# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CreditPayStubVerification")

model_instance <- CreditPayStubVerification$new()

test_that("verification_status", {
  # tests for the property `verification_status` (character)
  # Derived verification status.

  # uncomment below to test the property
  #expect_equal(model.instance$`verification_status`, "EXPECTED_RESULT")
})

test_that("verification_attributes", {
  # tests for the property `verification_attributes` (array[PayStubVerificationAttribute])

  # uncomment below to test the property
  #expect_equal(model.instance$`verification_attributes`, "EXPECTED_RESULT")
})
