# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AccountAccess")

model_instance <- AccountAccess$new()

test_that("unique_id", {
  # tests for the property `unique_id` (character)
  # The unique account identifier for this account. This value must match that returned by the data access API for this account.

  # uncomment below to test the property
  #expect_equal(model.instance$`unique_id`, "EXPECTED_RESULT")
})

test_that("authorized", {
  # tests for the property `authorized` (character)
  # Allow the application to see this account (and associated details, including balance) in the list of accounts  If unset, defaults to &#x60;true&#x60;.

  # uncomment below to test the property
  #expect_equal(model.instance$`authorized`, "EXPECTED_RESULT")
})

test_that("account_product_access", {
  # tests for the property `account_product_access` (AccountProductAccessNullable)

  # uncomment below to test the property
  #expect_equal(model.instance$`account_product_access`, "EXPECTED_RESULT")
})
