# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BankTransferCreateRequest")

model_instance <- BankTransferCreateRequest$new()

test_that("client_id", {
  # tests for the property `client_id` (character)
  # Your Plaid API &#x60;client_id&#x60;. The &#x60;client_id&#x60; is required and may be provided either in the &#x60;PLAID-CLIENT-ID&#x60; header or as part of a request body.

  # uncomment below to test the property
  #expect_equal(model.instance$`client_id`, "EXPECTED_RESULT")
})

test_that("secret", {
  # tests for the property `secret` (character)
  # Your Plaid API &#x60;secret&#x60;. The &#x60;secret&#x60; is required and may be provided either in the &#x60;PLAID-SECRET&#x60; header or as part of a request body.

  # uncomment below to test the property
  #expect_equal(model.instance$`secret`, "EXPECTED_RESULT")
})

test_that("idempotency_key", {
  # tests for the property `idempotency_key` (character)
  # A random key provided by the client, per unique bank transfer. Maximum of 50 characters.  The API supports idempotency for safely retrying requests without accidentally performing the same operation twice. For example, if a request to create a bank transfer fails due to a network connection error, you can retry the request with the same idempotency key to guarantee that only a single bank transfer is created.

  # uncomment below to test the property
  #expect_equal(model.instance$`idempotency_key`, "EXPECTED_RESULT")
})

test_that("access_token", {
  # tests for the property `access_token` (character)
  # The Plaid &#x60;access_token&#x60; for the account that will be debited or credited.

  # uncomment below to test the property
  #expect_equal(model.instance$`access_token`, "EXPECTED_RESULT")
})

test_that("account_id", {
  # tests for the property `account_id` (character)
  # The Plaid &#x60;account_id&#x60; for the account that will be debited or credited.

  # uncomment below to test the property
  #expect_equal(model.instance$`account_id`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (BankTransferType)

  # uncomment below to test the property
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("network", {
  # tests for the property `network` (BankTransferNetwork)

  # uncomment below to test the property
  #expect_equal(model.instance$`network`, "EXPECTED_RESULT")
})

test_that("amount", {
  # tests for the property `amount` (character)
  # The amount of the bank transfer (decimal string with two digits of precision e.g. \&quot;10.00\&quot;).

  # uncomment below to test the property
  #expect_equal(model.instance$`amount`, "EXPECTED_RESULT")
})

test_that("iso_currency_code", {
  # tests for the property `iso_currency_code` (character)
  # The currency of the transfer amount – should be set to \&quot;USD\&quot;.

  # uncomment below to test the property
  #expect_equal(model.instance$`iso_currency_code`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)
  # The transfer description. Maximum of 10 characters.

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("ach_class", {
  # tests for the property `ach_class` (ACHClass)

  # uncomment below to test the property
  #expect_equal(model.instance$`ach_class`, "EXPECTED_RESULT")
})

test_that("user", {
  # tests for the property `user` (BankTransferUser)

  # uncomment below to test the property
  #expect_equal(model.instance$`user`, "EXPECTED_RESULT")
})

test_that("custom_tag", {
  # tests for the property `custom_tag` (character)
  # An arbitrary string provided by the client for storage with the bank transfer. May be up to 100 characters.

  # uncomment below to test the property
  #expect_equal(model.instance$`custom_tag`, "EXPECTED_RESULT")
})

test_that("metadata", {
  # tests for the property `metadata` (map(character))
  # The Metadata object is a mapping of client-provided string fields to any string value. The following limitations apply: - The JSON values must be Strings (no nested JSON objects allowed) - Only ASCII characters may be used - Maximum of 50 key/value pairs - Maximum key length of 40 characters - Maximum value length of 500 characters 

  # uncomment below to test the property
  #expect_equal(model.instance$`metadata`, "EXPECTED_RESULT")
})

test_that("origination_account_id", {
  # tests for the property `origination_account_id` (character)
  # Plaid’s unique identifier for the origination account for this transfer. If you have more than one origination account, this value must be specified. Otherwise, this field should be left blank.

  # uncomment below to test the property
  #expect_equal(model.instance$`origination_account_id`, "EXPECTED_RESULT")
})
