# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ScreeningHitDateOfBirthItem")

model_instance <- ScreeningHitDateOfBirthItem$new()

test_that("analysis", {
  # tests for the property `analysis` (MatchSummary)

  # uncomment below to test the property
  #expect_equal(model.instance$`analysis`, "EXPECTED_RESULT")
})

test_that("data", {
  # tests for the property `data` (DateRange)

  # uncomment below to test the property
  #expect_equal(model.instance$`data`, "EXPECTED_RESULT")
})
