# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test StudentRepaymentPlan")

model_instance <- StudentRepaymentPlan$new()

test_that("description", {
  # tests for the property `description` (character)
  # The description of the repayment plan as provided by the servicer.

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (character)
  # The type of the repayment plan.

  # uncomment below to test the property
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})
