# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PaymentInitiationRecipientGetResponse")

model_instance <- PaymentInitiationRecipientGetResponse$new()

test_that("recipient_id", {
  # tests for the property `recipient_id` (character)
  # The ID of the recipient.

  # uncomment below to test the property
  #expect_equal(model.instance$`recipient_id`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # The name of the recipient.

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("address", {
  # tests for the property `address` (PaymentInitiationAddress)

  # uncomment below to test the property
  #expect_equal(model.instance$`address`, "EXPECTED_RESULT")
})

test_that("iban", {
  # tests for the property `iban` (character)
  # The International Bank Account Number (IBAN) for the recipient.

  # uncomment below to test the property
  #expect_equal(model.instance$`iban`, "EXPECTED_RESULT")
})

test_that("bacs", {
  # tests for the property `bacs` (RecipientBACSNullable)

  # uncomment below to test the property
  #expect_equal(model.instance$`bacs`, "EXPECTED_RESULT")
})

test_that("request_id", {
  # tests for the property `request_id` (character)
  # A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.

  # uncomment below to test the property
  #expect_equal(model.instance$`request_id`, "EXPECTED_RESULT")
})
