# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CustomerInitiatedReturnRisk")

model_instance <- CustomerInitiatedReturnRisk$new()

test_that("score", {
  # tests for the property `score` (integer)
  # A score from 0-99 that indicates the transaction return risk: a higher risk score suggests a higher return likelihood.

  # uncomment below to test the property
  #expect_equal(model.instance$`score`, "EXPECTED_RESULT")
})

test_that("risk_tier", {
  # tests for the property `risk_tier` (integer)
  # A tier corresponding to the projected likelihood that the transaction, if initiated, will be subject to a return.  In the &#x60;customer_initiated_return_risk&#x60; object, there are five risk tiers corresponding to the scores:   1: Predicted customer-initiated return incidence rate between 0.00% - 0.02%   2: Predicted customer-initiated return incidence rate between 0.02% - 0.05%   3: Predicted customer-initiated return incidence rate between 0.05% - 0.1%   4: Predicted customer-initiated return incidence rate between 0.1% - 0.5%   5: Predicted customer-initiated return incidence rate greater than 0.5% 

  # uncomment below to test the property
  #expect_equal(model.instance$`risk_tier`, "EXPECTED_RESULT")
})
