# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test IncomeVerificationPrecheckUser")

model_instance <- IncomeVerificationPrecheckUser$new()

test_that("first_name", {
  # tests for the property `first_name` (character)
  # The user&#39;s first name

  # uncomment below to test the property
  #expect_equal(model.instance$`first_name`, "EXPECTED_RESULT")
})

test_that("last_name", {
  # tests for the property `last_name` (character)
  # The user&#39;s last name

  # uncomment below to test the property
  #expect_equal(model.instance$`last_name`, "EXPECTED_RESULT")
})

test_that("email_address", {
  # tests for the property `email_address` (character)
  # The user&#39;s email address

  # uncomment below to test the property
  #expect_equal(model.instance$`email_address`, "EXPECTED_RESULT")
})

test_that("home_address", {
  # tests for the property `home_address` (SignalAddressData)

  # uncomment below to test the property
  #expect_equal(model.instance$`home_address`, "EXPECTED_RESULT")
})
