# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test TransactionsSyncRequestOptions")

model_instance <- TransactionsSyncRequestOptions$new()

test_that("include_original_description", {
  # tests for the property `include_original_description` (character)
  # Include the raw unparsed transaction description from the financial institution. This field is disabled by default. If you need this information in addition to the parsed data provided, contact your Plaid Account Manager.

  # uncomment below to test the property
  #expect_equal(model.instance$`include_original_description`, "EXPECTED_RESULT")
})

test_that("include_personal_finance_category", {
  # tests for the property `include_personal_finance_category` (character)
  # Include the [&#x60;personal_finance_category&#x60;](https://plaid.com/docs/api/products/transactions/#transactions-sync-response-added-personal-finance-category) object in the response.  See the [&#x60;taxonomy csv file&#x60;](https://plaid.com/documents/transactions-personal-finance-category-taxonomy.csv) for a full list of personal finance categories.  We’re introducing Category Rules - a new beta endpoint that will enable you to change the &#x60;personal_finance_category&#x60; for a transaction based on your users’ needs. When rules are set, the selected category will override the Plaid provided category. To learn more, send a note to transactions-feedback@plaid.com.

  # uncomment below to test the property
  #expect_equal(model.instance$`include_personal_finance_category`, "EXPECTED_RESULT")
})
