# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ProcessorNumber")

model_instance <- ProcessorNumber$new()

test_that("ach", {
  # tests for the property `ach` (NumbersACHNullable)

  # uncomment below to test the property
  #expect_equal(model.instance$`ach`, "EXPECTED_RESULT")
})

test_that("eft", {
  # tests for the property `eft` (NumbersEFTNullable)

  # uncomment below to test the property
  #expect_equal(model.instance$`eft`, "EXPECTED_RESULT")
})

test_that("international", {
  # tests for the property `international` (NumbersInternationalNullable)

  # uncomment below to test the property
  #expect_equal(model.instance$`international`, "EXPECTED_RESULT")
})

test_that("bacs", {
  # tests for the property `bacs` (NumbersBACSNullable)

  # uncomment below to test the property
  #expect_equal(model.instance$`bacs`, "EXPECTED_RESULT")
})
