# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test TransferAuthorizationDevice")

model_instance <- TransferAuthorizationDevice$new()

test_that("ip_address", {
  # tests for the property `ip_address` (character)
  # The IP address of the device being used to initiate the authorization.

  # uncomment below to test the property
  #expect_equal(model.instance$`ip_address`, "EXPECTED_RESULT")
})

test_that("user_agent", {
  # tests for the property `user_agent` (character)
  # The user agent of the device being used to initiate the authorization.

  # uncomment below to test the property
  #expect_equal(model.instance$`user_agent`, "EXPECTED_RESULT")
})
