# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Address")

model_instance <- Address$new()

test_that("data", {
  # tests for the property `data` (AddressData)

  # uncomment below to test the property
  #expect_equal(model.instance$`data`, "EXPECTED_RESULT")
})

test_that("primary", {
  # tests for the property `primary` (character)
  # When &#x60;true&#x60;, identifies the address as the primary address on an account.

  # uncomment below to test the property
  #expect_equal(model.instance$`primary`, "EXPECTED_RESULT")
})
