# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test TransferIntentCreate")

model_instance <- TransferIntentCreate$new()

test_that("id", {
  # tests for the property `id` (character)
  # Plaid&#39;s unique identifier for the transfer intent object.

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("created", {
  # tests for the property `created` (character)
  # The datetime the transfer was created. This will be of the form &#x60;2006-01-02T15:04:05Z&#x60;.

  # uncomment below to test the property
  #expect_equal(model.instance$`created`, "EXPECTED_RESULT")
})

test_that("status", {
  # tests for the property `status` (TransferIntentStatus)

  # uncomment below to test the property
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})

test_that("account_id", {
  # tests for the property `account_id` (character)
  # The Plaid &#x60;account_id&#x60; for the account that will be debited or credited. Returned only if &#x60;account_id&#x60; was set on intent creation.

  # uncomment below to test the property
  #expect_equal(model.instance$`account_id`, "EXPECTED_RESULT")
})

test_that("origination_account_id", {
  # tests for the property `origination_account_id` (character)
  # Plaid’s unique identifier for the origination account for the intent. If not provided, the default account will be used.

  # uncomment below to test the property
  #expect_equal(model.instance$`origination_account_id`, "EXPECTED_RESULT")
})

test_that("amount", {
  # tests for the property `amount` (character)
  # The amount of the transfer (decimal string with two digits of precision e.g. \&quot;10.00\&quot;).

  # uncomment below to test the property
  #expect_equal(model.instance$`amount`, "EXPECTED_RESULT")
})

test_that("mode", {
  # tests for the property `mode` (TransferIntentCreateMode)

  # uncomment below to test the property
  #expect_equal(model.instance$`mode`, "EXPECTED_RESULT")
})

test_that("ach_class", {
  # tests for the property `ach_class` (ACHClass)

  # uncomment below to test the property
  #expect_equal(model.instance$`ach_class`, "EXPECTED_RESULT")
})

test_that("user", {
  # tests for the property `user` (TransferUserInResponse)

  # uncomment below to test the property
  #expect_equal(model.instance$`user`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)
  # A description for the underlying transfer. Maximum of 8 characters.

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("metadata", {
  # tests for the property `metadata` (map(character))
  # The Metadata object is a mapping of client-provided string fields to any string value. The following limitations apply: - The JSON values must be Strings (no nested JSON objects allowed) - Only ASCII characters may be used - Maximum of 50 key/value pairs - Maximum key length of 40 characters - Maximum value length of 500 characters 

  # uncomment below to test the property
  #expect_equal(model.instance$`metadata`, "EXPECTED_RESULT")
})

test_that("iso_currency_code", {
  # tests for the property `iso_currency_code` (character)
  # The currency of the transfer amount, e.g. \&quot;USD\&quot;

  # uncomment below to test the property
  #expect_equal(model.instance$`iso_currency_code`, "EXPECTED_RESULT")
})

test_that("require_guarantee", {
  # tests for the property `require_guarantee` (character)
  # When &#x60;true&#x60;, the transfer requires a &#x60;GUARANTEED&#x60; decision by Plaid to proceed (Guaranteed ACH customers only).

  # uncomment below to test the property
  #expect_equal(model.instance$`require_guarantee`, "EXPECTED_RESULT")
})
