# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CreditPayStubEarnings")

model_instance <- CreditPayStubEarnings$new()

test_that("breakdown", {
  # tests for the property `breakdown` (array[PayStubEarningsBreakdown])

  # uncomment below to test the property
  #expect_equal(model.instance$`breakdown`, "EXPECTED_RESULT")
})

test_that("total", {
  # tests for the property `total` (PayStubEarningsTotal)

  # uncomment below to test the property
  #expect_equal(model.instance$`total`, "EXPECTED_RESULT")
})
