# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PersonalFinanceCategory")

model_instance <- PersonalFinanceCategory$new()

test_that("primary", {
  # tests for the property `primary` (character)
  # A high level category that communicates the broad category of the transaction.

  # uncomment below to test the property
  #expect_equal(model.instance$`primary`, "EXPECTED_RESULT")
})

test_that("detailed", {
  # tests for the property `detailed` (character)
  # A granular category conveying the transaction&#39;s intent. This field can also be used as a unique identifier for the category.

  # uncomment below to test the property
  #expect_equal(model.instance$`detailed`, "EXPECTED_RESULT")
})
