# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test LinkTokenGetMetadataResponse")

model_instance <- LinkTokenGetMetadataResponse$new()

test_that("initial_products", {
  # tests for the property `initial_products` (array[Products])
  # The &#x60;products&#x60; specified in the &#x60;/link/token/create&#x60; call.

  # uncomment below to test the property
  #expect_equal(model.instance$`initial_products`, "EXPECTED_RESULT")
})

test_that("webhook", {
  # tests for the property `webhook` (character)
  # The &#x60;webhook&#x60; specified in the &#x60;/link/token/create&#x60; call.

  # uncomment below to test the property
  #expect_equal(model.instance$`webhook`, "EXPECTED_RESULT")
})

test_that("country_codes", {
  # tests for the property `country_codes` (array[CountryCode])
  # The &#x60;country_codes&#x60; specified in the &#x60;/link/token/create&#x60; call.

  # uncomment below to test the property
  #expect_equal(model.instance$`country_codes`, "EXPECTED_RESULT")
})

test_that("language", {
  # tests for the property `language` (character)
  # The &#x60;language&#x60; specified in the &#x60;/link/token/create&#x60; call.

  # uncomment below to test the property
  #expect_equal(model.instance$`language`, "EXPECTED_RESULT")
})

test_that("institution_data", {
  # tests for the property `institution_data` (LinkTokenCreateInstitutionData)

  # uncomment below to test the property
  #expect_equal(model.instance$`institution_data`, "EXPECTED_RESULT")
})

test_that("account_filters", {
  # tests for the property `account_filters` (AccountFiltersResponse)

  # uncomment below to test the property
  #expect_equal(model.instance$`account_filters`, "EXPECTED_RESULT")
})

test_that("redirect_uri", {
  # tests for the property `redirect_uri` (character)
  # The &#x60;redirect_uri&#x60; specified in the &#x60;/link/token/create&#x60; call.

  # uncomment below to test the property
  #expect_equal(model.instance$`redirect_uri`, "EXPECTED_RESULT")
})

test_that("client_name", {
  # tests for the property `client_name` (character)
  # The &#x60;client_name&#x60; specified in the &#x60;/link/token/create&#x60; call.

  # uncomment below to test the property
  #expect_equal(model.instance$`client_name`, "EXPECTED_RESULT")
})
