# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test IdentityVerificationStepUpdatedWebhook")

model_instance <- IdentityVerificationStepUpdatedWebhook$new()

test_that("webhook_type", {
  # tests for the property `webhook_type` (character)
  # &#x60;IDENTITY_VERIFCATION&#x60;

  # uncomment below to test the property
  #expect_equal(model.instance$`webhook_type`, "EXPECTED_RESULT")
})

test_that("webhook_code", {
  # tests for the property `webhook_code` (character)
  # &#x60;STEP_UPDATED&#x60;

  # uncomment below to test the property
  #expect_equal(model.instance$`webhook_code`, "EXPECTED_RESULT")
})

test_that("identity_verification_id", {
  # tests for the property `identity_verification_id` (AnyType)
  # The ID of the associated Identity Verification attempt.

  # uncomment below to test the property
  #expect_equal(model.instance$`identity_verification_id`, "EXPECTED_RESULT")
})
