# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Owner")

model_instance <- Owner$new()

test_that("names", {
  # tests for the property `names` (array[character])
  # A list of names associated with the account by the financial institution. These should always be the names of individuals, even for business accounts. If the name of a business is reported, please contact Plaid Support. In the case of a joint account, Plaid will make a best effort to report the names of all account holders.  If an Item contains multiple accounts with different owner names, some institutions will report all names associated with the Item in each account&#39;s &#x60;names&#x60; array.

  # uncomment below to test the property
  #expect_equal(model.instance$`names`, "EXPECTED_RESULT")
})

test_that("phone_numbers", {
  # tests for the property `phone_numbers` (array[PhoneNumber])
  # A list of phone numbers associated with the account by the financial institution. May be an empty array if no relevant information is returned from the financial institution.

  # uncomment below to test the property
  #expect_equal(model.instance$`phone_numbers`, "EXPECTED_RESULT")
})

test_that("emails", {
  # tests for the property `emails` (array[Email])
  # A list of email addresses associated with the account by the financial institution. May be an empty array if no relevant information is returned from the financial institution.

  # uncomment below to test the property
  #expect_equal(model.instance$`emails`, "EXPECTED_RESULT")
})

test_that("addresses", {
  # tests for the property `addresses` (array[Address])
  # Data about the various addresses associated with the account by the financial institution. May be an empty array if no relevant information is returned from the financial institution.

  # uncomment below to test the property
  #expect_equal(model.instance$`addresses`, "EXPECTED_RESULT")
})
