# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test IdentityVerificationCreateRequest")

model_instance <- IdentityVerificationCreateRequest$new()

test_that("is_shareable", {
  # tests for the property `is_shareable` (character)
  # A flag specifying whether you would like Plaid to expose a shareable URL for the verification being created.

  # uncomment below to test the property
  #expect_equal(model.instance$`is_shareable`, "EXPECTED_RESULT")
})

test_that("template_id", {
  # tests for the property `template_id` (character)
  # ID of the associated Identity Verification template.

  # uncomment below to test the property
  #expect_equal(model.instance$`template_id`, "EXPECTED_RESULT")
})

test_that("gave_consent", {
  # tests for the property `gave_consent` (character)
  # A flag specifying whether the end user has already agreed to a privacy policy specifying that their data will be shared with Plaid for verification purposes.  If &#x60;gave_consent&#x60; is set to &#x60;true&#x60;, the &#x60;accept_tos&#x60; step will be marked as &#x60;skipped&#x60; and the end user&#39;s session will start at the next step requirement.

  # uncomment below to test the property
  #expect_equal(model.instance$`gave_consent`, "EXPECTED_RESULT")
})

test_that("user", {
  # tests for the property `user` (IdentityVerificationRequestUser)

  # uncomment below to test the property
  #expect_equal(model.instance$`user`, "EXPECTED_RESULT")
})

test_that("client_id", {
  # tests for the property `client_id` (character)
  # Your Plaid API &#x60;client_id&#x60;. The &#x60;client_id&#x60; is required and may be provided either in the &#x60;PLAID-CLIENT-ID&#x60; header or as part of a request body.

  # uncomment below to test the property
  #expect_equal(model.instance$`client_id`, "EXPECTED_RESULT")
})

test_that("secret", {
  # tests for the property `secret` (character)
  # Your Plaid API &#x60;secret&#x60;. The &#x60;secret&#x60; is required and may be provided either in the &#x60;PLAID-SECRET&#x60; header or as part of a request body.

  # uncomment below to test the property
  #expect_equal(model.instance$`secret`, "EXPECTED_RESULT")
})

test_that("is_idempotent", {
  # tests for the property `is_idempotent` (character)
  # An optional flag specifying how you would like Plaid to handle attempts to create an Identity Verification when an Identity Verification already exists for the provided &#x60;client_user_id&#x60; and &#x60;template_id&#x60;. If idempotency is enabled, Plaid will return the existing Identity Verification. If idempotency is disabled, Plaid will reject the request with a &#x60;400 Bad Request&#x60; status code if an Identity Verification already exists for the supplied &#x60;client_user_id&#x60; and &#x60;template_id&#x60;.

  # uncomment below to test the property
  #expect_equal(model.instance$`is_idempotent`, "EXPECTED_RESULT")
})
