# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test EmploymentVerification")

model_instance <- EmploymentVerification$new()

test_that("status", {
  # tests for the property `status` (EmploymentVerificationStatus)

  # uncomment below to test the property
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})

test_that("start_date", {
  # tests for the property `start_date` (character)
  # Start of employment in ISO 8601 format (YYYY-MM-DD).

  # uncomment below to test the property
  #expect_equal(model.instance$`start_date`, "EXPECTED_RESULT")
})

test_that("end_date", {
  # tests for the property `end_date` (character)
  # End of employment, if applicable. Provided in ISO 8601 format (YYY-MM-DD).

  # uncomment below to test the property
  #expect_equal(model.instance$`end_date`, "EXPECTED_RESULT")
})

test_that("employer", {
  # tests for the property `employer` (EmployerVerification)

  # uncomment below to test the property
  #expect_equal(model.instance$`employer`, "EXPECTED_RESULT")
})

test_that("title", {
  # tests for the property `title` (character)
  # Current title of employee.

  # uncomment below to test the property
  #expect_equal(model.instance$`title`, "EXPECTED_RESULT")
})

test_that("platform_ids", {
  # tests for the property `platform_ids` (PlatformIds)

  # uncomment below to test the property
  #expect_equal(model.instance$`platform_ids`, "EXPECTED_RESULT")
})
