# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CreditBankIncomeTransaction")

model_instance <- CreditBankIncomeTransaction$new()

test_that("amount", {
  # tests for the property `amount` (numeric)
  # The settled value of the transaction, denominated in the transactions&#39;s currency as stated in &#x60;iso_currency_code&#x60; or &#x60;unofficial_currency_code&#x60;. Positive values when money moves out of the account; negative values when money moves in. For example, credit card purchases are positive; credit card payment, direct deposits, and refunds are negative.

  # uncomment below to test the property
  #expect_equal(model.instance$`amount`, "EXPECTED_RESULT")
})

test_that("date", {
  # tests for the property `date` (character)
  # For pending transactions, the date that the transaction occurred; for posted transactions, the date that the transaction posted. Both dates are returned in an ISO 8601 format (YYYY-MM-DD).

  # uncomment below to test the property
  #expect_equal(model.instance$`date`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # The merchant name or transaction description.

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("original_description", {
  # tests for the property `original_description` (character)
  # The string returned by the financial institution to describe the transaction.

  # uncomment below to test the property
  #expect_equal(model.instance$`original_description`, "EXPECTED_RESULT")
})

test_that("pending", {
  # tests for the property `pending` (character)
  # When true, identifies the transaction as pending or unsettled. Pending transaction details (name, type, amount, category ID) may change before they are settled.

  # uncomment below to test the property
  #expect_equal(model.instance$`pending`, "EXPECTED_RESULT")
})

test_that("transaction_id", {
  # tests for the property `transaction_id` (character)
  # The unique ID of the transaction. Like all Plaid identifiers, the &#x60;transaction_id&#x60; is case sensitive.

  # uncomment below to test the property
  #expect_equal(model.instance$`transaction_id`, "EXPECTED_RESULT")
})

test_that("check_number", {
  # tests for the property `check_number` (character)
  # The check number of the transaction. This field is only populated for check transactions.

  # uncomment below to test the property
  #expect_equal(model.instance$`check_number`, "EXPECTED_RESULT")
})

test_that("iso_currency_code", {
  # tests for the property `iso_currency_code` (character)
  # The ISO 4217 currency code of the amount or balance.

  # uncomment below to test the property
  #expect_equal(model.instance$`iso_currency_code`, "EXPECTED_RESULT")
})

test_that("unofficial_currency_code", {
  # tests for the property `unofficial_currency_code` (character)
  # The unofficial currency code associated with the amount or balance. Always &#x60;null&#x60; if &#x60;iso_currency_code&#x60; is non-null. Unofficial currency codes are used for currencies that do not have official ISO currency codes, such as cryptocurrencies and the currencies of certain countries.

  # uncomment below to test the property
  #expect_equal(model.instance$`unofficial_currency_code`, "EXPECTED_RESULT")
})
