# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test TransactionsCategoryRule")

model_instance <- TransactionsCategoryRule$new()

test_that("id", {
  # tests for the property `id` (character)
  # A unique identifier of the rule created

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("item_id", {
  # tests for the property `item_id` (character)
  # A unique identifier of the item the rule was created for

  # uncomment below to test the property
  #expect_equal(model.instance$`item_id`, "EXPECTED_RESULT")
})

test_that("created_at", {
  # tests for the property `created_at` (character)
  # Date and time when a rule was created in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format ( &#x60;YYYY-MM-DDTHH:mm:ssZ&#x60; ). 

  # uncomment below to test the property
  #expect_equal(model.instance$`created_at`, "EXPECTED_RESULT")
})

test_that("personal_finance_category", {
  # tests for the property `personal_finance_category` (character)
  # Personal finance category unique identifier.  In the personal finance category taxonomy, this field is represented by the detailed category field. 

  # uncomment below to test the property
  #expect_equal(model.instance$`personal_finance_category`, "EXPECTED_RESULT")
})

test_that("rule_details", {
  # tests for the property `rule_details` (TransactionsRuleDetails)

  # uncomment below to test the property
  #expect_equal(model.instance$`rule_details`, "EXPECTED_RESULT")
})
