# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ExternalPaymentOptions")

model_instance <- ExternalPaymentOptions$new()

test_that("request_refund_details", {
  # tests for the property `request_refund_details` (character)
  # When &#x60;true&#x60;, Plaid will attempt to request refund details from the payee&#39;s financial institution.  Support varies between financial institutions and will not always be available.  If refund details could be retrieved, they will be available in the &#x60;/payment_initiation/payment/get&#x60; response.

  # uncomment below to test the property
  #expect_equal(model.instance$`request_refund_details`, "EXPECTED_RESULT")
})

test_that("iban", {
  # tests for the property `iban` (character)
  # The International Bank Account Number (IBAN) for the payer&#39;s account. If provided, the end user will be able to send payments only from the specified bank account.

  # uncomment below to test the property
  #expect_equal(model.instance$`iban`, "EXPECTED_RESULT")
})

test_that("bacs", {
  # tests for the property `bacs` (PaymentInitiationOptionalRestrictionBacs)

  # uncomment below to test the property
  #expect_equal(model.instance$`bacs`, "EXPECTED_RESULT")
})

test_that("wallet_id", {
  # tests for the property `wallet_id` (character)
  # The EMI (E-Money Institution) wallet that this payment is associated with, if any. This wallet is used as an intermediary account to enable Plaid to reconcile the settlement of funds for Payment Initiation requests.

  # uncomment below to test the property
  #expect_equal(model.instance$`wallet_id`, "EXPECTED_RESULT")
})

test_that("scheme", {
  # tests for the property `scheme` (PaymentScheme)

  # uncomment below to test the property
  #expect_equal(model.instance$`scheme`, "EXPECTED_RESULT")
})
