# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CreditBankIncomeSummary")

model_instance <- CreditBankIncomeSummary$new()

test_that("total_amount", {
  # tests for the property `total_amount` (numeric)
  # Total amount of earnings across all the income sources in the end user&#39;s Items for the days requested by the client.

  # uncomment below to test the property
  #expect_equal(model.instance$`total_amount`, "EXPECTED_RESULT")
})

test_that("iso_currency_code", {
  # tests for the property `iso_currency_code` (character)
  # The ISO 4217 currency code of the amount or balance.

  # uncomment below to test the property
  #expect_equal(model.instance$`iso_currency_code`, "EXPECTED_RESULT")
})

test_that("unofficial_currency_code", {
  # tests for the property `unofficial_currency_code` (character)
  # The unofficial currency code associated with the amount or balance. Always &#x60;null&#x60; if &#x60;iso_currency_code&#x60; is non-null. Unofficial currency codes are used for currencies that do not have official ISO currency codes, such as cryptocurrencies and the currencies of certain countries.

  # uncomment below to test the property
  #expect_equal(model.instance$`unofficial_currency_code`, "EXPECTED_RESULT")
})

test_that("start_date", {
  # tests for the property `start_date` (character)
  # The earliest date within the days requested in which all income sources identified by Plaid appear in a user&#39;s account. The date will be returned in an ISO 8601 format (YYYY-MM-DD).

  # uncomment below to test the property
  #expect_equal(model.instance$`start_date`, "EXPECTED_RESULT")
})

test_that("end_date", {
  # tests for the property `end_date` (character)
  # The latest date in which all income sources identified by Plaid appear in the user&#39;s account. The date will be returned in an ISO 8601 format (YYYY-MM-DD).

  # uncomment below to test the property
  #expect_equal(model.instance$`end_date`, "EXPECTED_RESULT")
})

test_that("income_sources_count", {
  # tests for the property `income_sources_count` (integer)
  # Number of income sources per end user.

  # uncomment below to test the property
  #expect_equal(model.instance$`income_sources_count`, "EXPECTED_RESULT")
})

test_that("income_categories_count", {
  # tests for the property `income_categories_count` (integer)
  # Number of income categories per end user.

  # uncomment below to test the property
  #expect_equal(model.instance$`income_categories_count`, "EXPECTED_RESULT")
})

test_that("income_transactions_count", {
  # tests for the property `income_transactions_count` (integer)
  # Number of income transactions per end user.

  # uncomment below to test the property
  #expect_equal(model.instance$`income_transactions_count`, "EXPECTED_RESULT")
})

test_that("historical_summary", {
  # tests for the property `historical_summary` (array[CreditBankIncomeHistoricalSummary])

  # uncomment below to test the property
  #expect_equal(model.instance$`historical_summary`, "EXPECTED_RESULT")
})
