# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PhysicalDocumentExtractedDataAnalysis")

model_instance <- PhysicalDocumentExtractedDataAnalysis$new()

test_that("name", {
  # tests for the property `name` (DocumentNameMatchCode)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("date_of_birth", {
  # tests for the property `date_of_birth` (DocumentDateOfBirthMatchCode)

  # uncomment below to test the property
  #expect_equal(model.instance$`date_of_birth`, "EXPECTED_RESULT")
})

test_that("expiration_date", {
  # tests for the property `expiration_date` (ExpirationDate)

  # uncomment below to test the property
  #expect_equal(model.instance$`expiration_date`, "EXPECTED_RESULT")
})

test_that("issuing_country", {
  # tests for the property `issuing_country` (IssuingCountry)

  # uncomment below to test the property
  #expect_equal(model.instance$`issuing_country`, "EXPECTED_RESULT")
})
