# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AssetReportItem")

model_instance <- AssetReportItem$new()

test_that("item_id", {
  # tests for the property `item_id` (character)
  # The &#x60;item_id&#x60; of the Item associated with this webhook, warning, or error

  # uncomment below to test the property
  #expect_equal(model.instance$`item_id`, "EXPECTED_RESULT")
})

test_that("institution_name", {
  # tests for the property `institution_name` (character)
  # The full financial institution name associated with the Item.

  # uncomment below to test the property
  #expect_equal(model.instance$`institution_name`, "EXPECTED_RESULT")
})

test_that("institution_id", {
  # tests for the property `institution_id` (character)
  # The id of the financial institution associated with the Item.

  # uncomment below to test the property
  #expect_equal(model.instance$`institution_id`, "EXPECTED_RESULT")
})

test_that("date_last_updated", {
  # tests for the property `date_last_updated` (character)
  # The date and time when this Item’s data was last retrieved from the financial institution, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format.

  # uncomment below to test the property
  #expect_equal(model.instance$`date_last_updated`, "EXPECTED_RESULT")
})

test_that("accounts", {
  # tests for the property `accounts` (array[AccountAssets])
  # Data about each of the accounts open on the Item.

  # uncomment below to test the property
  #expect_equal(model.instance$`accounts`, "EXPECTED_RESULT")
})
