# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test WatchlistScreeningReview")

model_instance <- WatchlistScreeningReview$new()

test_that("id", {
  # tests for the property `id` (character)
  # ID of the associated review.

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("confirmed_hits", {
  # tests for the property `confirmed_hits` (array[character])
  # Hits marked as a true positive after thorough manual review. These hits will never recur or be updated once dismissed. In most cases, confirmed hits indicate that the customer should be rejected.

  # uncomment below to test the property
  #expect_equal(model.instance$`confirmed_hits`, "EXPECTED_RESULT")
})

test_that("dismissed_hits", {
  # tests for the property `dismissed_hits` (array[character])
  # Hits marked as a false positive after thorough manual review. These hits will never recur or be updated once dismissed.

  # uncomment below to test the property
  #expect_equal(model.instance$`dismissed_hits`, "EXPECTED_RESULT")
})

test_that("comment", {
  # tests for the property `comment` (character)
  # A comment submitted by a team member as part of reviewing a watchlist screening.

  # uncomment below to test the property
  #expect_equal(model.instance$`comment`, "EXPECTED_RESULT")
})

test_that("audit_trail", {
  # tests for the property `audit_trail` (WatchlistScreeningAuditTrail)

  # uncomment below to test the property
  #expect_equal(model.instance$`audit_trail`, "EXPECTED_RESULT")
})
