# The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.146.0
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title AccountAssetsAllOf
#'
#' @description AccountAssetsAllOf Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field days_available  numeric 
#'
#' @field transactions  list( \link{AssetReportTransaction} ) 
#'
#' @field owners  list( \link{Owner} ) 
#'
#' @field historical_balances  list( \link{HistoricalBalance} ) 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
AccountAssetsAllOf <- R6::R6Class(
  'AccountAssetsAllOf',
  public = list(
    `days_available` = NULL,
    `transactions` = NULL,
    `owners` = NULL,
    `historical_balances` = NULL,
    initialize = function(
        `days_available`, `transactions`, `owners`, `historical_balances`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`days_available`)) {
        self$`days_available` <- `days_available`
      }
      if (!missing(`transactions`)) {
        stopifnot(is.vector(`transactions`), length(`transactions`) != 0)
        sapply(`transactions`, function(x) stopifnot(R6::is.R6(x)))
        self$`transactions` <- `transactions`
      }
      if (!missing(`owners`)) {
        stopifnot(is.vector(`owners`), length(`owners`) != 0)
        sapply(`owners`, function(x) stopifnot(R6::is.R6(x)))
        self$`owners` <- `owners`
      }
      if (!missing(`historical_balances`)) {
        stopifnot(is.vector(`historical_balances`), length(`historical_balances`) != 0)
        sapply(`historical_balances`, function(x) stopifnot(R6::is.R6(x)))
        self$`historical_balances` <- `historical_balances`
      }
    },
    toJSON = function() {
      AccountAssetsAllOfObject <- list()
      if (!is.null(self$`days_available`)) {
        AccountAssetsAllOfObject[['days_available']] <-
          self$`days_available`
      }
      if (!is.null(self$`transactions`)) {
        AccountAssetsAllOfObject[['transactions']] <-
          lapply(self$`transactions`, function(x) x$toJSON())
      }
      if (!is.null(self$`owners`)) {
        AccountAssetsAllOfObject[['owners']] <-
          lapply(self$`owners`, function(x) x$toJSON())
      }
      if (!is.null(self$`historical_balances`)) {
        AccountAssetsAllOfObject[['historical_balances']] <-
          lapply(self$`historical_balances`, function(x) x$toJSON())
      }

      AccountAssetsAllOfObject
    },
    fromJSON = function(AccountAssetsAllOfJson) {
      AccountAssetsAllOfObject <- jsonlite::fromJSON(AccountAssetsAllOfJson)
      if (!is.null(AccountAssetsAllOfObject$`days_available`)) {
        self$`days_available` <- AccountAssetsAllOfObject$`days_available`
      }
      if (!is.null(AccountAssetsAllOfObject$`transactions`)) {
        self$`transactions` <- ApiClient$new()$deserializeObj(AccountAssetsAllOfObject$`transactions`, "array[AssetReportTransaction]", loadNamespace("plaidr"))
      }
      if (!is.null(AccountAssetsAllOfObject$`owners`)) {
        self$`owners` <- ApiClient$new()$deserializeObj(AccountAssetsAllOfObject$`owners`, "array[Owner]", loadNamespace("plaidr"))
      }
      if (!is.null(AccountAssetsAllOfObject$`historical_balances`)) {
        self$`historical_balances` <- ApiClient$new()$deserializeObj(AccountAssetsAllOfObject$`historical_balances`, "array[HistoricalBalance]", loadNamespace("plaidr"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`days_available`)) {
        sprintf(
        '"days_available":
          %d
                ',
        self$`days_available`
        )},
        if (!is.null(self$`transactions`)) {
        sprintf(
        '"transactions":
        [%s]
',
        paste(sapply(self$`transactions`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`owners`)) {
        sprintf(
        '"owners":
        [%s]
',
        paste(sapply(self$`owners`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`historical_balances`)) {
        sprintf(
        '"historical_balances":
        [%s]
',
        paste(sapply(self$`historical_balances`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(AccountAssetsAllOfJson) {
      AccountAssetsAllOfObject <- jsonlite::fromJSON(AccountAssetsAllOfJson)
      self$`days_available` <- AccountAssetsAllOfObject$`days_available`
      self$`transactions` <- ApiClient$new()$deserializeObj(AccountAssetsAllOfObject$`transactions`, "array[AssetReportTransaction]", loadNamespace("plaidr"))
      self$`owners` <- ApiClient$new()$deserializeObj(AccountAssetsAllOfObject$`owners`, "array[Owner]", loadNamespace("plaidr"))
      self$`historical_balances` <- ApiClient$new()$deserializeObj(AccountAssetsAllOfObject$`historical_balances`, "array[HistoricalBalance]", loadNamespace("plaidr"))
      self
    }
  )
)
