# The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.146.0
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title AccountAssets
#'
#' @description AccountAssets Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field account_id  character 
#'
#' @field balances  \link{AccountBalance} 
#'
#' @field mask  character 
#'
#' @field name  character 
#'
#' @field official_name  character 
#'
#' @field type  \link{AccountType} 
#'
#' @field subtype  \link{AccountSubtype} 
#'
#' @field verification_status  character [optional]
#'
#' @field days_available  numeric 
#'
#' @field transactions  list( \link{AssetReportTransaction} ) 
#'
#' @field owners  list( \link{Owner} ) 
#'
#' @field historical_balances  list( \link{HistoricalBalance} ) 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
AccountAssets <- R6::R6Class(
  'AccountAssets',
  public = list(
    `account_id` = NULL,
    `balances` = NULL,
    `mask` = NULL,
    `name` = NULL,
    `official_name` = NULL,
    `type` = NULL,
    `subtype` = NULL,
    `verification_status` = NULL,
    `days_available` = NULL,
    `transactions` = NULL,
    `owners` = NULL,
    `historical_balances` = NULL,
    initialize = function(
        `account_id`, `balances`, `mask`, `name`, `official_name`, `type`, `subtype`, `days_available`, `transactions`, `owners`, `historical_balances`, `verification_status`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`account_id`)) {
        stopifnot(is.character(`account_id`), length(`account_id`) == 1)
        self$`account_id` <- `account_id`
      }
      if (!missing(`balances`)) {
        stopifnot(R6::is.R6(`balances`))
        self$`balances` <- `balances`
      }
      if (!missing(`mask`)) {
        stopifnot(is.character(`mask`), length(`mask`) == 1)
        self$`mask` <- `mask`
      }
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`official_name`)) {
        stopifnot(is.character(`official_name`), length(`official_name`) == 1)
        self$`official_name` <- `official_name`
      }
      if (!missing(`type`)) {
        stopifnot(R6::is.R6(`type`))
        self$`type` <- `type`
      }
      if (!missing(`subtype`)) {
        stopifnot(R6::is.R6(`subtype`))
        self$`subtype` <- `subtype`
      }
      if (!missing(`days_available`)) {
        self$`days_available` <- `days_available`
      }
      if (!missing(`transactions`)) {
        stopifnot(is.vector(`transactions`), length(`transactions`) != 0)
        sapply(`transactions`, function(x) stopifnot(R6::is.R6(x)))
        self$`transactions` <- `transactions`
      }
      if (!missing(`owners`)) {
        stopifnot(is.vector(`owners`), length(`owners`) != 0)
        sapply(`owners`, function(x) stopifnot(R6::is.R6(x)))
        self$`owners` <- `owners`
      }
      if (!missing(`historical_balances`)) {
        stopifnot(is.vector(`historical_balances`), length(`historical_balances`) != 0)
        sapply(`historical_balances`, function(x) stopifnot(R6::is.R6(x)))
        self$`historical_balances` <- `historical_balances`
      }
      if (!is.null(`verification_status`)) {
        stopifnot(is.character(`verification_status`), length(`verification_status`) == 1)
        self$`verification_status` <- `verification_status`
      }
    },
    toJSON = function() {
      AccountAssetsObject <- list()
      if (!is.null(self$`account_id`)) {
        AccountAssetsObject[['account_id']] <-
          self$`account_id`
      }
      if (!is.null(self$`balances`)) {
        AccountAssetsObject[['balances']] <-
          self$`balances`$toJSON()
      }
      if (!is.null(self$`mask`)) {
        AccountAssetsObject[['mask']] <-
          self$`mask`
      }
      if (!is.null(self$`name`)) {
        AccountAssetsObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`official_name`)) {
        AccountAssetsObject[['official_name']] <-
          self$`official_name`
      }
      if (!is.null(self$`type`)) {
        AccountAssetsObject[['type']] <-
          self$`type`$toJSON()
      }
      if (!is.null(self$`subtype`)) {
        AccountAssetsObject[['subtype']] <-
          self$`subtype`$toJSON()
      }
      if (!is.null(self$`verification_status`)) {
        AccountAssetsObject[['verification_status']] <-
          self$`verification_status`
      }
      if (!is.null(self$`days_available`)) {
        AccountAssetsObject[['days_available']] <-
          self$`days_available`
      }
      if (!is.null(self$`transactions`)) {
        AccountAssetsObject[['transactions']] <-
          lapply(self$`transactions`, function(x) x$toJSON())
      }
      if (!is.null(self$`owners`)) {
        AccountAssetsObject[['owners']] <-
          lapply(self$`owners`, function(x) x$toJSON())
      }
      if (!is.null(self$`historical_balances`)) {
        AccountAssetsObject[['historical_balances']] <-
          lapply(self$`historical_balances`, function(x) x$toJSON())
      }

      AccountAssetsObject
    },
    fromJSON = function(AccountAssetsJson) {
      AccountAssetsObject <- jsonlite::fromJSON(AccountAssetsJson)
      if (!is.null(AccountAssetsObject$`account_id`)) {
        self$`account_id` <- AccountAssetsObject$`account_id`
      }
      if (!is.null(AccountAssetsObject$`balances`)) {
        balancesObject <- AccountBalance$new()
        balancesObject$fromJSON(jsonlite::toJSON(AccountAssetsObject$balances, auto_unbox = TRUE, digits = NA))
        self$`balances` <- balancesObject
      }
      if (!is.null(AccountAssetsObject$`mask`)) {
        self$`mask` <- AccountAssetsObject$`mask`
      }
      if (!is.null(AccountAssetsObject$`name`)) {
        self$`name` <- AccountAssetsObject$`name`
      }
      if (!is.null(AccountAssetsObject$`official_name`)) {
        self$`official_name` <- AccountAssetsObject$`official_name`
      }
      if (!is.null(AccountAssetsObject$`type`)) {
        typeObject <- AccountType$new()
        typeObject$fromJSON(jsonlite::toJSON(AccountAssetsObject$type, auto_unbox = TRUE, digits = NA))
        self$`type` <- typeObject
      }
      if (!is.null(AccountAssetsObject$`subtype`)) {
        subtypeObject <- AccountSubtype$new()
        subtypeObject$fromJSON(jsonlite::toJSON(AccountAssetsObject$subtype, auto_unbox = TRUE, digits = NA))
        self$`subtype` <- subtypeObject
      }
      if (!is.null(AccountAssetsObject$`verification_status`)) {
        self$`verification_status` <- AccountAssetsObject$`verification_status`
      }
      if (!is.null(AccountAssetsObject$`days_available`)) {
        self$`days_available` <- AccountAssetsObject$`days_available`
      }
      if (!is.null(AccountAssetsObject$`transactions`)) {
        self$`transactions` <- ApiClient$new()$deserializeObj(AccountAssetsObject$`transactions`, "array[AssetReportTransaction]", loadNamespace("plaidr"))
      }
      if (!is.null(AccountAssetsObject$`owners`)) {
        self$`owners` <- ApiClient$new()$deserializeObj(AccountAssetsObject$`owners`, "array[Owner]", loadNamespace("plaidr"))
      }
      if (!is.null(AccountAssetsObject$`historical_balances`)) {
        self$`historical_balances` <- ApiClient$new()$deserializeObj(AccountAssetsObject$`historical_balances`, "array[HistoricalBalance]", loadNamespace("plaidr"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`account_id`)) {
        sprintf(
        '"account_id":
          "%s"
                ',
        self$`account_id`
        )},
        if (!is.null(self$`balances`)) {
        sprintf(
        '"balances":
        %s
        ',
        jsonlite::toJSON(self$`balances`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`mask`)) {
        sprintf(
        '"mask":
          "%s"
                ',
        self$`mask`
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`official_name`)) {
        sprintf(
        '"official_name":
          "%s"
                ',
        self$`official_name`
        )},
        if (!is.null(self$`type`)) {
        sprintf(
        '"type":
        %s
        ',
        jsonlite::toJSON(self$`type`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`subtype`)) {
        sprintf(
        '"subtype":
        %s
        ',
        jsonlite::toJSON(self$`subtype`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`verification_status`)) {
        sprintf(
        '"verification_status":
          "%s"
                ',
        self$`verification_status`
        )},
        if (!is.null(self$`days_available`)) {
        sprintf(
        '"days_available":
          %d
                ',
        self$`days_available`
        )},
        if (!is.null(self$`transactions`)) {
        sprintf(
        '"transactions":
        [%s]
',
        paste(sapply(self$`transactions`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`owners`)) {
        sprintf(
        '"owners":
        [%s]
',
        paste(sapply(self$`owners`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`historical_balances`)) {
        sprintf(
        '"historical_balances":
        [%s]
',
        paste(sapply(self$`historical_balances`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(AccountAssetsJson) {
      AccountAssetsObject <- jsonlite::fromJSON(AccountAssetsJson)
      self$`account_id` <- AccountAssetsObject$`account_id`
      self$`balances` <- AccountBalance$new()$fromJSON(jsonlite::toJSON(AccountAssetsObject$balances, auto_unbox = TRUE, digits = NA))
      self$`mask` <- AccountAssetsObject$`mask`
      self$`name` <- AccountAssetsObject$`name`
      self$`official_name` <- AccountAssetsObject$`official_name`
      self$`type` <- AccountType$new()$fromJSON(jsonlite::toJSON(AccountAssetsObject$type, auto_unbox = TRUE, digits = NA))
      self$`subtype` <- AccountSubtype$new()$fromJSON(jsonlite::toJSON(AccountAssetsObject$subtype, auto_unbox = TRUE, digits = NA))
      self$`verification_status` <- AccountAssetsObject$`verification_status`
      self$`days_available` <- AccountAssetsObject$`days_available`
      self$`transactions` <- ApiClient$new()$deserializeObj(AccountAssetsObject$`transactions`, "array[AssetReportTransaction]", loadNamespace("plaidr"))
      self$`owners` <- ApiClient$new()$deserializeObj(AccountAssetsObject$`owners`, "array[Owner]", loadNamespace("plaidr"))
      self$`historical_balances` <- ApiClient$new()$deserializeObj(AccountAssetsObject$`historical_balances`, "array[HistoricalBalance]", loadNamespace("plaidr"))
      self
    }
  )
)
