# The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.146.0
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title AccountsBalanceGetRequestOptions
#'
#' @description AccountsBalanceGetRequestOptions Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field account_ids  list( character ) [optional]
#'
#' @field min_last_updated_datetime MinLastUpdatedDatetime character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
AccountsBalanceGetRequestOptions <- R6::R6Class(
  'AccountsBalanceGetRequestOptions',
  public = list(
    `account_ids` = NULL,
    `min_last_updated_datetime` = NULL,
    initialize = function(
        `account_ids`=NULL, `min_last_updated_datetime`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`account_ids`)) {
        stopifnot(is.vector(`account_ids`), length(`account_ids`) != 0)
        sapply(`account_ids`, function(x) stopifnot(is.character(x)))
        self$`account_ids` <- `account_ids`
      }
      if (!is.null(`min_last_updated_datetime`)) {
        stopifnot(is.character(`min_last_updated_datetime`), length(`min_last_updated_datetime`) == 1)
        self$`min_last_updated_datetime` <- `min_last_updated_datetime`
      }
    },
    toJSON = function() {
      AccountsBalanceGetRequestOptionsObject <- list()
      if (!is.null(self$`account_ids`)) {
        AccountsBalanceGetRequestOptionsObject[['account_ids']] <-
          self$`account_ids`
      }
      if (!is.null(self$`min_last_updated_datetime`)) {
        AccountsBalanceGetRequestOptionsObject[['min_last_updated_datetime']] <-
          self$`min_last_updated_datetime`
      }

      AccountsBalanceGetRequestOptionsObject
    },
    fromJSON = function(AccountsBalanceGetRequestOptionsJson) {
      AccountsBalanceGetRequestOptionsObject <- jsonlite::fromJSON(AccountsBalanceGetRequestOptionsJson)
      if (!is.null(AccountsBalanceGetRequestOptionsObject$`account_ids`)) {
        self$`account_ids` <- ApiClient$new()$deserializeObj(AccountsBalanceGetRequestOptionsObject$`account_ids`, "array[character]", loadNamespace("plaidr"))
      }
      if (!is.null(AccountsBalanceGetRequestOptionsObject$`min_last_updated_datetime`)) {
        self$`min_last_updated_datetime` <- AccountsBalanceGetRequestOptionsObject$`min_last_updated_datetime`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`account_ids`)) {
        sprintf(
        '"account_ids":
           [%s]
        ',
        paste(unlist(lapply(self$`account_ids`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`min_last_updated_datetime`)) {
        sprintf(
        '"min_last_updated_datetime":
          "%s"
                ',
        self$`min_last_updated_datetime`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(AccountsBalanceGetRequestOptionsJson) {
      AccountsBalanceGetRequestOptionsObject <- jsonlite::fromJSON(AccountsBalanceGetRequestOptionsJson)
      self$`account_ids` <- ApiClient$new()$deserializeObj(AccountsBalanceGetRequestOptionsObject$`account_ids`, "array[character]", loadNamespace("plaidr"))
      self$`min_last_updated_datetime` <- AccountsBalanceGetRequestOptionsObject$`min_last_updated_datetime`
      self
    }
  )
)
