# The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.146.0
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title AccountsBalanceGetRequest
#'
#' @description AccountsBalanceGetRequest Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field access_token AccessToken character 
#'
#' @field secret APISecret character [optional]
#'
#' @field client_id ClientID character [optional]
#'
#' @field options  \link{AccountsBalanceGetRequestOptions} [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
AccountsBalanceGetRequest <- R6::R6Class(
  'AccountsBalanceGetRequest',
  public = list(
    `access_token` = NULL,
    `secret` = NULL,
    `client_id` = NULL,
    `options` = NULL,
    initialize = function(
        `access_token`, `secret`=NULL, `client_id`=NULL, `options`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`access_token`)) {
        stopifnot(is.character(`access_token`), length(`access_token`) == 1)
        self$`access_token` <- `access_token`
      }
      if (!is.null(`secret`)) {
        stopifnot(is.character(`secret`), length(`secret`) == 1)
        self$`secret` <- `secret`
      }
      if (!is.null(`client_id`)) {
        stopifnot(is.character(`client_id`), length(`client_id`) == 1)
        self$`client_id` <- `client_id`
      }
      if (!is.null(`options`)) {
        stopifnot(R6::is.R6(`options`))
        self$`options` <- `options`
      }
    },
    toJSON = function() {
      AccountsBalanceGetRequestObject <- list()
      if (!is.null(self$`access_token`)) {
        AccountsBalanceGetRequestObject[['access_token']] <-
          self$`access_token`
      }
      if (!is.null(self$`secret`)) {
        AccountsBalanceGetRequestObject[['secret']] <-
          self$`secret`
      }
      if (!is.null(self$`client_id`)) {
        AccountsBalanceGetRequestObject[['client_id']] <-
          self$`client_id`
      }
      if (!is.null(self$`options`)) {
        AccountsBalanceGetRequestObject[['options']] <-
          self$`options`$toJSON()
      }

      AccountsBalanceGetRequestObject
    },
    fromJSON = function(AccountsBalanceGetRequestJson) {
      AccountsBalanceGetRequestObject <- jsonlite::fromJSON(AccountsBalanceGetRequestJson)
      if (!is.null(AccountsBalanceGetRequestObject$`access_token`)) {
        self$`access_token` <- AccountsBalanceGetRequestObject$`access_token`
      }
      if (!is.null(AccountsBalanceGetRequestObject$`secret`)) {
        self$`secret` <- AccountsBalanceGetRequestObject$`secret`
      }
      if (!is.null(AccountsBalanceGetRequestObject$`client_id`)) {
        self$`client_id` <- AccountsBalanceGetRequestObject$`client_id`
      }
      if (!is.null(AccountsBalanceGetRequestObject$`options`)) {
        optionsObject <- AccountsBalanceGetRequestOptions$new()
        optionsObject$fromJSON(jsonlite::toJSON(AccountsBalanceGetRequestObject$options, auto_unbox = TRUE, digits = NA))
        self$`options` <- optionsObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`access_token`)) {
        sprintf(
        '"access_token":
          "%s"
                ',
        self$`access_token`
        )},
        if (!is.null(self$`secret`)) {
        sprintf(
        '"secret":
          "%s"
                ',
        self$`secret`
        )},
        if (!is.null(self$`client_id`)) {
        sprintf(
        '"client_id":
          "%s"
                ',
        self$`client_id`
        )},
        if (!is.null(self$`options`)) {
        sprintf(
        '"options":
        %s
        ',
        jsonlite::toJSON(self$`options`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(AccountsBalanceGetRequestJson) {
      AccountsBalanceGetRequestObject <- jsonlite::fromJSON(AccountsBalanceGetRequestJson)
      self$`access_token` <- AccountsBalanceGetRequestObject$`access_token`
      self$`secret` <- AccountsBalanceGetRequestObject$`secret`
      self$`client_id` <- AccountsBalanceGetRequestObject$`client_id`
      self$`options` <- AccountsBalanceGetRequestOptions$new()$fromJSON(jsonlite::toJSON(AccountsBalanceGetRequestObject$options, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)
