# The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.146.0
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ApplicationGetRequest
#'
#' @description ApplicationGetRequest Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field client_id ClientID character 
#'
#' @field secret APISecret character 
#'
#' @field application_id ApplicationID character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ApplicationGetRequest <- R6::R6Class(
  'ApplicationGetRequest',
  public = list(
    `client_id` = NULL,
    `secret` = NULL,
    `application_id` = NULL,
    initialize = function(
        `client_id`, `secret`, `application_id`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`client_id`)) {
        stopifnot(is.character(`client_id`), length(`client_id`) == 1)
        self$`client_id` <- `client_id`
      }
      if (!missing(`secret`)) {
        stopifnot(is.character(`secret`), length(`secret`) == 1)
        self$`secret` <- `secret`
      }
      if (!missing(`application_id`)) {
        stopifnot(is.character(`application_id`), length(`application_id`) == 1)
        self$`application_id` <- `application_id`
      }
    },
    toJSON = function() {
      ApplicationGetRequestObject <- list()
      if (!is.null(self$`client_id`)) {
        ApplicationGetRequestObject[['client_id']] <-
          self$`client_id`
      }
      if (!is.null(self$`secret`)) {
        ApplicationGetRequestObject[['secret']] <-
          self$`secret`
      }
      if (!is.null(self$`application_id`)) {
        ApplicationGetRequestObject[['application_id']] <-
          self$`application_id`
      }

      ApplicationGetRequestObject
    },
    fromJSON = function(ApplicationGetRequestJson) {
      ApplicationGetRequestObject <- jsonlite::fromJSON(ApplicationGetRequestJson)
      if (!is.null(ApplicationGetRequestObject$`client_id`)) {
        self$`client_id` <- ApplicationGetRequestObject$`client_id`
      }
      if (!is.null(ApplicationGetRequestObject$`secret`)) {
        self$`secret` <- ApplicationGetRequestObject$`secret`
      }
      if (!is.null(ApplicationGetRequestObject$`application_id`)) {
        self$`application_id` <- ApplicationGetRequestObject$`application_id`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`client_id`)) {
        sprintf(
        '"client_id":
          "%s"
                ',
        self$`client_id`
        )},
        if (!is.null(self$`secret`)) {
        sprintf(
        '"secret":
          "%s"
                ',
        self$`secret`
        )},
        if (!is.null(self$`application_id`)) {
        sprintf(
        '"application_id":
          "%s"
                ',
        self$`application_id`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ApplicationGetRequestJson) {
      ApplicationGetRequestObject <- jsonlite::fromJSON(ApplicationGetRequestJson)
      self$`client_id` <- ApplicationGetRequestObject$`client_id`
      self$`secret` <- ApplicationGetRequestObject$`secret`
      self$`application_id` <- ApplicationGetRequestObject$`application_id`
      self
    }
  )
)
