# The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.146.0
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title AssetReportFilterResponse
#'
#' @description AssetReportFilterResponse Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field asset_report_token AssetReportToken character 
#'
#' @field asset_report_id AssetReportId character 
#'
#' @field request_id RequestID character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
AssetReportFilterResponse <- R6::R6Class(
  'AssetReportFilterResponse',
  public = list(
    `asset_report_token` = NULL,
    `asset_report_id` = NULL,
    `request_id` = NULL,
    initialize = function(
        `asset_report_token`, `asset_report_id`, `request_id`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`asset_report_token`)) {
        stopifnot(is.character(`asset_report_token`), length(`asset_report_token`) == 1)
        self$`asset_report_token` <- `asset_report_token`
      }
      if (!missing(`asset_report_id`)) {
        stopifnot(is.character(`asset_report_id`), length(`asset_report_id`) == 1)
        self$`asset_report_id` <- `asset_report_id`
      }
      if (!missing(`request_id`)) {
        stopifnot(is.character(`request_id`), length(`request_id`) == 1)
        self$`request_id` <- `request_id`
      }
    },
    toJSON = function() {
      AssetReportFilterResponseObject <- list()
      if (!is.null(self$`asset_report_token`)) {
        AssetReportFilterResponseObject[['asset_report_token']] <-
          self$`asset_report_token`
      }
      if (!is.null(self$`asset_report_id`)) {
        AssetReportFilterResponseObject[['asset_report_id']] <-
          self$`asset_report_id`
      }
      if (!is.null(self$`request_id`)) {
        AssetReportFilterResponseObject[['request_id']] <-
          self$`request_id`
      }

      AssetReportFilterResponseObject
    },
    fromJSON = function(AssetReportFilterResponseJson) {
      AssetReportFilterResponseObject <- jsonlite::fromJSON(AssetReportFilterResponseJson)
      if (!is.null(AssetReportFilterResponseObject$`asset_report_token`)) {
        self$`asset_report_token` <- AssetReportFilterResponseObject$`asset_report_token`
      }
      if (!is.null(AssetReportFilterResponseObject$`asset_report_id`)) {
        self$`asset_report_id` <- AssetReportFilterResponseObject$`asset_report_id`
      }
      if (!is.null(AssetReportFilterResponseObject$`request_id`)) {
        self$`request_id` <- AssetReportFilterResponseObject$`request_id`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`asset_report_token`)) {
        sprintf(
        '"asset_report_token":
          "%s"
                ',
        self$`asset_report_token`
        )},
        if (!is.null(self$`asset_report_id`)) {
        sprintf(
        '"asset_report_id":
          "%s"
                ',
        self$`asset_report_id`
        )},
        if (!is.null(self$`request_id`)) {
        sprintf(
        '"request_id":
          "%s"
                ',
        self$`request_id`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(AssetReportFilterResponseJson) {
      AssetReportFilterResponseObject <- jsonlite::fromJSON(AssetReportFilterResponseJson)
      self$`asset_report_token` <- AssetReportFilterResponseObject$`asset_report_token`
      self$`asset_report_id` <- AssetReportFilterResponseObject$`asset_report_id`
      self$`request_id` <- AssetReportFilterResponseObject$`request_id`
      self
    }
  )
)
