# The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.146.0
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title AssetReportCreateRequestOptions
#'
#' @description AssetReportCreateRequestOptions Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field client_report_id  character [optional]
#'
#' @field webhook  character [optional]
#'
#' @field include_fast_report  character [optional]
#'
#' @field products  list( character ) [optional]
#'
#' @field user  \link{AssetReportUser} [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
AssetReportCreateRequestOptions <- R6::R6Class(
  'AssetReportCreateRequestOptions',
  public = list(
    `client_report_id` = NULL,
    `webhook` = NULL,
    `include_fast_report` = NULL,
    `products` = NULL,
    `user` = NULL,
    initialize = function(
        `client_report_id`=NULL, `webhook`=NULL, `include_fast_report`=NULL, `products`=NULL, `user`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`client_report_id`)) {
        stopifnot(is.character(`client_report_id`), length(`client_report_id`) == 1)
        self$`client_report_id` <- `client_report_id`
      }
      if (!is.null(`webhook`)) {
        stopifnot(is.character(`webhook`), length(`webhook`) == 1)
        self$`webhook` <- `webhook`
      }
      if (!is.null(`include_fast_report`)) {
        stopifnot(is.logical(`include_fast_report`), length(`include_fast_report`) == 1)
        self$`include_fast_report` <- `include_fast_report`
      }
      if (!is.null(`products`)) {
        stopifnot(is.vector(`products`), length(`products`) != 0)
        sapply(`products`, function(x) stopifnot(is.character(x)))
        self$`products` <- `products`
      }
      if (!is.null(`user`)) {
        stopifnot(R6::is.R6(`user`))
        self$`user` <- `user`
      }
    },
    toJSON = function() {
      AssetReportCreateRequestOptionsObject <- list()
      if (!is.null(self$`client_report_id`)) {
        AssetReportCreateRequestOptionsObject[['client_report_id']] <-
          self$`client_report_id`
      }
      if (!is.null(self$`webhook`)) {
        AssetReportCreateRequestOptionsObject[['webhook']] <-
          self$`webhook`
      }
      if (!is.null(self$`include_fast_report`)) {
        AssetReportCreateRequestOptionsObject[['include_fast_report']] <-
          self$`include_fast_report`
      }
      if (!is.null(self$`products`)) {
        AssetReportCreateRequestOptionsObject[['products']] <-
          self$`products`
      }
      if (!is.null(self$`user`)) {
        AssetReportCreateRequestOptionsObject[['user']] <-
          self$`user`$toJSON()
      }

      AssetReportCreateRequestOptionsObject
    },
    fromJSON = function(AssetReportCreateRequestOptionsJson) {
      AssetReportCreateRequestOptionsObject <- jsonlite::fromJSON(AssetReportCreateRequestOptionsJson)
      if (!is.null(AssetReportCreateRequestOptionsObject$`client_report_id`)) {
        self$`client_report_id` <- AssetReportCreateRequestOptionsObject$`client_report_id`
      }
      if (!is.null(AssetReportCreateRequestOptionsObject$`webhook`)) {
        self$`webhook` <- AssetReportCreateRequestOptionsObject$`webhook`
      }
      if (!is.null(AssetReportCreateRequestOptionsObject$`include_fast_report`)) {
        self$`include_fast_report` <- AssetReportCreateRequestOptionsObject$`include_fast_report`
      }
      if (!is.null(AssetReportCreateRequestOptionsObject$`products`)) {
        self$`products` <- ApiClient$new()$deserializeObj(AssetReportCreateRequestOptionsObject$`products`, "array[character]", loadNamespace("plaidr"))
      }
      if (!is.null(AssetReportCreateRequestOptionsObject$`user`)) {
        userObject <- AssetReportUser$new()
        userObject$fromJSON(jsonlite::toJSON(AssetReportCreateRequestOptionsObject$user, auto_unbox = TRUE, digits = NA))
        self$`user` <- userObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`client_report_id`)) {
        sprintf(
        '"client_report_id":
          "%s"
                ',
        self$`client_report_id`
        )},
        if (!is.null(self$`webhook`)) {
        sprintf(
        '"webhook":
          "%s"
                ',
        self$`webhook`
        )},
        if (!is.null(self$`include_fast_report`)) {
        sprintf(
        '"include_fast_report":
          %s
                ',
        tolower(self$`include_fast_report`)
        )},
        if (!is.null(self$`products`)) {
        sprintf(
        '"products":
           [%s]
        ',
        paste(unlist(lapply(self$`products`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`user`)) {
        sprintf(
        '"user":
        %s
        ',
        jsonlite::toJSON(self$`user`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(AssetReportCreateRequestOptionsJson) {
      AssetReportCreateRequestOptionsObject <- jsonlite::fromJSON(AssetReportCreateRequestOptionsJson)
      self$`client_report_id` <- AssetReportCreateRequestOptionsObject$`client_report_id`
      self$`webhook` <- AssetReportCreateRequestOptionsObject$`webhook`
      self$`include_fast_report` <- AssetReportCreateRequestOptionsObject$`include_fast_report`
      self$`products` <- ApiClient$new()$deserializeObj(AssetReportCreateRequestOptionsObject$`products`, "array[character]", loadNamespace("plaidr"))
      self$`user` <- AssetReportUser$new()$fromJSON(jsonlite::toJSON(AssetReportCreateRequestOptionsObject$user, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)
