# The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.146.0
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title AssetReportPDFGetRequest
#'
#' @description AssetReportPDFGetRequest Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field client_id ClientID character [optional]
#'
#' @field secret APISecret character [optional]
#'
#' @field asset_report_token AssetReportToken character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
AssetReportPDFGetRequest <- R6::R6Class(
  'AssetReportPDFGetRequest',
  public = list(
    `client_id` = NULL,
    `secret` = NULL,
    `asset_report_token` = NULL,
    initialize = function(
        `asset_report_token`, `client_id`=NULL, `secret`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`asset_report_token`)) {
        stopifnot(is.character(`asset_report_token`), length(`asset_report_token`) == 1)
        self$`asset_report_token` <- `asset_report_token`
      }
      if (!is.null(`client_id`)) {
        stopifnot(is.character(`client_id`), length(`client_id`) == 1)
        self$`client_id` <- `client_id`
      }
      if (!is.null(`secret`)) {
        stopifnot(is.character(`secret`), length(`secret`) == 1)
        self$`secret` <- `secret`
      }
    },
    toJSON = function() {
      AssetReportPDFGetRequestObject <- list()
      if (!is.null(self$`client_id`)) {
        AssetReportPDFGetRequestObject[['client_id']] <-
          self$`client_id`
      }
      if (!is.null(self$`secret`)) {
        AssetReportPDFGetRequestObject[['secret']] <-
          self$`secret`
      }
      if (!is.null(self$`asset_report_token`)) {
        AssetReportPDFGetRequestObject[['asset_report_token']] <-
          self$`asset_report_token`
      }

      AssetReportPDFGetRequestObject
    },
    fromJSON = function(AssetReportPDFGetRequestJson) {
      AssetReportPDFGetRequestObject <- jsonlite::fromJSON(AssetReportPDFGetRequestJson)
      if (!is.null(AssetReportPDFGetRequestObject$`client_id`)) {
        self$`client_id` <- AssetReportPDFGetRequestObject$`client_id`
      }
      if (!is.null(AssetReportPDFGetRequestObject$`secret`)) {
        self$`secret` <- AssetReportPDFGetRequestObject$`secret`
      }
      if (!is.null(AssetReportPDFGetRequestObject$`asset_report_token`)) {
        self$`asset_report_token` <- AssetReportPDFGetRequestObject$`asset_report_token`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`client_id`)) {
        sprintf(
        '"client_id":
          "%s"
                ',
        self$`client_id`
        )},
        if (!is.null(self$`secret`)) {
        sprintf(
        '"secret":
          "%s"
                ',
        self$`secret`
        )},
        if (!is.null(self$`asset_report_token`)) {
        sprintf(
        '"asset_report_token":
          "%s"
                ',
        self$`asset_report_token`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(AssetReportPDFGetRequestJson) {
      AssetReportPDFGetRequestObject <- jsonlite::fromJSON(AssetReportPDFGetRequestJson)
      self$`client_id` <- AssetReportPDFGetRequestObject$`client_id`
      self$`secret` <- AssetReportPDFGetRequestObject$`secret`
      self$`asset_report_token` <- AssetReportPDFGetRequestObject$`asset_report_token`
      self
    }
  )
)
