# The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.146.0
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title AssetReportRelayRemoveResponse
#'
#' @description AssetReportRelayRemoveResponse Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field removed  character 
#'
#' @field request_id RequestID character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
AssetReportRelayRemoveResponse <- R6::R6Class(
  'AssetReportRelayRemoveResponse',
  public = list(
    `removed` = NULL,
    `request_id` = NULL,
    initialize = function(
        `removed`, `request_id`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`removed`)) {
        stopifnot(is.logical(`removed`), length(`removed`) == 1)
        self$`removed` <- `removed`
      }
      if (!missing(`request_id`)) {
        stopifnot(is.character(`request_id`), length(`request_id`) == 1)
        self$`request_id` <- `request_id`
      }
    },
    toJSON = function() {
      AssetReportRelayRemoveResponseObject <- list()
      if (!is.null(self$`removed`)) {
        AssetReportRelayRemoveResponseObject[['removed']] <-
          self$`removed`
      }
      if (!is.null(self$`request_id`)) {
        AssetReportRelayRemoveResponseObject[['request_id']] <-
          self$`request_id`
      }

      AssetReportRelayRemoveResponseObject
    },
    fromJSON = function(AssetReportRelayRemoveResponseJson) {
      AssetReportRelayRemoveResponseObject <- jsonlite::fromJSON(AssetReportRelayRemoveResponseJson)
      if (!is.null(AssetReportRelayRemoveResponseObject$`removed`)) {
        self$`removed` <- AssetReportRelayRemoveResponseObject$`removed`
      }
      if (!is.null(AssetReportRelayRemoveResponseObject$`request_id`)) {
        self$`request_id` <- AssetReportRelayRemoveResponseObject$`request_id`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`removed`)) {
        sprintf(
        '"removed":
          %s
                ',
        tolower(self$`removed`)
        )},
        if (!is.null(self$`request_id`)) {
        sprintf(
        '"request_id":
          "%s"
                ',
        self$`request_id`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(AssetReportRelayRemoveResponseJson) {
      AssetReportRelayRemoveResponseObject <- jsonlite::fromJSON(AssetReportRelayRemoveResponseJson)
      self$`removed` <- AssetReportRelayRemoveResponseObject$`removed`
      self$`request_id` <- AssetReportRelayRemoveResponseObject$`request_id`
      self
    }
  )
)
