# The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.146.0
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title AssetReportRelayCreateResponse
#'
#' @description AssetReportRelayCreateResponse Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field asset_relay_token  character 
#'
#' @field request_id RequestID character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
AssetReportRelayCreateResponse <- R6::R6Class(
  'AssetReportRelayCreateResponse',
  public = list(
    `asset_relay_token` = NULL,
    `request_id` = NULL,
    initialize = function(
        `asset_relay_token`, `request_id`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`asset_relay_token`)) {
        stopifnot(is.character(`asset_relay_token`), length(`asset_relay_token`) == 1)
        self$`asset_relay_token` <- `asset_relay_token`
      }
      if (!missing(`request_id`)) {
        stopifnot(is.character(`request_id`), length(`request_id`) == 1)
        self$`request_id` <- `request_id`
      }
    },
    toJSON = function() {
      AssetReportRelayCreateResponseObject <- list()
      if (!is.null(self$`asset_relay_token`)) {
        AssetReportRelayCreateResponseObject[['asset_relay_token']] <-
          self$`asset_relay_token`
      }
      if (!is.null(self$`request_id`)) {
        AssetReportRelayCreateResponseObject[['request_id']] <-
          self$`request_id`
      }

      AssetReportRelayCreateResponseObject
    },
    fromJSON = function(AssetReportRelayCreateResponseJson) {
      AssetReportRelayCreateResponseObject <- jsonlite::fromJSON(AssetReportRelayCreateResponseJson)
      if (!is.null(AssetReportRelayCreateResponseObject$`asset_relay_token`)) {
        self$`asset_relay_token` <- AssetReportRelayCreateResponseObject$`asset_relay_token`
      }
      if (!is.null(AssetReportRelayCreateResponseObject$`request_id`)) {
        self$`request_id` <- AssetReportRelayCreateResponseObject$`request_id`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`asset_relay_token`)) {
        sprintf(
        '"asset_relay_token":
          "%s"
                ',
        self$`asset_relay_token`
        )},
        if (!is.null(self$`request_id`)) {
        sprintf(
        '"request_id":
          "%s"
                ',
        self$`request_id`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(AssetReportRelayCreateResponseJson) {
      AssetReportRelayCreateResponseObject <- jsonlite::fromJSON(AssetReportRelayCreateResponseJson)
      self$`asset_relay_token` <- AssetReportRelayCreateResponseObject$`asset_relay_token`
      self$`request_id` <- AssetReportRelayCreateResponseObject$`request_id`
      self
    }
  )
)
