# The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.146.0
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title BankTransferCreateResponse
#'
#' @description BankTransferCreateResponse Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field bank_transfer  \link{BankTransfer} 
#'
#' @field request_id RequestID character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
BankTransferCreateResponse <- R6::R6Class(
  'BankTransferCreateResponse',
  public = list(
    `bank_transfer` = NULL,
    `request_id` = NULL,
    initialize = function(
        `bank_transfer`, `request_id`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`bank_transfer`)) {
        stopifnot(R6::is.R6(`bank_transfer`))
        self$`bank_transfer` <- `bank_transfer`
      }
      if (!missing(`request_id`)) {
        stopifnot(is.character(`request_id`), length(`request_id`) == 1)
        self$`request_id` <- `request_id`
      }
    },
    toJSON = function() {
      BankTransferCreateResponseObject <- list()
      if (!is.null(self$`bank_transfer`)) {
        BankTransferCreateResponseObject[['bank_transfer']] <-
          self$`bank_transfer`$toJSON()
      }
      if (!is.null(self$`request_id`)) {
        BankTransferCreateResponseObject[['request_id']] <-
          self$`request_id`
      }

      BankTransferCreateResponseObject
    },
    fromJSON = function(BankTransferCreateResponseJson) {
      BankTransferCreateResponseObject <- jsonlite::fromJSON(BankTransferCreateResponseJson)
      if (!is.null(BankTransferCreateResponseObject$`bank_transfer`)) {
        bank_transferObject <- BankTransfer$new()
        bank_transferObject$fromJSON(jsonlite::toJSON(BankTransferCreateResponseObject$bank_transfer, auto_unbox = TRUE, digits = NA))
        self$`bank_transfer` <- bank_transferObject
      }
      if (!is.null(BankTransferCreateResponseObject$`request_id`)) {
        self$`request_id` <- BankTransferCreateResponseObject$`request_id`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`bank_transfer`)) {
        sprintf(
        '"bank_transfer":
        %s
        ',
        jsonlite::toJSON(self$`bank_transfer`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`request_id`)) {
        sprintf(
        '"request_id":
          "%s"
                ',
        self$`request_id`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(BankTransferCreateResponseJson) {
      BankTransferCreateResponseObject <- jsonlite::fromJSON(BankTransferCreateResponseJson)
      self$`bank_transfer` <- BankTransfer$new()$fromJSON(jsonlite::toJSON(BankTransferCreateResponseObject$bank_transfer, auto_unbox = TRUE, digits = NA))
      self$`request_id` <- BankTransferCreateResponseObject$`request_id`
      self
    }
  )
)
