# The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.146.0
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title BankTransferEventSyncResponse
#'
#' @description BankTransferEventSyncResponse Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field bank_transfer_events  list( \link{BankTransferEvent} ) 
#'
#' @field request_id RequestID character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
BankTransferEventSyncResponse <- R6::R6Class(
  'BankTransferEventSyncResponse',
  public = list(
    `bank_transfer_events` = NULL,
    `request_id` = NULL,
    initialize = function(
        `bank_transfer_events`, `request_id`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`bank_transfer_events`)) {
        stopifnot(is.vector(`bank_transfer_events`), length(`bank_transfer_events`) != 0)
        sapply(`bank_transfer_events`, function(x) stopifnot(R6::is.R6(x)))
        self$`bank_transfer_events` <- `bank_transfer_events`
      }
      if (!missing(`request_id`)) {
        stopifnot(is.character(`request_id`), length(`request_id`) == 1)
        self$`request_id` <- `request_id`
      }
    },
    toJSON = function() {
      BankTransferEventSyncResponseObject <- list()
      if (!is.null(self$`bank_transfer_events`)) {
        BankTransferEventSyncResponseObject[['bank_transfer_events']] <-
          lapply(self$`bank_transfer_events`, function(x) x$toJSON())
      }
      if (!is.null(self$`request_id`)) {
        BankTransferEventSyncResponseObject[['request_id']] <-
          self$`request_id`
      }

      BankTransferEventSyncResponseObject
    },
    fromJSON = function(BankTransferEventSyncResponseJson) {
      BankTransferEventSyncResponseObject <- jsonlite::fromJSON(BankTransferEventSyncResponseJson)
      if (!is.null(BankTransferEventSyncResponseObject$`bank_transfer_events`)) {
        self$`bank_transfer_events` <- ApiClient$new()$deserializeObj(BankTransferEventSyncResponseObject$`bank_transfer_events`, "array[BankTransferEvent]", loadNamespace("plaidr"))
      }
      if (!is.null(BankTransferEventSyncResponseObject$`request_id`)) {
        self$`request_id` <- BankTransferEventSyncResponseObject$`request_id`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`bank_transfer_events`)) {
        sprintf(
        '"bank_transfer_events":
        [%s]
',
        paste(sapply(self$`bank_transfer_events`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`request_id`)) {
        sprintf(
        '"request_id":
          "%s"
                ',
        self$`request_id`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(BankTransferEventSyncResponseJson) {
      BankTransferEventSyncResponseObject <- jsonlite::fromJSON(BankTransferEventSyncResponseJson)
      self$`bank_transfer_events` <- ApiClient$new()$deserializeObj(BankTransferEventSyncResponseObject$`bank_transfer_events`, "array[BankTransferEvent]", loadNamespace("plaidr"))
      self$`request_id` <- BankTransferEventSyncResponseObject$`request_id`
      self
    }
  )
)
