# The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.146.0
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title BankTransferListRequest
#'
#' @description BankTransferListRequest Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field client_id ClientID character [optional]
#'
#' @field secret APISecret character [optional]
#'
#' @field start_date  character [optional]
#'
#' @field end_date  character [optional]
#'
#' @field count  integer [optional]
#'
#' @field offset  integer [optional]
#'
#' @field origination_account_id  character [optional]
#'
#' @field direction  \link{BankTransferDirection} [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
BankTransferListRequest <- R6::R6Class(
  'BankTransferListRequest',
  public = list(
    `client_id` = NULL,
    `secret` = NULL,
    `start_date` = NULL,
    `end_date` = NULL,
    `count` = NULL,
    `offset` = NULL,
    `origination_account_id` = NULL,
    `direction` = NULL,
    initialize = function(
        `client_id`=NULL, `secret`=NULL, `start_date`=NULL, `end_date`=NULL, `count`=25, `offset`=0, `origination_account_id`=NULL, `direction`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`client_id`)) {
        stopifnot(is.character(`client_id`), length(`client_id`) == 1)
        self$`client_id` <- `client_id`
      }
      if (!is.null(`secret`)) {
        stopifnot(is.character(`secret`), length(`secret`) == 1)
        self$`secret` <- `secret`
      }
      if (!is.null(`start_date`)) {
        stopifnot(is.character(`start_date`), length(`start_date`) == 1)
        self$`start_date` <- `start_date`
      }
      if (!is.null(`end_date`)) {
        stopifnot(is.character(`end_date`), length(`end_date`) == 1)
        self$`end_date` <- `end_date`
      }
      if (!is.null(`count`)) {
        stopifnot(is.numeric(`count`), length(`count`) == 1)
        self$`count` <- `count`
      }
      if (!is.null(`offset`)) {
        stopifnot(is.numeric(`offset`), length(`offset`) == 1)
        self$`offset` <- `offset`
      }
      if (!is.null(`origination_account_id`)) {
        stopifnot(is.character(`origination_account_id`), length(`origination_account_id`) == 1)
        self$`origination_account_id` <- `origination_account_id`
      }
      if (!is.null(`direction`)) {
        stopifnot(R6::is.R6(`direction`))
        self$`direction` <- `direction`
      }
    },
    toJSON = function() {
      BankTransferListRequestObject <- list()
      if (!is.null(self$`client_id`)) {
        BankTransferListRequestObject[['client_id']] <-
          self$`client_id`
      }
      if (!is.null(self$`secret`)) {
        BankTransferListRequestObject[['secret']] <-
          self$`secret`
      }
      if (!is.null(self$`start_date`)) {
        BankTransferListRequestObject[['start_date']] <-
          self$`start_date`
      }
      if (!is.null(self$`end_date`)) {
        BankTransferListRequestObject[['end_date']] <-
          self$`end_date`
      }
      if (!is.null(self$`count`)) {
        BankTransferListRequestObject[['count']] <-
          self$`count`
      }
      if (!is.null(self$`offset`)) {
        BankTransferListRequestObject[['offset']] <-
          self$`offset`
      }
      if (!is.null(self$`origination_account_id`)) {
        BankTransferListRequestObject[['origination_account_id']] <-
          self$`origination_account_id`
      }
      if (!is.null(self$`direction`)) {
        BankTransferListRequestObject[['direction']] <-
          self$`direction`$toJSON()
      }

      BankTransferListRequestObject
    },
    fromJSON = function(BankTransferListRequestJson) {
      BankTransferListRequestObject <- jsonlite::fromJSON(BankTransferListRequestJson)
      if (!is.null(BankTransferListRequestObject$`client_id`)) {
        self$`client_id` <- BankTransferListRequestObject$`client_id`
      }
      if (!is.null(BankTransferListRequestObject$`secret`)) {
        self$`secret` <- BankTransferListRequestObject$`secret`
      }
      if (!is.null(BankTransferListRequestObject$`start_date`)) {
        self$`start_date` <- BankTransferListRequestObject$`start_date`
      }
      if (!is.null(BankTransferListRequestObject$`end_date`)) {
        self$`end_date` <- BankTransferListRequestObject$`end_date`
      }
      if (!is.null(BankTransferListRequestObject$`count`)) {
        self$`count` <- BankTransferListRequestObject$`count`
      }
      if (!is.null(BankTransferListRequestObject$`offset`)) {
        self$`offset` <- BankTransferListRequestObject$`offset`
      }
      if (!is.null(BankTransferListRequestObject$`origination_account_id`)) {
        self$`origination_account_id` <- BankTransferListRequestObject$`origination_account_id`
      }
      if (!is.null(BankTransferListRequestObject$`direction`)) {
        directionObject <- BankTransferDirection$new()
        directionObject$fromJSON(jsonlite::toJSON(BankTransferListRequestObject$direction, auto_unbox = TRUE, digits = NA))
        self$`direction` <- directionObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`client_id`)) {
        sprintf(
        '"client_id":
          "%s"
                ',
        self$`client_id`
        )},
        if (!is.null(self$`secret`)) {
        sprintf(
        '"secret":
          "%s"
                ',
        self$`secret`
        )},
        if (!is.null(self$`start_date`)) {
        sprintf(
        '"start_date":
          "%s"
                ',
        self$`start_date`
        )},
        if (!is.null(self$`end_date`)) {
        sprintf(
        '"end_date":
          "%s"
                ',
        self$`end_date`
        )},
        if (!is.null(self$`count`)) {
        sprintf(
        '"count":
          %d
                ',
        self$`count`
        )},
        if (!is.null(self$`offset`)) {
        sprintf(
        '"offset":
          %d
                ',
        self$`offset`
        )},
        if (!is.null(self$`origination_account_id`)) {
        sprintf(
        '"origination_account_id":
          "%s"
                ',
        self$`origination_account_id`
        )},
        if (!is.null(self$`direction`)) {
        sprintf(
        '"direction":
        %s
        ',
        jsonlite::toJSON(self$`direction`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(BankTransferListRequestJson) {
      BankTransferListRequestObject <- jsonlite::fromJSON(BankTransferListRequestJson)
      self$`client_id` <- BankTransferListRequestObject$`client_id`
      self$`secret` <- BankTransferListRequestObject$`secret`
      self$`start_date` <- BankTransferListRequestObject$`start_date`
      self$`end_date` <- BankTransferListRequestObject$`end_date`
      self$`count` <- BankTransferListRequestObject$`count`
      self$`offset` <- BankTransferListRequestObject$`offset`
      self$`origination_account_id` <- BankTransferListRequestObject$`origination_account_id`
      self$`direction` <- BankTransferDirection$new()$fromJSON(jsonlite::toJSON(BankTransferListRequestObject$direction, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)
