# The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.146.0
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ClientProvidedEnhancedTransaction
#'
#' @description ClientProvidedEnhancedTransaction Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field id  character 
#'
#' @field description  character 
#'
#' @field amount  numeric 
#'
#' @field iso_currency_code  character 
#'
#' @field enhancements  \link{Enhancements} 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ClientProvidedEnhancedTransaction <- R6::R6Class(
  'ClientProvidedEnhancedTransaction',
  public = list(
    `id` = NULL,
    `description` = NULL,
    `amount` = NULL,
    `iso_currency_code` = NULL,
    `enhancements` = NULL,
    initialize = function(
        `id`, `description`, `amount`, `iso_currency_code`, `enhancements`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!missing(`amount`)) {
        stopifnot(is.numeric(`amount`), length(`amount`) == 1)
        self$`amount` <- `amount`
      }
      if (!missing(`iso_currency_code`)) {
        stopifnot(is.character(`iso_currency_code`), length(`iso_currency_code`) == 1)
        self$`iso_currency_code` <- `iso_currency_code`
      }
      if (!missing(`enhancements`)) {
        stopifnot(R6::is.R6(`enhancements`))
        self$`enhancements` <- `enhancements`
      }
    },
    toJSON = function() {
      ClientProvidedEnhancedTransactionObject <- list()
      if (!is.null(self$`id`)) {
        ClientProvidedEnhancedTransactionObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`description`)) {
        ClientProvidedEnhancedTransactionObject[['description']] <-
          self$`description`
      }
      if (!is.null(self$`amount`)) {
        ClientProvidedEnhancedTransactionObject[['amount']] <-
          self$`amount`
      }
      if (!is.null(self$`iso_currency_code`)) {
        ClientProvidedEnhancedTransactionObject[['iso_currency_code']] <-
          self$`iso_currency_code`
      }
      if (!is.null(self$`enhancements`)) {
        ClientProvidedEnhancedTransactionObject[['enhancements']] <-
          self$`enhancements`$toJSON()
      }

      ClientProvidedEnhancedTransactionObject
    },
    fromJSON = function(ClientProvidedEnhancedTransactionJson) {
      ClientProvidedEnhancedTransactionObject <- jsonlite::fromJSON(ClientProvidedEnhancedTransactionJson)
      if (!is.null(ClientProvidedEnhancedTransactionObject$`id`)) {
        self$`id` <- ClientProvidedEnhancedTransactionObject$`id`
      }
      if (!is.null(ClientProvidedEnhancedTransactionObject$`description`)) {
        self$`description` <- ClientProvidedEnhancedTransactionObject$`description`
      }
      if (!is.null(ClientProvidedEnhancedTransactionObject$`amount`)) {
        self$`amount` <- ClientProvidedEnhancedTransactionObject$`amount`
      }
      if (!is.null(ClientProvidedEnhancedTransactionObject$`iso_currency_code`)) {
        self$`iso_currency_code` <- ClientProvidedEnhancedTransactionObject$`iso_currency_code`
      }
      if (!is.null(ClientProvidedEnhancedTransactionObject$`enhancements`)) {
        enhancementsObject <- Enhancements$new()
        enhancementsObject$fromJSON(jsonlite::toJSON(ClientProvidedEnhancedTransactionObject$enhancements, auto_unbox = TRUE, digits = NA))
        self$`enhancements` <- enhancementsObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          "%s"
                ',
        self$`id`
        )},
        if (!is.null(self$`description`)) {
        sprintf(
        '"description":
          "%s"
                ',
        self$`description`
        )},
        if (!is.null(self$`amount`)) {
        sprintf(
        '"amount":
          %d
                ',
        self$`amount`
        )},
        if (!is.null(self$`iso_currency_code`)) {
        sprintf(
        '"iso_currency_code":
          "%s"
                ',
        self$`iso_currency_code`
        )},
        if (!is.null(self$`enhancements`)) {
        sprintf(
        '"enhancements":
        %s
        ',
        jsonlite::toJSON(self$`enhancements`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ClientProvidedEnhancedTransactionJson) {
      ClientProvidedEnhancedTransactionObject <- jsonlite::fromJSON(ClientProvidedEnhancedTransactionJson)
      self$`id` <- ClientProvidedEnhancedTransactionObject$`id`
      self$`description` <- ClientProvidedEnhancedTransactionObject$`description`
      self$`amount` <- ClientProvidedEnhancedTransactionObject$`amount`
      self$`iso_currency_code` <- ClientProvidedEnhancedTransactionObject$`iso_currency_code`
      self$`enhancements` <- Enhancements$new()$fromJSON(jsonlite::toJSON(ClientProvidedEnhancedTransactionObject$enhancements, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)
