# The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.146.0
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title CreditPayrollIncomeRefreshRequest
#'
#' @description CreditPayrollIncomeRefreshRequest Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field client_id ClientID character [optional]
#'
#' @field secret APISecret character [optional]
#'
#' @field user_token UserToken character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
CreditPayrollIncomeRefreshRequest <- R6::R6Class(
  'CreditPayrollIncomeRefreshRequest',
  public = list(
    `client_id` = NULL,
    `secret` = NULL,
    `user_token` = NULL,
    initialize = function(
        `client_id`=NULL, `secret`=NULL, `user_token`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`client_id`)) {
        stopifnot(is.character(`client_id`), length(`client_id`) == 1)
        self$`client_id` <- `client_id`
      }
      if (!is.null(`secret`)) {
        stopifnot(is.character(`secret`), length(`secret`) == 1)
        self$`secret` <- `secret`
      }
      if (!is.null(`user_token`)) {
        stopifnot(is.character(`user_token`), length(`user_token`) == 1)
        self$`user_token` <- `user_token`
      }
    },
    toJSON = function() {
      CreditPayrollIncomeRefreshRequestObject <- list()
      if (!is.null(self$`client_id`)) {
        CreditPayrollIncomeRefreshRequestObject[['client_id']] <-
          self$`client_id`
      }
      if (!is.null(self$`secret`)) {
        CreditPayrollIncomeRefreshRequestObject[['secret']] <-
          self$`secret`
      }
      if (!is.null(self$`user_token`)) {
        CreditPayrollIncomeRefreshRequestObject[['user_token']] <-
          self$`user_token`
      }

      CreditPayrollIncomeRefreshRequestObject
    },
    fromJSON = function(CreditPayrollIncomeRefreshRequestJson) {
      CreditPayrollIncomeRefreshRequestObject <- jsonlite::fromJSON(CreditPayrollIncomeRefreshRequestJson)
      if (!is.null(CreditPayrollIncomeRefreshRequestObject$`client_id`)) {
        self$`client_id` <- CreditPayrollIncomeRefreshRequestObject$`client_id`
      }
      if (!is.null(CreditPayrollIncomeRefreshRequestObject$`secret`)) {
        self$`secret` <- CreditPayrollIncomeRefreshRequestObject$`secret`
      }
      if (!is.null(CreditPayrollIncomeRefreshRequestObject$`user_token`)) {
        self$`user_token` <- CreditPayrollIncomeRefreshRequestObject$`user_token`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`client_id`)) {
        sprintf(
        '"client_id":
          "%s"
                ',
        self$`client_id`
        )},
        if (!is.null(self$`secret`)) {
        sprintf(
        '"secret":
          "%s"
                ',
        self$`secret`
        )},
        if (!is.null(self$`user_token`)) {
        sprintf(
        '"user_token":
          "%s"
                ',
        self$`user_token`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(CreditPayrollIncomeRefreshRequestJson) {
      CreditPayrollIncomeRefreshRequestObject <- jsonlite::fromJSON(CreditPayrollIncomeRefreshRequestJson)
      self$`client_id` <- CreditPayrollIncomeRefreshRequestObject$`client_id`
      self$`secret` <- CreditPayrollIncomeRefreshRequestObject$`secret`
      self$`user_token` <- CreditPayrollIncomeRefreshRequestObject$`user_token`
      self
    }
  )
)
