# The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.146.0
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title CreditBankIncomeItem
#'
#' @description CreditBankIncomeItem Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field bank_income_accounts  list( \link{CreditBankIncomeAccount} ) [optional]
#'
#' @field bank_income_sources  list( \link{CreditBankIncomeSource} ) [optional]
#'
#' @field last_updated_time  character [optional]
#'
#' @field institution_id  character [optional]
#'
#' @field institution_name  character [optional]
#'
#' @field item_id  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
CreditBankIncomeItem <- R6::R6Class(
  'CreditBankIncomeItem',
  public = list(
    `bank_income_accounts` = NULL,
    `bank_income_sources` = NULL,
    `last_updated_time` = NULL,
    `institution_id` = NULL,
    `institution_name` = NULL,
    `item_id` = NULL,
    initialize = function(
        `bank_income_accounts`=NULL, `bank_income_sources`=NULL, `last_updated_time`=NULL, `institution_id`=NULL, `institution_name`=NULL, `item_id`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`bank_income_accounts`)) {
        stopifnot(is.vector(`bank_income_accounts`), length(`bank_income_accounts`) != 0)
        sapply(`bank_income_accounts`, function(x) stopifnot(R6::is.R6(x)))
        self$`bank_income_accounts` <- `bank_income_accounts`
      }
      if (!is.null(`bank_income_sources`)) {
        stopifnot(is.vector(`bank_income_sources`), length(`bank_income_sources`) != 0)
        sapply(`bank_income_sources`, function(x) stopifnot(R6::is.R6(x)))
        self$`bank_income_sources` <- `bank_income_sources`
      }
      if (!is.null(`last_updated_time`)) {
        stopifnot(is.character(`last_updated_time`), length(`last_updated_time`) == 1)
        self$`last_updated_time` <- `last_updated_time`
      }
      if (!is.null(`institution_id`)) {
        stopifnot(is.character(`institution_id`), length(`institution_id`) == 1)
        self$`institution_id` <- `institution_id`
      }
      if (!is.null(`institution_name`)) {
        stopifnot(is.character(`institution_name`), length(`institution_name`) == 1)
        self$`institution_name` <- `institution_name`
      }
      if (!is.null(`item_id`)) {
        stopifnot(is.character(`item_id`), length(`item_id`) == 1)
        self$`item_id` <- `item_id`
      }
    },
    toJSON = function() {
      CreditBankIncomeItemObject <- list()
      if (!is.null(self$`bank_income_accounts`)) {
        CreditBankIncomeItemObject[['bank_income_accounts']] <-
          lapply(self$`bank_income_accounts`, function(x) x$toJSON())
      }
      if (!is.null(self$`bank_income_sources`)) {
        CreditBankIncomeItemObject[['bank_income_sources']] <-
          lapply(self$`bank_income_sources`, function(x) x$toJSON())
      }
      if (!is.null(self$`last_updated_time`)) {
        CreditBankIncomeItemObject[['last_updated_time']] <-
          self$`last_updated_time`
      }
      if (!is.null(self$`institution_id`)) {
        CreditBankIncomeItemObject[['institution_id']] <-
          self$`institution_id`
      }
      if (!is.null(self$`institution_name`)) {
        CreditBankIncomeItemObject[['institution_name']] <-
          self$`institution_name`
      }
      if (!is.null(self$`item_id`)) {
        CreditBankIncomeItemObject[['item_id']] <-
          self$`item_id`
      }

      CreditBankIncomeItemObject
    },
    fromJSON = function(CreditBankIncomeItemJson) {
      CreditBankIncomeItemObject <- jsonlite::fromJSON(CreditBankIncomeItemJson)
      if (!is.null(CreditBankIncomeItemObject$`bank_income_accounts`)) {
        self$`bank_income_accounts` <- ApiClient$new()$deserializeObj(CreditBankIncomeItemObject$`bank_income_accounts`, "array[CreditBankIncomeAccount]", loadNamespace("plaidr"))
      }
      if (!is.null(CreditBankIncomeItemObject$`bank_income_sources`)) {
        self$`bank_income_sources` <- ApiClient$new()$deserializeObj(CreditBankIncomeItemObject$`bank_income_sources`, "array[CreditBankIncomeSource]", loadNamespace("plaidr"))
      }
      if (!is.null(CreditBankIncomeItemObject$`last_updated_time`)) {
        self$`last_updated_time` <- CreditBankIncomeItemObject$`last_updated_time`
      }
      if (!is.null(CreditBankIncomeItemObject$`institution_id`)) {
        self$`institution_id` <- CreditBankIncomeItemObject$`institution_id`
      }
      if (!is.null(CreditBankIncomeItemObject$`institution_name`)) {
        self$`institution_name` <- CreditBankIncomeItemObject$`institution_name`
      }
      if (!is.null(CreditBankIncomeItemObject$`item_id`)) {
        self$`item_id` <- CreditBankIncomeItemObject$`item_id`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`bank_income_accounts`)) {
        sprintf(
        '"bank_income_accounts":
        [%s]
',
        paste(sapply(self$`bank_income_accounts`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`bank_income_sources`)) {
        sprintf(
        '"bank_income_sources":
        [%s]
',
        paste(sapply(self$`bank_income_sources`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`last_updated_time`)) {
        sprintf(
        '"last_updated_time":
          "%s"
                ',
        self$`last_updated_time`
        )},
        if (!is.null(self$`institution_id`)) {
        sprintf(
        '"institution_id":
          "%s"
                ',
        self$`institution_id`
        )},
        if (!is.null(self$`institution_name`)) {
        sprintf(
        '"institution_name":
          "%s"
                ',
        self$`institution_name`
        )},
        if (!is.null(self$`item_id`)) {
        sprintf(
        '"item_id":
          "%s"
                ',
        self$`item_id`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(CreditBankIncomeItemJson) {
      CreditBankIncomeItemObject <- jsonlite::fromJSON(CreditBankIncomeItemJson)
      self$`bank_income_accounts` <- ApiClient$new()$deserializeObj(CreditBankIncomeItemObject$`bank_income_accounts`, "array[CreditBankIncomeAccount]", loadNamespace("plaidr"))
      self$`bank_income_sources` <- ApiClient$new()$deserializeObj(CreditBankIncomeItemObject$`bank_income_sources`, "array[CreditBankIncomeSource]", loadNamespace("plaidr"))
      self$`last_updated_time` <- CreditBankIncomeItemObject$`last_updated_time`
      self$`institution_id` <- CreditBankIncomeItemObject$`institution_id`
      self$`institution_name` <- CreditBankIncomeItemObject$`institution_name`
      self$`item_id` <- CreditBankIncomeItemObject$`item_id`
      self
    }
  )
)
