# The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.146.0
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title CreditBankIncomeRefreshRequest
#'
#' @description CreditBankIncomeRefreshRequest Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field client_id ClientID character 
#'
#' @field secret APISecret character 
#'
#' @field user_token UserToken character 
#'
#' @field options  \link{CreditBankIncomeRefreshRequestOptions} [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
CreditBankIncomeRefreshRequest <- R6::R6Class(
  'CreditBankIncomeRefreshRequest',
  public = list(
    `client_id` = NULL,
    `secret` = NULL,
    `user_token` = NULL,
    `options` = NULL,
    initialize = function(
        `client_id`, `secret`, `user_token`, `options`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`client_id`)) {
        stopifnot(is.character(`client_id`), length(`client_id`) == 1)
        self$`client_id` <- `client_id`
      }
      if (!missing(`secret`)) {
        stopifnot(is.character(`secret`), length(`secret`) == 1)
        self$`secret` <- `secret`
      }
      if (!missing(`user_token`)) {
        stopifnot(is.character(`user_token`), length(`user_token`) == 1)
        self$`user_token` <- `user_token`
      }
      if (!is.null(`options`)) {
        stopifnot(R6::is.R6(`options`))
        self$`options` <- `options`
      }
    },
    toJSON = function() {
      CreditBankIncomeRefreshRequestObject <- list()
      if (!is.null(self$`client_id`)) {
        CreditBankIncomeRefreshRequestObject[['client_id']] <-
          self$`client_id`
      }
      if (!is.null(self$`secret`)) {
        CreditBankIncomeRefreshRequestObject[['secret']] <-
          self$`secret`
      }
      if (!is.null(self$`user_token`)) {
        CreditBankIncomeRefreshRequestObject[['user_token']] <-
          self$`user_token`
      }
      if (!is.null(self$`options`)) {
        CreditBankIncomeRefreshRequestObject[['options']] <-
          self$`options`$toJSON()
      }

      CreditBankIncomeRefreshRequestObject
    },
    fromJSON = function(CreditBankIncomeRefreshRequestJson) {
      CreditBankIncomeRefreshRequestObject <- jsonlite::fromJSON(CreditBankIncomeRefreshRequestJson)
      if (!is.null(CreditBankIncomeRefreshRequestObject$`client_id`)) {
        self$`client_id` <- CreditBankIncomeRefreshRequestObject$`client_id`
      }
      if (!is.null(CreditBankIncomeRefreshRequestObject$`secret`)) {
        self$`secret` <- CreditBankIncomeRefreshRequestObject$`secret`
      }
      if (!is.null(CreditBankIncomeRefreshRequestObject$`user_token`)) {
        self$`user_token` <- CreditBankIncomeRefreshRequestObject$`user_token`
      }
      if (!is.null(CreditBankIncomeRefreshRequestObject$`options`)) {
        optionsObject <- CreditBankIncomeRefreshRequestOptions$new()
        optionsObject$fromJSON(jsonlite::toJSON(CreditBankIncomeRefreshRequestObject$options, auto_unbox = TRUE, digits = NA))
        self$`options` <- optionsObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`client_id`)) {
        sprintf(
        '"client_id":
          "%s"
                ',
        self$`client_id`
        )},
        if (!is.null(self$`secret`)) {
        sprintf(
        '"secret":
          "%s"
                ',
        self$`secret`
        )},
        if (!is.null(self$`user_token`)) {
        sprintf(
        '"user_token":
          "%s"
                ',
        self$`user_token`
        )},
        if (!is.null(self$`options`)) {
        sprintf(
        '"options":
        %s
        ',
        jsonlite::toJSON(self$`options`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(CreditBankIncomeRefreshRequestJson) {
      CreditBankIncomeRefreshRequestObject <- jsonlite::fromJSON(CreditBankIncomeRefreshRequestJson)
      self$`client_id` <- CreditBankIncomeRefreshRequestObject$`client_id`
      self$`secret` <- CreditBankIncomeRefreshRequestObject$`secret`
      self$`user_token` <- CreditBankIncomeRefreshRequestObject$`user_token`
      self$`options` <- CreditBankIncomeRefreshRequestOptions$new()$fromJSON(jsonlite::toJSON(CreditBankIncomeRefreshRequestObject$options, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)
