# The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.146.0
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title DepositSwitchGetResponse
#'
#' @description DepositSwitchGetResponse Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field deposit_switch_id  character 
#'
#' @field target_account_id  character 
#'
#' @field target_item_id  character 
#'
#' @field state  character 
#'
#' @field switch_method  character [optional]
#'
#' @field account_has_multiple_allocations  character 
#'
#' @field is_allocated_remainder  character 
#'
#' @field percent_allocated  numeric 
#'
#' @field amount_allocated  numeric 
#'
#' @field employer_name  character [optional]
#'
#' @field employer_id  character [optional]
#'
#' @field institution_name  character [optional]
#'
#' @field institution_id  character [optional]
#'
#' @field date_created  character 
#'
#' @field date_completed  character 
#'
#' @field request_id RequestID character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
DepositSwitchGetResponse <- R6::R6Class(
  'DepositSwitchGetResponse',
  public = list(
    `deposit_switch_id` = NULL,
    `target_account_id` = NULL,
    `target_item_id` = NULL,
    `state` = NULL,
    `switch_method` = NULL,
    `account_has_multiple_allocations` = NULL,
    `is_allocated_remainder` = NULL,
    `percent_allocated` = NULL,
    `amount_allocated` = NULL,
    `employer_name` = NULL,
    `employer_id` = NULL,
    `institution_name` = NULL,
    `institution_id` = NULL,
    `date_created` = NULL,
    `date_completed` = NULL,
    `request_id` = NULL,
    initialize = function(
        `deposit_switch_id`, `target_account_id`, `target_item_id`, `state`, `account_has_multiple_allocations`, `is_allocated_remainder`, `percent_allocated`, `amount_allocated`, `date_created`, `date_completed`, `request_id`, `switch_method`=NULL, `employer_name`=NULL, `employer_id`=NULL, `institution_name`=NULL, `institution_id`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`deposit_switch_id`)) {
        stopifnot(is.character(`deposit_switch_id`), length(`deposit_switch_id`) == 1)
        self$`deposit_switch_id` <- `deposit_switch_id`
      }
      if (!missing(`target_account_id`)) {
        stopifnot(is.character(`target_account_id`), length(`target_account_id`) == 1)
        self$`target_account_id` <- `target_account_id`
      }
      if (!missing(`target_item_id`)) {
        stopifnot(is.character(`target_item_id`), length(`target_item_id`) == 1)
        self$`target_item_id` <- `target_item_id`
      }
      if (!missing(`state`)) {
        stopifnot(is.character(`state`), length(`state`) == 1)
        self$`state` <- `state`
      }
      if (!missing(`account_has_multiple_allocations`)) {
        stopifnot(is.logical(`account_has_multiple_allocations`), length(`account_has_multiple_allocations`) == 1)
        self$`account_has_multiple_allocations` <- `account_has_multiple_allocations`
      }
      if (!missing(`is_allocated_remainder`)) {
        stopifnot(is.logical(`is_allocated_remainder`), length(`is_allocated_remainder`) == 1)
        self$`is_allocated_remainder` <- `is_allocated_remainder`
      }
      if (!missing(`percent_allocated`)) {
        stopifnot(is.numeric(`percent_allocated`), length(`percent_allocated`) == 1)
        self$`percent_allocated` <- `percent_allocated`
      }
      if (!missing(`amount_allocated`)) {
        stopifnot(is.numeric(`amount_allocated`), length(`amount_allocated`) == 1)
        self$`amount_allocated` <- `amount_allocated`
      }
      if (!missing(`date_created`)) {
        stopifnot(is.character(`date_created`), length(`date_created`) == 1)
        self$`date_created` <- `date_created`
      }
      if (!missing(`date_completed`)) {
        stopifnot(is.character(`date_completed`), length(`date_completed`) == 1)
        self$`date_completed` <- `date_completed`
      }
      if (!missing(`request_id`)) {
        stopifnot(is.character(`request_id`), length(`request_id`) == 1)
        self$`request_id` <- `request_id`
      }
      if (!is.null(`switch_method`)) {
        stopifnot(is.character(`switch_method`), length(`switch_method`) == 1)
        self$`switch_method` <- `switch_method`
      }
      if (!is.null(`employer_name`)) {
        stopifnot(is.character(`employer_name`), length(`employer_name`) == 1)
        self$`employer_name` <- `employer_name`
      }
      if (!is.null(`employer_id`)) {
        stopifnot(is.character(`employer_id`), length(`employer_id`) == 1)
        self$`employer_id` <- `employer_id`
      }
      if (!is.null(`institution_name`)) {
        stopifnot(is.character(`institution_name`), length(`institution_name`) == 1)
        self$`institution_name` <- `institution_name`
      }
      if (!is.null(`institution_id`)) {
        stopifnot(is.character(`institution_id`), length(`institution_id`) == 1)
        self$`institution_id` <- `institution_id`
      }
    },
    toJSON = function() {
      DepositSwitchGetResponseObject <- list()
      if (!is.null(self$`deposit_switch_id`)) {
        DepositSwitchGetResponseObject[['deposit_switch_id']] <-
          self$`deposit_switch_id`
      }
      if (!is.null(self$`target_account_id`)) {
        DepositSwitchGetResponseObject[['target_account_id']] <-
          self$`target_account_id`
      }
      if (!is.null(self$`target_item_id`)) {
        DepositSwitchGetResponseObject[['target_item_id']] <-
          self$`target_item_id`
      }
      if (!is.null(self$`state`)) {
        DepositSwitchGetResponseObject[['state']] <-
          self$`state`
      }
      if (!is.null(self$`switch_method`)) {
        DepositSwitchGetResponseObject[['switch_method']] <-
          self$`switch_method`
      }
      if (!is.null(self$`account_has_multiple_allocations`)) {
        DepositSwitchGetResponseObject[['account_has_multiple_allocations']] <-
          self$`account_has_multiple_allocations`
      }
      if (!is.null(self$`is_allocated_remainder`)) {
        DepositSwitchGetResponseObject[['is_allocated_remainder']] <-
          self$`is_allocated_remainder`
      }
      if (!is.null(self$`percent_allocated`)) {
        DepositSwitchGetResponseObject[['percent_allocated']] <-
          self$`percent_allocated`
      }
      if (!is.null(self$`amount_allocated`)) {
        DepositSwitchGetResponseObject[['amount_allocated']] <-
          self$`amount_allocated`
      }
      if (!is.null(self$`employer_name`)) {
        DepositSwitchGetResponseObject[['employer_name']] <-
          self$`employer_name`
      }
      if (!is.null(self$`employer_id`)) {
        DepositSwitchGetResponseObject[['employer_id']] <-
          self$`employer_id`
      }
      if (!is.null(self$`institution_name`)) {
        DepositSwitchGetResponseObject[['institution_name']] <-
          self$`institution_name`
      }
      if (!is.null(self$`institution_id`)) {
        DepositSwitchGetResponseObject[['institution_id']] <-
          self$`institution_id`
      }
      if (!is.null(self$`date_created`)) {
        DepositSwitchGetResponseObject[['date_created']] <-
          self$`date_created`
      }
      if (!is.null(self$`date_completed`)) {
        DepositSwitchGetResponseObject[['date_completed']] <-
          self$`date_completed`
      }
      if (!is.null(self$`request_id`)) {
        DepositSwitchGetResponseObject[['request_id']] <-
          self$`request_id`
      }

      DepositSwitchGetResponseObject
    },
    fromJSON = function(DepositSwitchGetResponseJson) {
      DepositSwitchGetResponseObject <- jsonlite::fromJSON(DepositSwitchGetResponseJson)
      if (!is.null(DepositSwitchGetResponseObject$`deposit_switch_id`)) {
        self$`deposit_switch_id` <- DepositSwitchGetResponseObject$`deposit_switch_id`
      }
      if (!is.null(DepositSwitchGetResponseObject$`target_account_id`)) {
        self$`target_account_id` <- DepositSwitchGetResponseObject$`target_account_id`
      }
      if (!is.null(DepositSwitchGetResponseObject$`target_item_id`)) {
        self$`target_item_id` <- DepositSwitchGetResponseObject$`target_item_id`
      }
      if (!is.null(DepositSwitchGetResponseObject$`state`)) {
        self$`state` <- DepositSwitchGetResponseObject$`state`
      }
      if (!is.null(DepositSwitchGetResponseObject$`switch_method`)) {
        self$`switch_method` <- DepositSwitchGetResponseObject$`switch_method`
      }
      if (!is.null(DepositSwitchGetResponseObject$`account_has_multiple_allocations`)) {
        self$`account_has_multiple_allocations` <- DepositSwitchGetResponseObject$`account_has_multiple_allocations`
      }
      if (!is.null(DepositSwitchGetResponseObject$`is_allocated_remainder`)) {
        self$`is_allocated_remainder` <- DepositSwitchGetResponseObject$`is_allocated_remainder`
      }
      if (!is.null(DepositSwitchGetResponseObject$`percent_allocated`)) {
        self$`percent_allocated` <- DepositSwitchGetResponseObject$`percent_allocated`
      }
      if (!is.null(DepositSwitchGetResponseObject$`amount_allocated`)) {
        self$`amount_allocated` <- DepositSwitchGetResponseObject$`amount_allocated`
      }
      if (!is.null(DepositSwitchGetResponseObject$`employer_name`)) {
        self$`employer_name` <- DepositSwitchGetResponseObject$`employer_name`
      }
      if (!is.null(DepositSwitchGetResponseObject$`employer_id`)) {
        self$`employer_id` <- DepositSwitchGetResponseObject$`employer_id`
      }
      if (!is.null(DepositSwitchGetResponseObject$`institution_name`)) {
        self$`institution_name` <- DepositSwitchGetResponseObject$`institution_name`
      }
      if (!is.null(DepositSwitchGetResponseObject$`institution_id`)) {
        self$`institution_id` <- DepositSwitchGetResponseObject$`institution_id`
      }
      if (!is.null(DepositSwitchGetResponseObject$`date_created`)) {
        self$`date_created` <- DepositSwitchGetResponseObject$`date_created`
      }
      if (!is.null(DepositSwitchGetResponseObject$`date_completed`)) {
        self$`date_completed` <- DepositSwitchGetResponseObject$`date_completed`
      }
      if (!is.null(DepositSwitchGetResponseObject$`request_id`)) {
        self$`request_id` <- DepositSwitchGetResponseObject$`request_id`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`deposit_switch_id`)) {
        sprintf(
        '"deposit_switch_id":
          "%s"
                ',
        self$`deposit_switch_id`
        )},
        if (!is.null(self$`target_account_id`)) {
        sprintf(
        '"target_account_id":
          "%s"
                ',
        self$`target_account_id`
        )},
        if (!is.null(self$`target_item_id`)) {
        sprintf(
        '"target_item_id":
          "%s"
                ',
        self$`target_item_id`
        )},
        if (!is.null(self$`state`)) {
        sprintf(
        '"state":
          "%s"
                ',
        self$`state`
        )},
        if (!is.null(self$`switch_method`)) {
        sprintf(
        '"switch_method":
          "%s"
                ',
        self$`switch_method`
        )},
        if (!is.null(self$`account_has_multiple_allocations`)) {
        sprintf(
        '"account_has_multiple_allocations":
          %s
                ',
        tolower(self$`account_has_multiple_allocations`)
        )},
        if (!is.null(self$`is_allocated_remainder`)) {
        sprintf(
        '"is_allocated_remainder":
          %s
                ',
        tolower(self$`is_allocated_remainder`)
        )},
        if (!is.null(self$`percent_allocated`)) {
        sprintf(
        '"percent_allocated":
          %d
                ',
        self$`percent_allocated`
        )},
        if (!is.null(self$`amount_allocated`)) {
        sprintf(
        '"amount_allocated":
          %d
                ',
        self$`amount_allocated`
        )},
        if (!is.null(self$`employer_name`)) {
        sprintf(
        '"employer_name":
          "%s"
                ',
        self$`employer_name`
        )},
        if (!is.null(self$`employer_id`)) {
        sprintf(
        '"employer_id":
          "%s"
                ',
        self$`employer_id`
        )},
        if (!is.null(self$`institution_name`)) {
        sprintf(
        '"institution_name":
          "%s"
                ',
        self$`institution_name`
        )},
        if (!is.null(self$`institution_id`)) {
        sprintf(
        '"institution_id":
          "%s"
                ',
        self$`institution_id`
        )},
        if (!is.null(self$`date_created`)) {
        sprintf(
        '"date_created":
          "%s"
                ',
        self$`date_created`
        )},
        if (!is.null(self$`date_completed`)) {
        sprintf(
        '"date_completed":
          "%s"
                ',
        self$`date_completed`
        )},
        if (!is.null(self$`request_id`)) {
        sprintf(
        '"request_id":
          "%s"
                ',
        self$`request_id`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(DepositSwitchGetResponseJson) {
      DepositSwitchGetResponseObject <- jsonlite::fromJSON(DepositSwitchGetResponseJson)
      self$`deposit_switch_id` <- DepositSwitchGetResponseObject$`deposit_switch_id`
      self$`target_account_id` <- DepositSwitchGetResponseObject$`target_account_id`
      self$`target_item_id` <- DepositSwitchGetResponseObject$`target_item_id`
      self$`state` <- DepositSwitchGetResponseObject$`state`
      self$`switch_method` <- DepositSwitchGetResponseObject$`switch_method`
      self$`account_has_multiple_allocations` <- DepositSwitchGetResponseObject$`account_has_multiple_allocations`
      self$`is_allocated_remainder` <- DepositSwitchGetResponseObject$`is_allocated_remainder`
      self$`percent_allocated` <- DepositSwitchGetResponseObject$`percent_allocated`
      self$`amount_allocated` <- DepositSwitchGetResponseObject$`amount_allocated`
      self$`employer_name` <- DepositSwitchGetResponseObject$`employer_name`
      self$`employer_id` <- DepositSwitchGetResponseObject$`employer_id`
      self$`institution_name` <- DepositSwitchGetResponseObject$`institution_name`
      self$`institution_id` <- DepositSwitchGetResponseObject$`institution_id`
      self$`date_created` <- DepositSwitchGetResponseObject$`date_created`
      self$`date_completed` <- DepositSwitchGetResponseObject$`date_completed`
      self$`request_id` <- DepositSwitchGetResponseObject$`request_id`
      self
    }
  )
)
