# The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.146.0
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title EmploymentVerificationGetResponse
#'
#' @description EmploymentVerificationGetResponse Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field employments  list( \link{EmploymentVerification} ) 
#'
#' @field request_id RequestID character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
EmploymentVerificationGetResponse <- R6::R6Class(
  'EmploymentVerificationGetResponse',
  public = list(
    `employments` = NULL,
    `request_id` = NULL,
    initialize = function(
        `employments`, `request_id`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`employments`)) {
        stopifnot(is.vector(`employments`), length(`employments`) != 0)
        sapply(`employments`, function(x) stopifnot(R6::is.R6(x)))
        self$`employments` <- `employments`
      }
      if (!missing(`request_id`)) {
        stopifnot(is.character(`request_id`), length(`request_id`) == 1)
        self$`request_id` <- `request_id`
      }
    },
    toJSON = function() {
      EmploymentVerificationGetResponseObject <- list()
      if (!is.null(self$`employments`)) {
        EmploymentVerificationGetResponseObject[['employments']] <-
          lapply(self$`employments`, function(x) x$toJSON())
      }
      if (!is.null(self$`request_id`)) {
        EmploymentVerificationGetResponseObject[['request_id']] <-
          self$`request_id`
      }

      EmploymentVerificationGetResponseObject
    },
    fromJSON = function(EmploymentVerificationGetResponseJson) {
      EmploymentVerificationGetResponseObject <- jsonlite::fromJSON(EmploymentVerificationGetResponseJson)
      if (!is.null(EmploymentVerificationGetResponseObject$`employments`)) {
        self$`employments` <- ApiClient$new()$deserializeObj(EmploymentVerificationGetResponseObject$`employments`, "array[EmploymentVerification]", loadNamespace("plaidr"))
      }
      if (!is.null(EmploymentVerificationGetResponseObject$`request_id`)) {
        self$`request_id` <- EmploymentVerificationGetResponseObject$`request_id`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`employments`)) {
        sprintf(
        '"employments":
        [%s]
',
        paste(sapply(self$`employments`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`request_id`)) {
        sprintf(
        '"request_id":
          "%s"
                ',
        self$`request_id`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(EmploymentVerificationGetResponseJson) {
      EmploymentVerificationGetResponseObject <- jsonlite::fromJSON(EmploymentVerificationGetResponseJson)
      self$`employments` <- ApiClient$new()$deserializeObj(EmploymentVerificationGetResponseObject$`employments`, "array[EmploymentVerification]", loadNamespace("plaidr"))
      self$`request_id` <- EmploymentVerificationGetResponseObject$`request_id`
      self
    }
  )
)
