# The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.146.0
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title EntityScreeningHitDocumentsItems
#'
#' @description EntityScreeningHitDocumentsItems Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field analysis  \link{MatchSummary} [optional]
#'
#' @field data  \link{EntityDocument} [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
EntityScreeningHitDocumentsItems <- R6::R6Class(
  'EntityScreeningHitDocumentsItems',
  public = list(
    `analysis` = NULL,
    `data` = NULL,
    initialize = function(
        `analysis`=NULL, `data`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`analysis`)) {
        stopifnot(R6::is.R6(`analysis`))
        self$`analysis` <- `analysis`
      }
      if (!is.null(`data`)) {
        stopifnot(R6::is.R6(`data`))
        self$`data` <- `data`
      }
    },
    toJSON = function() {
      EntityScreeningHitDocumentsItemsObject <- list()
      if (!is.null(self$`analysis`)) {
        EntityScreeningHitDocumentsItemsObject[['analysis']] <-
          self$`analysis`$toJSON()
      }
      if (!is.null(self$`data`)) {
        EntityScreeningHitDocumentsItemsObject[['data']] <-
          self$`data`$toJSON()
      }

      EntityScreeningHitDocumentsItemsObject
    },
    fromJSON = function(EntityScreeningHitDocumentsItemsJson) {
      EntityScreeningHitDocumentsItemsObject <- jsonlite::fromJSON(EntityScreeningHitDocumentsItemsJson)
      if (!is.null(EntityScreeningHitDocumentsItemsObject$`analysis`)) {
        analysisObject <- MatchSummary$new()
        analysisObject$fromJSON(jsonlite::toJSON(EntityScreeningHitDocumentsItemsObject$analysis, auto_unbox = TRUE, digits = NA))
        self$`analysis` <- analysisObject
      }
      if (!is.null(EntityScreeningHitDocumentsItemsObject$`data`)) {
        dataObject <- EntityDocument$new()
        dataObject$fromJSON(jsonlite::toJSON(EntityScreeningHitDocumentsItemsObject$data, auto_unbox = TRUE, digits = NA))
        self$`data` <- dataObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`analysis`)) {
        sprintf(
        '"analysis":
        %s
        ',
        jsonlite::toJSON(self$`analysis`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`data`)) {
        sprintf(
        '"data":
        %s
        ',
        jsonlite::toJSON(self$`data`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(EntityScreeningHitDocumentsItemsJson) {
      EntityScreeningHitDocumentsItemsObject <- jsonlite::fromJSON(EntityScreeningHitDocumentsItemsJson)
      self$`analysis` <- MatchSummary$new()$fromJSON(jsonlite::toJSON(EntityScreeningHitDocumentsItemsObject$analysis, auto_unbox = TRUE, digits = NA))
      self$`data` <- EntityDocument$new()$fromJSON(jsonlite::toJSON(EntityScreeningHitDocumentsItemsObject$data, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)
