# The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.146.0
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title HistoricalUpdateWebhook
#'
#' @description HistoricalUpdateWebhook Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field webhook_type  character 
#'
#' @field webhook_code  character 
#'
#' @field error  \link{PlaidError} [optional]
#'
#' @field new_transactions  numeric 
#'
#' @field item_id ItemId character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
HistoricalUpdateWebhook <- R6::R6Class(
  'HistoricalUpdateWebhook',
  public = list(
    `webhook_type` = NULL,
    `webhook_code` = NULL,
    `error` = NULL,
    `new_transactions` = NULL,
    `item_id` = NULL,
    initialize = function(
        `webhook_type`, `webhook_code`, `new_transactions`, `item_id`, `error`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`webhook_type`)) {
        stopifnot(is.character(`webhook_type`), length(`webhook_type`) == 1)
        self$`webhook_type` <- `webhook_type`
      }
      if (!missing(`webhook_code`)) {
        stopifnot(is.character(`webhook_code`), length(`webhook_code`) == 1)
        self$`webhook_code` <- `webhook_code`
      }
      if (!missing(`new_transactions`)) {
        self$`new_transactions` <- `new_transactions`
      }
      if (!missing(`item_id`)) {
        stopifnot(is.character(`item_id`), length(`item_id`) == 1)
        self$`item_id` <- `item_id`
      }
      if (!is.null(`error`)) {
        stopifnot(R6::is.R6(`error`))
        self$`error` <- `error`
      }
    },
    toJSON = function() {
      HistoricalUpdateWebhookObject <- list()
      if (!is.null(self$`webhook_type`)) {
        HistoricalUpdateWebhookObject[['webhook_type']] <-
          self$`webhook_type`
      }
      if (!is.null(self$`webhook_code`)) {
        HistoricalUpdateWebhookObject[['webhook_code']] <-
          self$`webhook_code`
      }
      if (!is.null(self$`error`)) {
        HistoricalUpdateWebhookObject[['error']] <-
          self$`error`$toJSON()
      }
      if (!is.null(self$`new_transactions`)) {
        HistoricalUpdateWebhookObject[['new_transactions']] <-
          self$`new_transactions`
      }
      if (!is.null(self$`item_id`)) {
        HistoricalUpdateWebhookObject[['item_id']] <-
          self$`item_id`
      }

      HistoricalUpdateWebhookObject
    },
    fromJSON = function(HistoricalUpdateWebhookJson) {
      HistoricalUpdateWebhookObject <- jsonlite::fromJSON(HistoricalUpdateWebhookJson)
      if (!is.null(HistoricalUpdateWebhookObject$`webhook_type`)) {
        self$`webhook_type` <- HistoricalUpdateWebhookObject$`webhook_type`
      }
      if (!is.null(HistoricalUpdateWebhookObject$`webhook_code`)) {
        self$`webhook_code` <- HistoricalUpdateWebhookObject$`webhook_code`
      }
      if (!is.null(HistoricalUpdateWebhookObject$`error`)) {
        errorObject <- PlaidError$new()
        errorObject$fromJSON(jsonlite::toJSON(HistoricalUpdateWebhookObject$error, auto_unbox = TRUE, digits = NA))
        self$`error` <- errorObject
      }
      if (!is.null(HistoricalUpdateWebhookObject$`new_transactions`)) {
        self$`new_transactions` <- HistoricalUpdateWebhookObject$`new_transactions`
      }
      if (!is.null(HistoricalUpdateWebhookObject$`item_id`)) {
        self$`item_id` <- HistoricalUpdateWebhookObject$`item_id`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`webhook_type`)) {
        sprintf(
        '"webhook_type":
          "%s"
                ',
        self$`webhook_type`
        )},
        if (!is.null(self$`webhook_code`)) {
        sprintf(
        '"webhook_code":
          "%s"
                ',
        self$`webhook_code`
        )},
        if (!is.null(self$`error`)) {
        sprintf(
        '"error":
        %s
        ',
        jsonlite::toJSON(self$`error`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`new_transactions`)) {
        sprintf(
        '"new_transactions":
          %d
                ',
        self$`new_transactions`
        )},
        if (!is.null(self$`item_id`)) {
        sprintf(
        '"item_id":
          "%s"
                ',
        self$`item_id`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(HistoricalUpdateWebhookJson) {
      HistoricalUpdateWebhookObject <- jsonlite::fromJSON(HistoricalUpdateWebhookJson)
      self$`webhook_type` <- HistoricalUpdateWebhookObject$`webhook_type`
      self$`webhook_code` <- HistoricalUpdateWebhookObject$`webhook_code`
      self$`error` <- PlaidError$new()$fromJSON(jsonlite::toJSON(HistoricalUpdateWebhookObject$error, auto_unbox = TRUE, digits = NA))
      self$`new_transactions` <- HistoricalUpdateWebhookObject$`new_transactions`
      self$`item_id` <- HistoricalUpdateWebhookObject$`item_id`
      self
    }
  )
)
