# The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.146.0
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title IncomeVerificationTaxformsGetResponse
#'
#' @description IncomeVerificationTaxformsGetResponse Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field request_id RequestID character [optional]
#'
#' @field document_metadata  list( \link{DocumentMetadata} ) 
#'
#' @field taxforms  list( \link{Taxform} ) 
#'
#' @field error  \link{PlaidError} [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
IncomeVerificationTaxformsGetResponse <- R6::R6Class(
  'IncomeVerificationTaxformsGetResponse',
  public = list(
    `request_id` = NULL,
    `document_metadata` = NULL,
    `taxforms` = NULL,
    `error` = NULL,
    initialize = function(
        `document_metadata`, `taxforms`, `request_id`=NULL, `error`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`document_metadata`)) {
        stopifnot(is.vector(`document_metadata`), length(`document_metadata`) != 0)
        sapply(`document_metadata`, function(x) stopifnot(R6::is.R6(x)))
        self$`document_metadata` <- `document_metadata`
      }
      if (!missing(`taxforms`)) {
        stopifnot(is.vector(`taxforms`), length(`taxforms`) != 0)
        sapply(`taxforms`, function(x) stopifnot(R6::is.R6(x)))
        self$`taxforms` <- `taxforms`
      }
      if (!is.null(`request_id`)) {
        stopifnot(is.character(`request_id`), length(`request_id`) == 1)
        self$`request_id` <- `request_id`
      }
      if (!is.null(`error`)) {
        stopifnot(R6::is.R6(`error`))
        self$`error` <- `error`
      }
    },
    toJSON = function() {
      IncomeVerificationTaxformsGetResponseObject <- list()
      if (!is.null(self$`request_id`)) {
        IncomeVerificationTaxformsGetResponseObject[['request_id']] <-
          self$`request_id`
      }
      if (!is.null(self$`document_metadata`)) {
        IncomeVerificationTaxformsGetResponseObject[['document_metadata']] <-
          lapply(self$`document_metadata`, function(x) x$toJSON())
      }
      if (!is.null(self$`taxforms`)) {
        IncomeVerificationTaxformsGetResponseObject[['taxforms']] <-
          lapply(self$`taxforms`, function(x) x$toJSON())
      }
      if (!is.null(self$`error`)) {
        IncomeVerificationTaxformsGetResponseObject[['error']] <-
          self$`error`$toJSON()
      }

      IncomeVerificationTaxformsGetResponseObject
    },
    fromJSON = function(IncomeVerificationTaxformsGetResponseJson) {
      IncomeVerificationTaxformsGetResponseObject <- jsonlite::fromJSON(IncomeVerificationTaxformsGetResponseJson)
      if (!is.null(IncomeVerificationTaxformsGetResponseObject$`request_id`)) {
        self$`request_id` <- IncomeVerificationTaxformsGetResponseObject$`request_id`
      }
      if (!is.null(IncomeVerificationTaxformsGetResponseObject$`document_metadata`)) {
        self$`document_metadata` <- ApiClient$new()$deserializeObj(IncomeVerificationTaxformsGetResponseObject$`document_metadata`, "array[DocumentMetadata]", loadNamespace("plaidr"))
      }
      if (!is.null(IncomeVerificationTaxformsGetResponseObject$`taxforms`)) {
        self$`taxforms` <- ApiClient$new()$deserializeObj(IncomeVerificationTaxformsGetResponseObject$`taxforms`, "array[Taxform]", loadNamespace("plaidr"))
      }
      if (!is.null(IncomeVerificationTaxformsGetResponseObject$`error`)) {
        errorObject <- PlaidError$new()
        errorObject$fromJSON(jsonlite::toJSON(IncomeVerificationTaxformsGetResponseObject$error, auto_unbox = TRUE, digits = NA))
        self$`error` <- errorObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`request_id`)) {
        sprintf(
        '"request_id":
          "%s"
                ',
        self$`request_id`
        )},
        if (!is.null(self$`document_metadata`)) {
        sprintf(
        '"document_metadata":
        [%s]
',
        paste(sapply(self$`document_metadata`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`taxforms`)) {
        sprintf(
        '"taxforms":
        [%s]
',
        paste(sapply(self$`taxforms`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`error`)) {
        sprintf(
        '"error":
        %s
        ',
        jsonlite::toJSON(self$`error`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(IncomeVerificationTaxformsGetResponseJson) {
      IncomeVerificationTaxformsGetResponseObject <- jsonlite::fromJSON(IncomeVerificationTaxformsGetResponseJson)
      self$`request_id` <- IncomeVerificationTaxformsGetResponseObject$`request_id`
      self$`document_metadata` <- ApiClient$new()$deserializeObj(IncomeVerificationTaxformsGetResponseObject$`document_metadata`, "array[DocumentMetadata]", loadNamespace("plaidr"))
      self$`taxforms` <- ApiClient$new()$deserializeObj(IncomeVerificationTaxformsGetResponseObject$`taxforms`, "array[Taxform]", loadNamespace("plaidr"))
      self$`error` <- PlaidError$new()$fromJSON(jsonlite::toJSON(IncomeVerificationTaxformsGetResponseObject$error, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)
