# The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.146.0
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title IncomeVerificationRefreshResponse
#'
#' @description IncomeVerificationRefreshResponse Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field request_id RequestID character 
#'
#' @field verification_refresh_status  \link{VerificationRefreshStatus} 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
IncomeVerificationRefreshResponse <- R6::R6Class(
  'IncomeVerificationRefreshResponse',
  public = list(
    `request_id` = NULL,
    `verification_refresh_status` = NULL,
    initialize = function(
        `request_id`, `verification_refresh_status`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`request_id`)) {
        stopifnot(is.character(`request_id`), length(`request_id`) == 1)
        self$`request_id` <- `request_id`
      }
      if (!missing(`verification_refresh_status`)) {
        stopifnot(R6::is.R6(`verification_refresh_status`))
        self$`verification_refresh_status` <- `verification_refresh_status`
      }
    },
    toJSON = function() {
      IncomeVerificationRefreshResponseObject <- list()
      if (!is.null(self$`request_id`)) {
        IncomeVerificationRefreshResponseObject[['request_id']] <-
          self$`request_id`
      }
      if (!is.null(self$`verification_refresh_status`)) {
        IncomeVerificationRefreshResponseObject[['verification_refresh_status']] <-
          self$`verification_refresh_status`$toJSON()
      }

      IncomeVerificationRefreshResponseObject
    },
    fromJSON = function(IncomeVerificationRefreshResponseJson) {
      IncomeVerificationRefreshResponseObject <- jsonlite::fromJSON(IncomeVerificationRefreshResponseJson)
      if (!is.null(IncomeVerificationRefreshResponseObject$`request_id`)) {
        self$`request_id` <- IncomeVerificationRefreshResponseObject$`request_id`
      }
      if (!is.null(IncomeVerificationRefreshResponseObject$`verification_refresh_status`)) {
        verification_refresh_statusObject <- VerificationRefreshStatus$new()
        verification_refresh_statusObject$fromJSON(jsonlite::toJSON(IncomeVerificationRefreshResponseObject$verification_refresh_status, auto_unbox = TRUE, digits = NA))
        self$`verification_refresh_status` <- verification_refresh_statusObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`request_id`)) {
        sprintf(
        '"request_id":
          "%s"
                ',
        self$`request_id`
        )},
        if (!is.null(self$`verification_refresh_status`)) {
        sprintf(
        '"verification_refresh_status":
        %s
        ',
        jsonlite::toJSON(self$`verification_refresh_status`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(IncomeVerificationRefreshResponseJson) {
      IncomeVerificationRefreshResponseObject <- jsonlite::fromJSON(IncomeVerificationRefreshResponseJson)
      self$`request_id` <- IncomeVerificationRefreshResponseObject$`request_id`
      self$`verification_refresh_status` <- VerificationRefreshStatus$new()$fromJSON(jsonlite::toJSON(IncomeVerificationRefreshResponseObject$verification_refresh_status, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)
