# The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.146.0
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title IncomeVerificationRefreshRequest
#'
#' @description IncomeVerificationRefreshRequest Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field client_id ClientID character [optional]
#'
#' @field secret APISecret character [optional]
#'
#' @field income_verification_id  character [optional]
#'
#' @field access_token  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
IncomeVerificationRefreshRequest <- R6::R6Class(
  'IncomeVerificationRefreshRequest',
  public = list(
    `client_id` = NULL,
    `secret` = NULL,
    `income_verification_id` = NULL,
    `access_token` = NULL,
    initialize = function(
        `client_id`=NULL, `secret`=NULL, `income_verification_id`=NULL, `access_token`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`client_id`)) {
        stopifnot(is.character(`client_id`), length(`client_id`) == 1)
        self$`client_id` <- `client_id`
      }
      if (!is.null(`secret`)) {
        stopifnot(is.character(`secret`), length(`secret`) == 1)
        self$`secret` <- `secret`
      }
      if (!is.null(`income_verification_id`)) {
        stopifnot(is.character(`income_verification_id`), length(`income_verification_id`) == 1)
        self$`income_verification_id` <- `income_verification_id`
      }
      if (!is.null(`access_token`)) {
        stopifnot(is.character(`access_token`), length(`access_token`) == 1)
        self$`access_token` <- `access_token`
      }
    },
    toJSON = function() {
      IncomeVerificationRefreshRequestObject <- list()
      if (!is.null(self$`client_id`)) {
        IncomeVerificationRefreshRequestObject[['client_id']] <-
          self$`client_id`
      }
      if (!is.null(self$`secret`)) {
        IncomeVerificationRefreshRequestObject[['secret']] <-
          self$`secret`
      }
      if (!is.null(self$`income_verification_id`)) {
        IncomeVerificationRefreshRequestObject[['income_verification_id']] <-
          self$`income_verification_id`
      }
      if (!is.null(self$`access_token`)) {
        IncomeVerificationRefreshRequestObject[['access_token']] <-
          self$`access_token`
      }

      IncomeVerificationRefreshRequestObject
    },
    fromJSON = function(IncomeVerificationRefreshRequestJson) {
      IncomeVerificationRefreshRequestObject <- jsonlite::fromJSON(IncomeVerificationRefreshRequestJson)
      if (!is.null(IncomeVerificationRefreshRequestObject$`client_id`)) {
        self$`client_id` <- IncomeVerificationRefreshRequestObject$`client_id`
      }
      if (!is.null(IncomeVerificationRefreshRequestObject$`secret`)) {
        self$`secret` <- IncomeVerificationRefreshRequestObject$`secret`
      }
      if (!is.null(IncomeVerificationRefreshRequestObject$`income_verification_id`)) {
        self$`income_verification_id` <- IncomeVerificationRefreshRequestObject$`income_verification_id`
      }
      if (!is.null(IncomeVerificationRefreshRequestObject$`access_token`)) {
        self$`access_token` <- IncomeVerificationRefreshRequestObject$`access_token`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`client_id`)) {
        sprintf(
        '"client_id":
          "%s"
                ',
        self$`client_id`
        )},
        if (!is.null(self$`secret`)) {
        sprintf(
        '"secret":
          "%s"
                ',
        self$`secret`
        )},
        if (!is.null(self$`income_verification_id`)) {
        sprintf(
        '"income_verification_id":
          "%s"
                ',
        self$`income_verification_id`
        )},
        if (!is.null(self$`access_token`)) {
        sprintf(
        '"access_token":
          "%s"
                ',
        self$`access_token`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(IncomeVerificationRefreshRequestJson) {
      IncomeVerificationRefreshRequestObject <- jsonlite::fromJSON(IncomeVerificationRefreshRequestJson)
      self$`client_id` <- IncomeVerificationRefreshRequestObject$`client_id`
      self$`secret` <- IncomeVerificationRefreshRequestObject$`secret`
      self$`income_verification_id` <- IncomeVerificationRefreshRequestObject$`income_verification_id`
      self$`access_token` <- IncomeVerificationRefreshRequestObject$`access_token`
      self
    }
  )
)
