# The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.146.0
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ItemPublicTokenExchangeResponse
#'
#' @description ItemPublicTokenExchangeResponse Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field access_token AccessToken character 
#'
#' @field item_id  character 
#'
#' @field request_id RequestID character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ItemPublicTokenExchangeResponse <- R6::R6Class(
  'ItemPublicTokenExchangeResponse',
  public = list(
    `access_token` = NULL,
    `item_id` = NULL,
    `request_id` = NULL,
    initialize = function(
        `access_token`, `item_id`, `request_id`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`access_token`)) {
        stopifnot(is.character(`access_token`), length(`access_token`) == 1)
        self$`access_token` <- `access_token`
      }
      if (!missing(`item_id`)) {
        stopifnot(is.character(`item_id`), length(`item_id`) == 1)
        self$`item_id` <- `item_id`
      }
      if (!missing(`request_id`)) {
        stopifnot(is.character(`request_id`), length(`request_id`) == 1)
        self$`request_id` <- `request_id`
      }
    },
    toJSON = function() {
      ItemPublicTokenExchangeResponseObject <- list()
      if (!is.null(self$`access_token`)) {
        ItemPublicTokenExchangeResponseObject[['access_token']] <-
          self$`access_token`
      }
      if (!is.null(self$`item_id`)) {
        ItemPublicTokenExchangeResponseObject[['item_id']] <-
          self$`item_id`
      }
      if (!is.null(self$`request_id`)) {
        ItemPublicTokenExchangeResponseObject[['request_id']] <-
          self$`request_id`
      }

      ItemPublicTokenExchangeResponseObject
    },
    fromJSON = function(ItemPublicTokenExchangeResponseJson) {
      ItemPublicTokenExchangeResponseObject <- jsonlite::fromJSON(ItemPublicTokenExchangeResponseJson)
      if (!is.null(ItemPublicTokenExchangeResponseObject$`access_token`)) {
        self$`access_token` <- ItemPublicTokenExchangeResponseObject$`access_token`
      }
      if (!is.null(ItemPublicTokenExchangeResponseObject$`item_id`)) {
        self$`item_id` <- ItemPublicTokenExchangeResponseObject$`item_id`
      }
      if (!is.null(ItemPublicTokenExchangeResponseObject$`request_id`)) {
        self$`request_id` <- ItemPublicTokenExchangeResponseObject$`request_id`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`access_token`)) {
        sprintf(
        '"access_token":
          "%s"
                ',
        self$`access_token`
        )},
        if (!is.null(self$`item_id`)) {
        sprintf(
        '"item_id":
          "%s"
                ',
        self$`item_id`
        )},
        if (!is.null(self$`request_id`)) {
        sprintf(
        '"request_id":
          "%s"
                ',
        self$`request_id`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ItemPublicTokenExchangeResponseJson) {
      ItemPublicTokenExchangeResponseObject <- jsonlite::fromJSON(ItemPublicTokenExchangeResponseJson)
      self$`access_token` <- ItemPublicTokenExchangeResponseObject$`access_token`
      self$`item_id` <- ItemPublicTokenExchangeResponseObject$`item_id`
      self$`request_id` <- ItemPublicTokenExchangeResponseObject$`request_id`
      self
    }
  )
)
