# The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.146.0
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title JWKPublicKey
#'
#' @description JWKPublicKey Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field alg  character 
#'
#' @field crv  character 
#'
#' @field kid  character 
#'
#' @field kty  character 
#'
#' @field use  character 
#'
#' @field x  character 
#'
#' @field y  character 
#'
#' @field created_at  integer 
#'
#' @field expired_at  integer 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
JWKPublicKey <- R6::R6Class(
  'JWKPublicKey',
  public = list(
    `alg` = NULL,
    `crv` = NULL,
    `kid` = NULL,
    `kty` = NULL,
    `use` = NULL,
    `x` = NULL,
    `y` = NULL,
    `created_at` = NULL,
    `expired_at` = NULL,
    initialize = function(
        `alg`, `crv`, `kid`, `kty`, `use`, `x`, `y`, `created_at`, `expired_at`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`alg`)) {
        stopifnot(is.character(`alg`), length(`alg`) == 1)
        self$`alg` <- `alg`
      }
      if (!missing(`crv`)) {
        stopifnot(is.character(`crv`), length(`crv`) == 1)
        self$`crv` <- `crv`
      }
      if (!missing(`kid`)) {
        stopifnot(is.character(`kid`), length(`kid`) == 1)
        self$`kid` <- `kid`
      }
      if (!missing(`kty`)) {
        stopifnot(is.character(`kty`), length(`kty`) == 1)
        self$`kty` <- `kty`
      }
      if (!missing(`use`)) {
        stopifnot(is.character(`use`), length(`use`) == 1)
        self$`use` <- `use`
      }
      if (!missing(`x`)) {
        stopifnot(is.character(`x`), length(`x`) == 1)
        self$`x` <- `x`
      }
      if (!missing(`y`)) {
        stopifnot(is.character(`y`), length(`y`) == 1)
        self$`y` <- `y`
      }
      if (!missing(`created_at`)) {
        stopifnot(is.numeric(`created_at`), length(`created_at`) == 1)
        self$`created_at` <- `created_at`
      }
      if (!missing(`expired_at`)) {
        stopifnot(is.numeric(`expired_at`), length(`expired_at`) == 1)
        self$`expired_at` <- `expired_at`
      }
    },
    toJSON = function() {
      JWKPublicKeyObject <- list()
      if (!is.null(self$`alg`)) {
        JWKPublicKeyObject[['alg']] <-
          self$`alg`
      }
      if (!is.null(self$`crv`)) {
        JWKPublicKeyObject[['crv']] <-
          self$`crv`
      }
      if (!is.null(self$`kid`)) {
        JWKPublicKeyObject[['kid']] <-
          self$`kid`
      }
      if (!is.null(self$`kty`)) {
        JWKPublicKeyObject[['kty']] <-
          self$`kty`
      }
      if (!is.null(self$`use`)) {
        JWKPublicKeyObject[['use']] <-
          self$`use`
      }
      if (!is.null(self$`x`)) {
        JWKPublicKeyObject[['x']] <-
          self$`x`
      }
      if (!is.null(self$`y`)) {
        JWKPublicKeyObject[['y']] <-
          self$`y`
      }
      if (!is.null(self$`created_at`)) {
        JWKPublicKeyObject[['created_at']] <-
          self$`created_at`
      }
      if (!is.null(self$`expired_at`)) {
        JWKPublicKeyObject[['expired_at']] <-
          self$`expired_at`
      }

      JWKPublicKeyObject
    },
    fromJSON = function(JWKPublicKeyJson) {
      JWKPublicKeyObject <- jsonlite::fromJSON(JWKPublicKeyJson)
      if (!is.null(JWKPublicKeyObject$`alg`)) {
        self$`alg` <- JWKPublicKeyObject$`alg`
      }
      if (!is.null(JWKPublicKeyObject$`crv`)) {
        self$`crv` <- JWKPublicKeyObject$`crv`
      }
      if (!is.null(JWKPublicKeyObject$`kid`)) {
        self$`kid` <- JWKPublicKeyObject$`kid`
      }
      if (!is.null(JWKPublicKeyObject$`kty`)) {
        self$`kty` <- JWKPublicKeyObject$`kty`
      }
      if (!is.null(JWKPublicKeyObject$`use`)) {
        self$`use` <- JWKPublicKeyObject$`use`
      }
      if (!is.null(JWKPublicKeyObject$`x`)) {
        self$`x` <- JWKPublicKeyObject$`x`
      }
      if (!is.null(JWKPublicKeyObject$`y`)) {
        self$`y` <- JWKPublicKeyObject$`y`
      }
      if (!is.null(JWKPublicKeyObject$`created_at`)) {
        self$`created_at` <- JWKPublicKeyObject$`created_at`
      }
      if (!is.null(JWKPublicKeyObject$`expired_at`)) {
        self$`expired_at` <- JWKPublicKeyObject$`expired_at`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`alg`)) {
        sprintf(
        '"alg":
          "%s"
                ',
        self$`alg`
        )},
        if (!is.null(self$`crv`)) {
        sprintf(
        '"crv":
          "%s"
                ',
        self$`crv`
        )},
        if (!is.null(self$`kid`)) {
        sprintf(
        '"kid":
          "%s"
                ',
        self$`kid`
        )},
        if (!is.null(self$`kty`)) {
        sprintf(
        '"kty":
          "%s"
                ',
        self$`kty`
        )},
        if (!is.null(self$`use`)) {
        sprintf(
        '"use":
          "%s"
                ',
        self$`use`
        )},
        if (!is.null(self$`x`)) {
        sprintf(
        '"x":
          "%s"
                ',
        self$`x`
        )},
        if (!is.null(self$`y`)) {
        sprintf(
        '"y":
          "%s"
                ',
        self$`y`
        )},
        if (!is.null(self$`created_at`)) {
        sprintf(
        '"created_at":
          %d
                ',
        self$`created_at`
        )},
        if (!is.null(self$`expired_at`)) {
        sprintf(
        '"expired_at":
          %d
                ',
        self$`expired_at`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(JWKPublicKeyJson) {
      JWKPublicKeyObject <- jsonlite::fromJSON(JWKPublicKeyJson)
      self$`alg` <- JWKPublicKeyObject$`alg`
      self$`crv` <- JWKPublicKeyObject$`crv`
      self$`kid` <- JWKPublicKeyObject$`kid`
      self$`kty` <- JWKPublicKeyObject$`kty`
      self$`use` <- JWKPublicKeyObject$`use`
      self$`x` <- JWKPublicKeyObject$`x`
      self$`y` <- JWKPublicKeyObject$`y`
      self$`created_at` <- JWKPublicKeyObject$`created_at`
      self$`expired_at` <- JWKPublicKeyObject$`expired_at`
      self
    }
  )
)
