# The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.146.0
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title KYCCheckDateOfBirthSummary
#'
#' @description KYCCheckDateOfBirthSummary Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field summary  \link{MatchSummaryCode} 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
KYCCheckDateOfBirthSummary <- R6::R6Class(
  'KYCCheckDateOfBirthSummary',
  public = list(
    `summary` = NULL,
    initialize = function(
        `summary`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`summary`)) {
        stopifnot(R6::is.R6(`summary`))
        self$`summary` <- `summary`
      }
    },
    toJSON = function() {
      KYCCheckDateOfBirthSummaryObject <- list()
      if (!is.null(self$`summary`)) {
        KYCCheckDateOfBirthSummaryObject[['summary']] <-
          self$`summary`$toJSON()
      }

      KYCCheckDateOfBirthSummaryObject
    },
    fromJSON = function(KYCCheckDateOfBirthSummaryJson) {
      KYCCheckDateOfBirthSummaryObject <- jsonlite::fromJSON(KYCCheckDateOfBirthSummaryJson)
      if (!is.null(KYCCheckDateOfBirthSummaryObject$`summary`)) {
        summaryObject <- MatchSummaryCode$new()
        summaryObject$fromJSON(jsonlite::toJSON(KYCCheckDateOfBirthSummaryObject$summary, auto_unbox = TRUE, digits = NA))
        self$`summary` <- summaryObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`summary`)) {
        sprintf(
        '"summary":
        %s
        ',
        jsonlite::toJSON(self$`summary`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(KYCCheckDateOfBirthSummaryJson) {
      KYCCheckDateOfBirthSummaryObject <- jsonlite::fromJSON(KYCCheckDateOfBirthSummaryJson)
      self$`summary` <- MatchSummaryCode$new()$fromJSON(jsonlite::toJSON(KYCCheckDateOfBirthSummaryObject$summary, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)
