# The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.146.0
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title LinkTokenCreateRequestAuth
#'
#' @description LinkTokenCreateRequestAuth Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field auth_type_select_enabled  character [optional]
#'
#' @field automated_microdeposits_enabled  character [optional]
#'
#' @field instant_match_enabled  character [optional]
#'
#' @field same_day_microdeposits_enabled  character [optional]
#'
#' @field flow_type  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
LinkTokenCreateRequestAuth <- R6::R6Class(
  'LinkTokenCreateRequestAuth',
  public = list(
    `auth_type_select_enabled` = NULL,
    `automated_microdeposits_enabled` = NULL,
    `instant_match_enabled` = NULL,
    `same_day_microdeposits_enabled` = NULL,
    `flow_type` = NULL,
    initialize = function(
        `auth_type_select_enabled`=FALSE, `automated_microdeposits_enabled`=NULL, `instant_match_enabled`=NULL, `same_day_microdeposits_enabled`=NULL, `flow_type`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`auth_type_select_enabled`)) {
        stopifnot(is.logical(`auth_type_select_enabled`), length(`auth_type_select_enabled`) == 1)
        self$`auth_type_select_enabled` <- `auth_type_select_enabled`
      }
      if (!is.null(`automated_microdeposits_enabled`)) {
        stopifnot(is.logical(`automated_microdeposits_enabled`), length(`automated_microdeposits_enabled`) == 1)
        self$`automated_microdeposits_enabled` <- `automated_microdeposits_enabled`
      }
      if (!is.null(`instant_match_enabled`)) {
        stopifnot(is.logical(`instant_match_enabled`), length(`instant_match_enabled`) == 1)
        self$`instant_match_enabled` <- `instant_match_enabled`
      }
      if (!is.null(`same_day_microdeposits_enabled`)) {
        stopifnot(is.logical(`same_day_microdeposits_enabled`), length(`same_day_microdeposits_enabled`) == 1)
        self$`same_day_microdeposits_enabled` <- `same_day_microdeposits_enabled`
      }
      if (!is.null(`flow_type`)) {
        stopifnot(is.character(`flow_type`), length(`flow_type`) == 1)
        self$`flow_type` <- `flow_type`
      }
    },
    toJSON = function() {
      LinkTokenCreateRequestAuthObject <- list()
      if (!is.null(self$`auth_type_select_enabled`)) {
        LinkTokenCreateRequestAuthObject[['auth_type_select_enabled']] <-
          self$`auth_type_select_enabled`
      }
      if (!is.null(self$`automated_microdeposits_enabled`)) {
        LinkTokenCreateRequestAuthObject[['automated_microdeposits_enabled']] <-
          self$`automated_microdeposits_enabled`
      }
      if (!is.null(self$`instant_match_enabled`)) {
        LinkTokenCreateRequestAuthObject[['instant_match_enabled']] <-
          self$`instant_match_enabled`
      }
      if (!is.null(self$`same_day_microdeposits_enabled`)) {
        LinkTokenCreateRequestAuthObject[['same_day_microdeposits_enabled']] <-
          self$`same_day_microdeposits_enabled`
      }
      if (!is.null(self$`flow_type`)) {
        LinkTokenCreateRequestAuthObject[['flow_type']] <-
          self$`flow_type`
      }

      LinkTokenCreateRequestAuthObject
    },
    fromJSON = function(LinkTokenCreateRequestAuthJson) {
      LinkTokenCreateRequestAuthObject <- jsonlite::fromJSON(LinkTokenCreateRequestAuthJson)
      if (!is.null(LinkTokenCreateRequestAuthObject$`auth_type_select_enabled`)) {
        self$`auth_type_select_enabled` <- LinkTokenCreateRequestAuthObject$`auth_type_select_enabled`
      }
      if (!is.null(LinkTokenCreateRequestAuthObject$`automated_microdeposits_enabled`)) {
        self$`automated_microdeposits_enabled` <- LinkTokenCreateRequestAuthObject$`automated_microdeposits_enabled`
      }
      if (!is.null(LinkTokenCreateRequestAuthObject$`instant_match_enabled`)) {
        self$`instant_match_enabled` <- LinkTokenCreateRequestAuthObject$`instant_match_enabled`
      }
      if (!is.null(LinkTokenCreateRequestAuthObject$`same_day_microdeposits_enabled`)) {
        self$`same_day_microdeposits_enabled` <- LinkTokenCreateRequestAuthObject$`same_day_microdeposits_enabled`
      }
      if (!is.null(LinkTokenCreateRequestAuthObject$`flow_type`)) {
        self$`flow_type` <- LinkTokenCreateRequestAuthObject$`flow_type`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`auth_type_select_enabled`)) {
        sprintf(
        '"auth_type_select_enabled":
          %s
                ',
        tolower(self$`auth_type_select_enabled`)
        )},
        if (!is.null(self$`automated_microdeposits_enabled`)) {
        sprintf(
        '"automated_microdeposits_enabled":
          %s
                ',
        tolower(self$`automated_microdeposits_enabled`)
        )},
        if (!is.null(self$`instant_match_enabled`)) {
        sprintf(
        '"instant_match_enabled":
          %s
                ',
        tolower(self$`instant_match_enabled`)
        )},
        if (!is.null(self$`same_day_microdeposits_enabled`)) {
        sprintf(
        '"same_day_microdeposits_enabled":
          %s
                ',
        tolower(self$`same_day_microdeposits_enabled`)
        )},
        if (!is.null(self$`flow_type`)) {
        sprintf(
        '"flow_type":
          "%s"
                ',
        self$`flow_type`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(LinkTokenCreateRequestAuthJson) {
      LinkTokenCreateRequestAuthObject <- jsonlite::fromJSON(LinkTokenCreateRequestAuthJson)
      self$`auth_type_select_enabled` <- LinkTokenCreateRequestAuthObject$`auth_type_select_enabled`
      self$`automated_microdeposits_enabled` <- LinkTokenCreateRequestAuthObject$`automated_microdeposits_enabled`
      self$`instant_match_enabled` <- LinkTokenCreateRequestAuthObject$`instant_match_enabled`
      self$`same_day_microdeposits_enabled` <- LinkTokenCreateRequestAuthObject$`same_day_microdeposits_enabled`
      self$`flow_type` <- LinkTokenCreateRequestAuthObject$`flow_type`
      self
    }
  )
)
