# The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.146.0
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title LinkTokenGetRequest
#'
#' @description LinkTokenGetRequest Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field client_id ClientID character [optional]
#'
#' @field secret APISecret character [optional]
#'
#' @field link_token  character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
LinkTokenGetRequest <- R6::R6Class(
  'LinkTokenGetRequest',
  public = list(
    `client_id` = NULL,
    `secret` = NULL,
    `link_token` = NULL,
    initialize = function(
        `link_token`, `client_id`=NULL, `secret`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`link_token`)) {
        stopifnot(is.character(`link_token`), length(`link_token`) == 1)
        self$`link_token` <- `link_token`
      }
      if (!is.null(`client_id`)) {
        stopifnot(is.character(`client_id`), length(`client_id`) == 1)
        self$`client_id` <- `client_id`
      }
      if (!is.null(`secret`)) {
        stopifnot(is.character(`secret`), length(`secret`) == 1)
        self$`secret` <- `secret`
      }
    },
    toJSON = function() {
      LinkTokenGetRequestObject <- list()
      if (!is.null(self$`client_id`)) {
        LinkTokenGetRequestObject[['client_id']] <-
          self$`client_id`
      }
      if (!is.null(self$`secret`)) {
        LinkTokenGetRequestObject[['secret']] <-
          self$`secret`
      }
      if (!is.null(self$`link_token`)) {
        LinkTokenGetRequestObject[['link_token']] <-
          self$`link_token`
      }

      LinkTokenGetRequestObject
    },
    fromJSON = function(LinkTokenGetRequestJson) {
      LinkTokenGetRequestObject <- jsonlite::fromJSON(LinkTokenGetRequestJson)
      if (!is.null(LinkTokenGetRequestObject$`client_id`)) {
        self$`client_id` <- LinkTokenGetRequestObject$`client_id`
      }
      if (!is.null(LinkTokenGetRequestObject$`secret`)) {
        self$`secret` <- LinkTokenGetRequestObject$`secret`
      }
      if (!is.null(LinkTokenGetRequestObject$`link_token`)) {
        self$`link_token` <- LinkTokenGetRequestObject$`link_token`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`client_id`)) {
        sprintf(
        '"client_id":
          "%s"
                ',
        self$`client_id`
        )},
        if (!is.null(self$`secret`)) {
        sprintf(
        '"secret":
          "%s"
                ',
        self$`secret`
        )},
        if (!is.null(self$`link_token`)) {
        sprintf(
        '"link_token":
          "%s"
                ',
        self$`link_token`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(LinkTokenGetRequestJson) {
      LinkTokenGetRequestObject <- jsonlite::fromJSON(LinkTokenGetRequestJson)
      self$`client_id` <- LinkTokenGetRequestObject$`client_id`
      self$`secret` <- LinkTokenGetRequestObject$`secret`
      self$`link_token` <- LinkTokenGetRequestObject$`link_token`
      self
    }
  )
)
