# The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.146.0
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title LinkTokenAccountFilters
#'
#' @description LinkTokenAccountFilters Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field depository  \link{DepositoryFilter} [optional]
#'
#' @field credit  \link{CreditFilter} [optional]
#'
#' @field loan  \link{LoanFilter} [optional]
#'
#' @field investment  \link{InvestmentFilter} [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
LinkTokenAccountFilters <- R6::R6Class(
  'LinkTokenAccountFilters',
  public = list(
    `depository` = NULL,
    `credit` = NULL,
    `loan` = NULL,
    `investment` = NULL,
    initialize = function(
        `depository`=NULL, `credit`=NULL, `loan`=NULL, `investment`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`depository`)) {
        stopifnot(R6::is.R6(`depository`))
        self$`depository` <- `depository`
      }
      if (!is.null(`credit`)) {
        stopifnot(R6::is.R6(`credit`))
        self$`credit` <- `credit`
      }
      if (!is.null(`loan`)) {
        stopifnot(R6::is.R6(`loan`))
        self$`loan` <- `loan`
      }
      if (!is.null(`investment`)) {
        stopifnot(R6::is.R6(`investment`))
        self$`investment` <- `investment`
      }
    },
    toJSON = function() {
      LinkTokenAccountFiltersObject <- list()
      if (!is.null(self$`depository`)) {
        LinkTokenAccountFiltersObject[['depository']] <-
          self$`depository`$toJSON()
      }
      if (!is.null(self$`credit`)) {
        LinkTokenAccountFiltersObject[['credit']] <-
          self$`credit`$toJSON()
      }
      if (!is.null(self$`loan`)) {
        LinkTokenAccountFiltersObject[['loan']] <-
          self$`loan`$toJSON()
      }
      if (!is.null(self$`investment`)) {
        LinkTokenAccountFiltersObject[['investment']] <-
          self$`investment`$toJSON()
      }

      LinkTokenAccountFiltersObject
    },
    fromJSON = function(LinkTokenAccountFiltersJson) {
      LinkTokenAccountFiltersObject <- jsonlite::fromJSON(LinkTokenAccountFiltersJson)
      if (!is.null(LinkTokenAccountFiltersObject$`depository`)) {
        depositoryObject <- DepositoryFilter$new()
        depositoryObject$fromJSON(jsonlite::toJSON(LinkTokenAccountFiltersObject$depository, auto_unbox = TRUE, digits = NA))
        self$`depository` <- depositoryObject
      }
      if (!is.null(LinkTokenAccountFiltersObject$`credit`)) {
        creditObject <- CreditFilter$new()
        creditObject$fromJSON(jsonlite::toJSON(LinkTokenAccountFiltersObject$credit, auto_unbox = TRUE, digits = NA))
        self$`credit` <- creditObject
      }
      if (!is.null(LinkTokenAccountFiltersObject$`loan`)) {
        loanObject <- LoanFilter$new()
        loanObject$fromJSON(jsonlite::toJSON(LinkTokenAccountFiltersObject$loan, auto_unbox = TRUE, digits = NA))
        self$`loan` <- loanObject
      }
      if (!is.null(LinkTokenAccountFiltersObject$`investment`)) {
        investmentObject <- InvestmentFilter$new()
        investmentObject$fromJSON(jsonlite::toJSON(LinkTokenAccountFiltersObject$investment, auto_unbox = TRUE, digits = NA))
        self$`investment` <- investmentObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`depository`)) {
        sprintf(
        '"depository":
        %s
        ',
        jsonlite::toJSON(self$`depository`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`credit`)) {
        sprintf(
        '"credit":
        %s
        ',
        jsonlite::toJSON(self$`credit`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`loan`)) {
        sprintf(
        '"loan":
        %s
        ',
        jsonlite::toJSON(self$`loan`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`investment`)) {
        sprintf(
        '"investment":
        %s
        ',
        jsonlite::toJSON(self$`investment`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(LinkTokenAccountFiltersJson) {
      LinkTokenAccountFiltersObject <- jsonlite::fromJSON(LinkTokenAccountFiltersJson)
      self$`depository` <- DepositoryFilter$new()$fromJSON(jsonlite::toJSON(LinkTokenAccountFiltersObject$depository, auto_unbox = TRUE, digits = NA))
      self$`credit` <- CreditFilter$new()$fromJSON(jsonlite::toJSON(LinkTokenAccountFiltersObject$credit, auto_unbox = TRUE, digits = NA))
      self$`loan` <- LoanFilter$new()$fromJSON(jsonlite::toJSON(LinkTokenAccountFiltersObject$loan, auto_unbox = TRUE, digits = NA))
      self$`investment` <- InvestmentFilter$new()$fromJSON(jsonlite::toJSON(LinkTokenAccountFiltersObject$investment, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)
