# The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.146.0
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title MFA
#'
#' @description MFA Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field type  character 
#'
#' @field question_rounds  numeric 
#'
#' @field questions_per_round  numeric 
#'
#' @field selection_rounds  numeric 
#'
#' @field selections_per_question  numeric 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
MFA <- R6::R6Class(
  'MFA',
  public = list(
    `type` = NULL,
    `question_rounds` = NULL,
    `questions_per_round` = NULL,
    `selection_rounds` = NULL,
    `selections_per_question` = NULL,
    initialize = function(
        `type`, `question_rounds`, `questions_per_round`, `selection_rounds`, `selections_per_question`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`type`)) {
        stopifnot(is.character(`type`), length(`type`) == 1)
        self$`type` <- `type`
      }
      if (!missing(`question_rounds`)) {
        self$`question_rounds` <- `question_rounds`
      }
      if (!missing(`questions_per_round`)) {
        self$`questions_per_round` <- `questions_per_round`
      }
      if (!missing(`selection_rounds`)) {
        self$`selection_rounds` <- `selection_rounds`
      }
      if (!missing(`selections_per_question`)) {
        self$`selections_per_question` <- `selections_per_question`
      }
    },
    toJSON = function() {
      MFAObject <- list()
      if (!is.null(self$`type`)) {
        MFAObject[['type']] <-
          self$`type`
      }
      if (!is.null(self$`question_rounds`)) {
        MFAObject[['question_rounds']] <-
          self$`question_rounds`
      }
      if (!is.null(self$`questions_per_round`)) {
        MFAObject[['questions_per_round']] <-
          self$`questions_per_round`
      }
      if (!is.null(self$`selection_rounds`)) {
        MFAObject[['selection_rounds']] <-
          self$`selection_rounds`
      }
      if (!is.null(self$`selections_per_question`)) {
        MFAObject[['selections_per_question']] <-
          self$`selections_per_question`
      }

      MFAObject
    },
    fromJSON = function(MFAJson) {
      MFAObject <- jsonlite::fromJSON(MFAJson)
      if (!is.null(MFAObject$`type`)) {
        self$`type` <- MFAObject$`type`
      }
      if (!is.null(MFAObject$`question_rounds`)) {
        self$`question_rounds` <- MFAObject$`question_rounds`
      }
      if (!is.null(MFAObject$`questions_per_round`)) {
        self$`questions_per_round` <- MFAObject$`questions_per_round`
      }
      if (!is.null(MFAObject$`selection_rounds`)) {
        self$`selection_rounds` <- MFAObject$`selection_rounds`
      }
      if (!is.null(MFAObject$`selections_per_question`)) {
        self$`selections_per_question` <- MFAObject$`selections_per_question`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`type`)) {
        sprintf(
        '"type":
          "%s"
                ',
        self$`type`
        )},
        if (!is.null(self$`question_rounds`)) {
        sprintf(
        '"question_rounds":
          %d
                ',
        self$`question_rounds`
        )},
        if (!is.null(self$`questions_per_round`)) {
        sprintf(
        '"questions_per_round":
          %d
                ',
        self$`questions_per_round`
        )},
        if (!is.null(self$`selection_rounds`)) {
        sprintf(
        '"selection_rounds":
          %d
                ',
        self$`selection_rounds`
        )},
        if (!is.null(self$`selections_per_question`)) {
        sprintf(
        '"selections_per_question":
          %d
                ',
        self$`selections_per_question`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(MFAJson) {
      MFAObject <- jsonlite::fromJSON(MFAJson)
      self$`type` <- MFAObject$`type`
      self$`question_rounds` <- MFAObject$`question_rounds`
      self$`questions_per_round` <- MFAObject$`questions_per_round`
      self$`selection_rounds` <- MFAObject$`selection_rounds`
      self$`selections_per_question` <- MFAObject$`selections_per_question`
      self
    }
  )
)
