# The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.146.0
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title MortgageInterestRate
#'
#' @description MortgageInterestRate Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field percentage  numeric 
#'
#' @field type  character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
MortgageInterestRate <- R6::R6Class(
  'MortgageInterestRate',
  public = list(
    `percentage` = NULL,
    `type` = NULL,
    initialize = function(
        `percentage`, `type`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`percentage`)) {
        stopifnot(is.numeric(`percentage`), length(`percentage`) == 1)
        self$`percentage` <- `percentage`
      }
      if (!missing(`type`)) {
        stopifnot(is.character(`type`), length(`type`) == 1)
        self$`type` <- `type`
      }
    },
    toJSON = function() {
      MortgageInterestRateObject <- list()
      if (!is.null(self$`percentage`)) {
        MortgageInterestRateObject[['percentage']] <-
          self$`percentage`
      }
      if (!is.null(self$`type`)) {
        MortgageInterestRateObject[['type']] <-
          self$`type`
      }

      MortgageInterestRateObject
    },
    fromJSON = function(MortgageInterestRateJson) {
      MortgageInterestRateObject <- jsonlite::fromJSON(MortgageInterestRateJson)
      if (!is.null(MortgageInterestRateObject$`percentage`)) {
        self$`percentage` <- MortgageInterestRateObject$`percentage`
      }
      if (!is.null(MortgageInterestRateObject$`type`)) {
        self$`type` <- MortgageInterestRateObject$`type`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`percentage`)) {
        sprintf(
        '"percentage":
          %d
                ',
        self$`percentage`
        )},
        if (!is.null(self$`type`)) {
        sprintf(
        '"type":
          "%s"
                ',
        self$`type`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(MortgageInterestRateJson) {
      MortgageInterestRateObject <- jsonlite::fromJSON(MortgageInterestRateJson)
      self$`percentage` <- MortgageInterestRateObject$`percentage`
      self$`type` <- MortgageInterestRateObject$`type`
      self
    }
  )
)
