# The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.146.0
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title MortgageLiability
#'
#' @description MortgageLiability Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field account_id  character 
#'
#' @field account_number  character 
#'
#' @field current_late_fee  numeric 
#'
#' @field escrow_balance  numeric 
#'
#' @field has_pmi  character 
#'
#' @field has_prepayment_penalty  character 
#'
#' @field interest_rate  \link{MortgageInterestRate} 
#'
#' @field last_payment_amount  numeric 
#'
#' @field last_payment_date  character 
#'
#' @field loan_type_description  character 
#'
#' @field loan_term  character 
#'
#' @field maturity_date  character 
#'
#' @field next_monthly_payment  numeric 
#'
#' @field next_payment_due_date  character 
#'
#' @field origination_date  character 
#'
#' @field origination_principal_amount  numeric 
#'
#' @field past_due_amount  numeric 
#'
#' @field property_address  \link{MortgagePropertyAddress} 
#'
#' @field ytd_interest_paid  numeric 
#'
#' @field ytd_principal_paid  numeric 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
MortgageLiability <- R6::R6Class(
  'MortgageLiability',
  public = list(
    `account_id` = NULL,
    `account_number` = NULL,
    `current_late_fee` = NULL,
    `escrow_balance` = NULL,
    `has_pmi` = NULL,
    `has_prepayment_penalty` = NULL,
    `interest_rate` = NULL,
    `last_payment_amount` = NULL,
    `last_payment_date` = NULL,
    `loan_type_description` = NULL,
    `loan_term` = NULL,
    `maturity_date` = NULL,
    `next_monthly_payment` = NULL,
    `next_payment_due_date` = NULL,
    `origination_date` = NULL,
    `origination_principal_amount` = NULL,
    `past_due_amount` = NULL,
    `property_address` = NULL,
    `ytd_interest_paid` = NULL,
    `ytd_principal_paid` = NULL,
    initialize = function(
        `account_id`, `account_number`, `current_late_fee`, `escrow_balance`, `has_pmi`, `has_prepayment_penalty`, `interest_rate`, `last_payment_amount`, `last_payment_date`, `loan_type_description`, `loan_term`, `maturity_date`, `next_monthly_payment`, `next_payment_due_date`, `origination_date`, `origination_principal_amount`, `past_due_amount`, `property_address`, `ytd_interest_paid`, `ytd_principal_paid`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`account_id`)) {
        stopifnot(is.character(`account_id`), length(`account_id`) == 1)
        self$`account_id` <- `account_id`
      }
      if (!missing(`account_number`)) {
        stopifnot(is.character(`account_number`), length(`account_number`) == 1)
        self$`account_number` <- `account_number`
      }
      if (!missing(`current_late_fee`)) {
        stopifnot(is.numeric(`current_late_fee`), length(`current_late_fee`) == 1)
        self$`current_late_fee` <- `current_late_fee`
      }
      if (!missing(`escrow_balance`)) {
        stopifnot(is.numeric(`escrow_balance`), length(`escrow_balance`) == 1)
        self$`escrow_balance` <- `escrow_balance`
      }
      if (!missing(`has_pmi`)) {
        stopifnot(is.logical(`has_pmi`), length(`has_pmi`) == 1)
        self$`has_pmi` <- `has_pmi`
      }
      if (!missing(`has_prepayment_penalty`)) {
        stopifnot(is.logical(`has_prepayment_penalty`), length(`has_prepayment_penalty`) == 1)
        self$`has_prepayment_penalty` <- `has_prepayment_penalty`
      }
      if (!missing(`interest_rate`)) {
        stopifnot(R6::is.R6(`interest_rate`))
        self$`interest_rate` <- `interest_rate`
      }
      if (!missing(`last_payment_amount`)) {
        stopifnot(is.numeric(`last_payment_amount`), length(`last_payment_amount`) == 1)
        self$`last_payment_amount` <- `last_payment_amount`
      }
      if (!missing(`last_payment_date`)) {
        stopifnot(is.character(`last_payment_date`), length(`last_payment_date`) == 1)
        self$`last_payment_date` <- `last_payment_date`
      }
      if (!missing(`loan_type_description`)) {
        stopifnot(is.character(`loan_type_description`), length(`loan_type_description`) == 1)
        self$`loan_type_description` <- `loan_type_description`
      }
      if (!missing(`loan_term`)) {
        stopifnot(is.character(`loan_term`), length(`loan_term`) == 1)
        self$`loan_term` <- `loan_term`
      }
      if (!missing(`maturity_date`)) {
        stopifnot(is.character(`maturity_date`), length(`maturity_date`) == 1)
        self$`maturity_date` <- `maturity_date`
      }
      if (!missing(`next_monthly_payment`)) {
        stopifnot(is.numeric(`next_monthly_payment`), length(`next_monthly_payment`) == 1)
        self$`next_monthly_payment` <- `next_monthly_payment`
      }
      if (!missing(`next_payment_due_date`)) {
        stopifnot(is.character(`next_payment_due_date`), length(`next_payment_due_date`) == 1)
        self$`next_payment_due_date` <- `next_payment_due_date`
      }
      if (!missing(`origination_date`)) {
        stopifnot(is.character(`origination_date`), length(`origination_date`) == 1)
        self$`origination_date` <- `origination_date`
      }
      if (!missing(`origination_principal_amount`)) {
        stopifnot(is.numeric(`origination_principal_amount`), length(`origination_principal_amount`) == 1)
        self$`origination_principal_amount` <- `origination_principal_amount`
      }
      if (!missing(`past_due_amount`)) {
        stopifnot(is.numeric(`past_due_amount`), length(`past_due_amount`) == 1)
        self$`past_due_amount` <- `past_due_amount`
      }
      if (!missing(`property_address`)) {
        stopifnot(R6::is.R6(`property_address`))
        self$`property_address` <- `property_address`
      }
      if (!missing(`ytd_interest_paid`)) {
        stopifnot(is.numeric(`ytd_interest_paid`), length(`ytd_interest_paid`) == 1)
        self$`ytd_interest_paid` <- `ytd_interest_paid`
      }
      if (!missing(`ytd_principal_paid`)) {
        stopifnot(is.numeric(`ytd_principal_paid`), length(`ytd_principal_paid`) == 1)
        self$`ytd_principal_paid` <- `ytd_principal_paid`
      }
    },
    toJSON = function() {
      MortgageLiabilityObject <- list()
      if (!is.null(self$`account_id`)) {
        MortgageLiabilityObject[['account_id']] <-
          self$`account_id`
      }
      if (!is.null(self$`account_number`)) {
        MortgageLiabilityObject[['account_number']] <-
          self$`account_number`
      }
      if (!is.null(self$`current_late_fee`)) {
        MortgageLiabilityObject[['current_late_fee']] <-
          self$`current_late_fee`
      }
      if (!is.null(self$`escrow_balance`)) {
        MortgageLiabilityObject[['escrow_balance']] <-
          self$`escrow_balance`
      }
      if (!is.null(self$`has_pmi`)) {
        MortgageLiabilityObject[['has_pmi']] <-
          self$`has_pmi`
      }
      if (!is.null(self$`has_prepayment_penalty`)) {
        MortgageLiabilityObject[['has_prepayment_penalty']] <-
          self$`has_prepayment_penalty`
      }
      if (!is.null(self$`interest_rate`)) {
        MortgageLiabilityObject[['interest_rate']] <-
          self$`interest_rate`$toJSON()
      }
      if (!is.null(self$`last_payment_amount`)) {
        MortgageLiabilityObject[['last_payment_amount']] <-
          self$`last_payment_amount`
      }
      if (!is.null(self$`last_payment_date`)) {
        MortgageLiabilityObject[['last_payment_date']] <-
          self$`last_payment_date`
      }
      if (!is.null(self$`loan_type_description`)) {
        MortgageLiabilityObject[['loan_type_description']] <-
          self$`loan_type_description`
      }
      if (!is.null(self$`loan_term`)) {
        MortgageLiabilityObject[['loan_term']] <-
          self$`loan_term`
      }
      if (!is.null(self$`maturity_date`)) {
        MortgageLiabilityObject[['maturity_date']] <-
          self$`maturity_date`
      }
      if (!is.null(self$`next_monthly_payment`)) {
        MortgageLiabilityObject[['next_monthly_payment']] <-
          self$`next_monthly_payment`
      }
      if (!is.null(self$`next_payment_due_date`)) {
        MortgageLiabilityObject[['next_payment_due_date']] <-
          self$`next_payment_due_date`
      }
      if (!is.null(self$`origination_date`)) {
        MortgageLiabilityObject[['origination_date']] <-
          self$`origination_date`
      }
      if (!is.null(self$`origination_principal_amount`)) {
        MortgageLiabilityObject[['origination_principal_amount']] <-
          self$`origination_principal_amount`
      }
      if (!is.null(self$`past_due_amount`)) {
        MortgageLiabilityObject[['past_due_amount']] <-
          self$`past_due_amount`
      }
      if (!is.null(self$`property_address`)) {
        MortgageLiabilityObject[['property_address']] <-
          self$`property_address`$toJSON()
      }
      if (!is.null(self$`ytd_interest_paid`)) {
        MortgageLiabilityObject[['ytd_interest_paid']] <-
          self$`ytd_interest_paid`
      }
      if (!is.null(self$`ytd_principal_paid`)) {
        MortgageLiabilityObject[['ytd_principal_paid']] <-
          self$`ytd_principal_paid`
      }

      MortgageLiabilityObject
    },
    fromJSON = function(MortgageLiabilityJson) {
      MortgageLiabilityObject <- jsonlite::fromJSON(MortgageLiabilityJson)
      if (!is.null(MortgageLiabilityObject$`account_id`)) {
        self$`account_id` <- MortgageLiabilityObject$`account_id`
      }
      if (!is.null(MortgageLiabilityObject$`account_number`)) {
        self$`account_number` <- MortgageLiabilityObject$`account_number`
      }
      if (!is.null(MortgageLiabilityObject$`current_late_fee`)) {
        self$`current_late_fee` <- MortgageLiabilityObject$`current_late_fee`
      }
      if (!is.null(MortgageLiabilityObject$`escrow_balance`)) {
        self$`escrow_balance` <- MortgageLiabilityObject$`escrow_balance`
      }
      if (!is.null(MortgageLiabilityObject$`has_pmi`)) {
        self$`has_pmi` <- MortgageLiabilityObject$`has_pmi`
      }
      if (!is.null(MortgageLiabilityObject$`has_prepayment_penalty`)) {
        self$`has_prepayment_penalty` <- MortgageLiabilityObject$`has_prepayment_penalty`
      }
      if (!is.null(MortgageLiabilityObject$`interest_rate`)) {
        interest_rateObject <- MortgageInterestRate$new()
        interest_rateObject$fromJSON(jsonlite::toJSON(MortgageLiabilityObject$interest_rate, auto_unbox = TRUE, digits = NA))
        self$`interest_rate` <- interest_rateObject
      }
      if (!is.null(MortgageLiabilityObject$`last_payment_amount`)) {
        self$`last_payment_amount` <- MortgageLiabilityObject$`last_payment_amount`
      }
      if (!is.null(MortgageLiabilityObject$`last_payment_date`)) {
        self$`last_payment_date` <- MortgageLiabilityObject$`last_payment_date`
      }
      if (!is.null(MortgageLiabilityObject$`loan_type_description`)) {
        self$`loan_type_description` <- MortgageLiabilityObject$`loan_type_description`
      }
      if (!is.null(MortgageLiabilityObject$`loan_term`)) {
        self$`loan_term` <- MortgageLiabilityObject$`loan_term`
      }
      if (!is.null(MortgageLiabilityObject$`maturity_date`)) {
        self$`maturity_date` <- MortgageLiabilityObject$`maturity_date`
      }
      if (!is.null(MortgageLiabilityObject$`next_monthly_payment`)) {
        self$`next_monthly_payment` <- MortgageLiabilityObject$`next_monthly_payment`
      }
      if (!is.null(MortgageLiabilityObject$`next_payment_due_date`)) {
        self$`next_payment_due_date` <- MortgageLiabilityObject$`next_payment_due_date`
      }
      if (!is.null(MortgageLiabilityObject$`origination_date`)) {
        self$`origination_date` <- MortgageLiabilityObject$`origination_date`
      }
      if (!is.null(MortgageLiabilityObject$`origination_principal_amount`)) {
        self$`origination_principal_amount` <- MortgageLiabilityObject$`origination_principal_amount`
      }
      if (!is.null(MortgageLiabilityObject$`past_due_amount`)) {
        self$`past_due_amount` <- MortgageLiabilityObject$`past_due_amount`
      }
      if (!is.null(MortgageLiabilityObject$`property_address`)) {
        property_addressObject <- MortgagePropertyAddress$new()
        property_addressObject$fromJSON(jsonlite::toJSON(MortgageLiabilityObject$property_address, auto_unbox = TRUE, digits = NA))
        self$`property_address` <- property_addressObject
      }
      if (!is.null(MortgageLiabilityObject$`ytd_interest_paid`)) {
        self$`ytd_interest_paid` <- MortgageLiabilityObject$`ytd_interest_paid`
      }
      if (!is.null(MortgageLiabilityObject$`ytd_principal_paid`)) {
        self$`ytd_principal_paid` <- MortgageLiabilityObject$`ytd_principal_paid`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`account_id`)) {
        sprintf(
        '"account_id":
          "%s"
                ',
        self$`account_id`
        )},
        if (!is.null(self$`account_number`)) {
        sprintf(
        '"account_number":
          "%s"
                ',
        self$`account_number`
        )},
        if (!is.null(self$`current_late_fee`)) {
        sprintf(
        '"current_late_fee":
          %d
                ',
        self$`current_late_fee`
        )},
        if (!is.null(self$`escrow_balance`)) {
        sprintf(
        '"escrow_balance":
          %d
                ',
        self$`escrow_balance`
        )},
        if (!is.null(self$`has_pmi`)) {
        sprintf(
        '"has_pmi":
          %s
                ',
        tolower(self$`has_pmi`)
        )},
        if (!is.null(self$`has_prepayment_penalty`)) {
        sprintf(
        '"has_prepayment_penalty":
          %s
                ',
        tolower(self$`has_prepayment_penalty`)
        )},
        if (!is.null(self$`interest_rate`)) {
        sprintf(
        '"interest_rate":
        %s
        ',
        jsonlite::toJSON(self$`interest_rate`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`last_payment_amount`)) {
        sprintf(
        '"last_payment_amount":
          %d
                ',
        self$`last_payment_amount`
        )},
        if (!is.null(self$`last_payment_date`)) {
        sprintf(
        '"last_payment_date":
          "%s"
                ',
        self$`last_payment_date`
        )},
        if (!is.null(self$`loan_type_description`)) {
        sprintf(
        '"loan_type_description":
          "%s"
                ',
        self$`loan_type_description`
        )},
        if (!is.null(self$`loan_term`)) {
        sprintf(
        '"loan_term":
          "%s"
                ',
        self$`loan_term`
        )},
        if (!is.null(self$`maturity_date`)) {
        sprintf(
        '"maturity_date":
          "%s"
                ',
        self$`maturity_date`
        )},
        if (!is.null(self$`next_monthly_payment`)) {
        sprintf(
        '"next_monthly_payment":
          %d
                ',
        self$`next_monthly_payment`
        )},
        if (!is.null(self$`next_payment_due_date`)) {
        sprintf(
        '"next_payment_due_date":
          "%s"
                ',
        self$`next_payment_due_date`
        )},
        if (!is.null(self$`origination_date`)) {
        sprintf(
        '"origination_date":
          "%s"
                ',
        self$`origination_date`
        )},
        if (!is.null(self$`origination_principal_amount`)) {
        sprintf(
        '"origination_principal_amount":
          %d
                ',
        self$`origination_principal_amount`
        )},
        if (!is.null(self$`past_due_amount`)) {
        sprintf(
        '"past_due_amount":
          %d
                ',
        self$`past_due_amount`
        )},
        if (!is.null(self$`property_address`)) {
        sprintf(
        '"property_address":
        %s
        ',
        jsonlite::toJSON(self$`property_address`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`ytd_interest_paid`)) {
        sprintf(
        '"ytd_interest_paid":
          %d
                ',
        self$`ytd_interest_paid`
        )},
        if (!is.null(self$`ytd_principal_paid`)) {
        sprintf(
        '"ytd_principal_paid":
          %d
                ',
        self$`ytd_principal_paid`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(MortgageLiabilityJson) {
      MortgageLiabilityObject <- jsonlite::fromJSON(MortgageLiabilityJson)
      self$`account_id` <- MortgageLiabilityObject$`account_id`
      self$`account_number` <- MortgageLiabilityObject$`account_number`
      self$`current_late_fee` <- MortgageLiabilityObject$`current_late_fee`
      self$`escrow_balance` <- MortgageLiabilityObject$`escrow_balance`
      self$`has_pmi` <- MortgageLiabilityObject$`has_pmi`
      self$`has_prepayment_penalty` <- MortgageLiabilityObject$`has_prepayment_penalty`
      self$`interest_rate` <- MortgageInterestRate$new()$fromJSON(jsonlite::toJSON(MortgageLiabilityObject$interest_rate, auto_unbox = TRUE, digits = NA))
      self$`last_payment_amount` <- MortgageLiabilityObject$`last_payment_amount`
      self$`last_payment_date` <- MortgageLiabilityObject$`last_payment_date`
      self$`loan_type_description` <- MortgageLiabilityObject$`loan_type_description`
      self$`loan_term` <- MortgageLiabilityObject$`loan_term`
      self$`maturity_date` <- MortgageLiabilityObject$`maturity_date`
      self$`next_monthly_payment` <- MortgageLiabilityObject$`next_monthly_payment`
      self$`next_payment_due_date` <- MortgageLiabilityObject$`next_payment_due_date`
      self$`origination_date` <- MortgageLiabilityObject$`origination_date`
      self$`origination_principal_amount` <- MortgageLiabilityObject$`origination_principal_amount`
      self$`past_due_amount` <- MortgageLiabilityObject$`past_due_amount`
      self$`property_address` <- MortgagePropertyAddress$new()$fromJSON(jsonlite::toJSON(MortgageLiabilityObject$property_address, auto_unbox = TRUE, digits = NA))
      self$`ytd_interest_paid` <- MortgageLiabilityObject$`ytd_interest_paid`
      self$`ytd_principal_paid` <- MortgageLiabilityObject$`ytd_principal_paid`
      self
    }
  )
)
