# The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.146.0
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title MultiDocumentRiskSignal
#'
#' @description MultiDocumentRiskSignal Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field document_references  list( \link{RiskSignalDocumentReference} ) 
#'
#' @field risk_signals  list( \link{DocumentRiskSignal} ) 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
MultiDocumentRiskSignal <- R6::R6Class(
  'MultiDocumentRiskSignal',
  public = list(
    `document_references` = NULL,
    `risk_signals` = NULL,
    initialize = function(
        `document_references`, `risk_signals`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`document_references`)) {
        stopifnot(is.vector(`document_references`), length(`document_references`) != 0)
        sapply(`document_references`, function(x) stopifnot(R6::is.R6(x)))
        self$`document_references` <- `document_references`
      }
      if (!missing(`risk_signals`)) {
        stopifnot(is.vector(`risk_signals`), length(`risk_signals`) != 0)
        sapply(`risk_signals`, function(x) stopifnot(R6::is.R6(x)))
        self$`risk_signals` <- `risk_signals`
      }
    },
    toJSON = function() {
      MultiDocumentRiskSignalObject <- list()
      if (!is.null(self$`document_references`)) {
        MultiDocumentRiskSignalObject[['document_references']] <-
          lapply(self$`document_references`, function(x) x$toJSON())
      }
      if (!is.null(self$`risk_signals`)) {
        MultiDocumentRiskSignalObject[['risk_signals']] <-
          lapply(self$`risk_signals`, function(x) x$toJSON())
      }

      MultiDocumentRiskSignalObject
    },
    fromJSON = function(MultiDocumentRiskSignalJson) {
      MultiDocumentRiskSignalObject <- jsonlite::fromJSON(MultiDocumentRiskSignalJson)
      if (!is.null(MultiDocumentRiskSignalObject$`document_references`)) {
        self$`document_references` <- ApiClient$new()$deserializeObj(MultiDocumentRiskSignalObject$`document_references`, "array[RiskSignalDocumentReference]", loadNamespace("plaidr"))
      }
      if (!is.null(MultiDocumentRiskSignalObject$`risk_signals`)) {
        self$`risk_signals` <- ApiClient$new()$deserializeObj(MultiDocumentRiskSignalObject$`risk_signals`, "array[DocumentRiskSignal]", loadNamespace("plaidr"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`document_references`)) {
        sprintf(
        '"document_references":
        [%s]
',
        paste(sapply(self$`document_references`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`risk_signals`)) {
        sprintf(
        '"risk_signals":
        [%s]
',
        paste(sapply(self$`risk_signals`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(MultiDocumentRiskSignalJson) {
      MultiDocumentRiskSignalObject <- jsonlite::fromJSON(MultiDocumentRiskSignalJson)
      self$`document_references` <- ApiClient$new()$deserializeObj(MultiDocumentRiskSignalObject$`document_references`, "array[RiskSignalDocumentReference]", loadNamespace("plaidr"))
      self$`risk_signals` <- ApiClient$new()$deserializeObj(MultiDocumentRiskSignalObject$`risk_signals`, "array[DocumentRiskSignal]", loadNamespace("plaidr"))
      self
    }
  )
)
