# The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.146.0
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title NumbersACH
#'
#' @description NumbersACH Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field account_id  character 
#'
#' @field account  character 
#'
#' @field routing  character 
#'
#' @field wire_routing  character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
NumbersACH <- R6::R6Class(
  'NumbersACH',
  public = list(
    `account_id` = NULL,
    `account` = NULL,
    `routing` = NULL,
    `wire_routing` = NULL,
    initialize = function(
        `account_id`, `account`, `routing`, `wire_routing`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`account_id`)) {
        stopifnot(is.character(`account_id`), length(`account_id`) == 1)
        self$`account_id` <- `account_id`
      }
      if (!missing(`account`)) {
        stopifnot(is.character(`account`), length(`account`) == 1)
        self$`account` <- `account`
      }
      if (!missing(`routing`)) {
        stopifnot(is.character(`routing`), length(`routing`) == 1)
        self$`routing` <- `routing`
      }
      if (!missing(`wire_routing`)) {
        stopifnot(is.character(`wire_routing`), length(`wire_routing`) == 1)
        self$`wire_routing` <- `wire_routing`
      }
    },
    toJSON = function() {
      NumbersACHObject <- list()
      if (!is.null(self$`account_id`)) {
        NumbersACHObject[['account_id']] <-
          self$`account_id`
      }
      if (!is.null(self$`account`)) {
        NumbersACHObject[['account']] <-
          self$`account`
      }
      if (!is.null(self$`routing`)) {
        NumbersACHObject[['routing']] <-
          self$`routing`
      }
      if (!is.null(self$`wire_routing`)) {
        NumbersACHObject[['wire_routing']] <-
          self$`wire_routing`
      }

      NumbersACHObject
    },
    fromJSON = function(NumbersACHJson) {
      NumbersACHObject <- jsonlite::fromJSON(NumbersACHJson)
      if (!is.null(NumbersACHObject$`account_id`)) {
        self$`account_id` <- NumbersACHObject$`account_id`
      }
      if (!is.null(NumbersACHObject$`account`)) {
        self$`account` <- NumbersACHObject$`account`
      }
      if (!is.null(NumbersACHObject$`routing`)) {
        self$`routing` <- NumbersACHObject$`routing`
      }
      if (!is.null(NumbersACHObject$`wire_routing`)) {
        self$`wire_routing` <- NumbersACHObject$`wire_routing`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`account_id`)) {
        sprintf(
        '"account_id":
          "%s"
                ',
        self$`account_id`
        )},
        if (!is.null(self$`account`)) {
        sprintf(
        '"account":
          "%s"
                ',
        self$`account`
        )},
        if (!is.null(self$`routing`)) {
        sprintf(
        '"routing":
          "%s"
                ',
        self$`routing`
        )},
        if (!is.null(self$`wire_routing`)) {
        sprintf(
        '"wire_routing":
          "%s"
                ',
        self$`wire_routing`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(NumbersACHJson) {
      NumbersACHObject <- jsonlite::fromJSON(NumbersACHJson)
      self$`account_id` <- NumbersACHObject$`account_id`
      self$`account` <- NumbersACHObject$`account`
      self$`routing` <- NumbersACHObject$`routing`
      self$`wire_routing` <- NumbersACHObject$`wire_routing`
      self
    }
  )
)
