# The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.146.0
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title PaginatedIndividualWatchlistScreeningReviewListResponse
#'
#' @description PaginatedIndividualWatchlistScreeningReviewListResponse Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field watchlist_screening_reviews  list( \link{WatchlistScreeningReview} ) 
#'
#' @field next_cursor  character 
#'
#' @field request_id RequestID character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PaginatedIndividualWatchlistScreeningReviewListResponse <- R6::R6Class(
  'PaginatedIndividualWatchlistScreeningReviewListResponse',
  public = list(
    `watchlist_screening_reviews` = NULL,
    `next_cursor` = NULL,
    `request_id` = NULL,
    initialize = function(
        `watchlist_screening_reviews`, `next_cursor`, `request_id`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`watchlist_screening_reviews`)) {
        stopifnot(is.vector(`watchlist_screening_reviews`), length(`watchlist_screening_reviews`) != 0)
        sapply(`watchlist_screening_reviews`, function(x) stopifnot(R6::is.R6(x)))
        self$`watchlist_screening_reviews` <- `watchlist_screening_reviews`
      }
      if (!missing(`next_cursor`)) {
        stopifnot(is.character(`next_cursor`), length(`next_cursor`) == 1)
        self$`next_cursor` <- `next_cursor`
      }
      if (!missing(`request_id`)) {
        stopifnot(is.character(`request_id`), length(`request_id`) == 1)
        self$`request_id` <- `request_id`
      }
    },
    toJSON = function() {
      PaginatedIndividualWatchlistScreeningReviewListResponseObject <- list()
      if (!is.null(self$`watchlist_screening_reviews`)) {
        PaginatedIndividualWatchlistScreeningReviewListResponseObject[['watchlist_screening_reviews']] <-
          lapply(self$`watchlist_screening_reviews`, function(x) x$toJSON())
      }
      if (!is.null(self$`next_cursor`)) {
        PaginatedIndividualWatchlistScreeningReviewListResponseObject[['next_cursor']] <-
          self$`next_cursor`
      }
      if (!is.null(self$`request_id`)) {
        PaginatedIndividualWatchlistScreeningReviewListResponseObject[['request_id']] <-
          self$`request_id`
      }

      PaginatedIndividualWatchlistScreeningReviewListResponseObject
    },
    fromJSON = function(PaginatedIndividualWatchlistScreeningReviewListResponseJson) {
      PaginatedIndividualWatchlistScreeningReviewListResponseObject <- jsonlite::fromJSON(PaginatedIndividualWatchlistScreeningReviewListResponseJson)
      if (!is.null(PaginatedIndividualWatchlistScreeningReviewListResponseObject$`watchlist_screening_reviews`)) {
        self$`watchlist_screening_reviews` <- ApiClient$new()$deserializeObj(PaginatedIndividualWatchlistScreeningReviewListResponseObject$`watchlist_screening_reviews`, "array[WatchlistScreeningReview]", loadNamespace("plaidr"))
      }
      if (!is.null(PaginatedIndividualWatchlistScreeningReviewListResponseObject$`next_cursor`)) {
        self$`next_cursor` <- PaginatedIndividualWatchlistScreeningReviewListResponseObject$`next_cursor`
      }
      if (!is.null(PaginatedIndividualWatchlistScreeningReviewListResponseObject$`request_id`)) {
        self$`request_id` <- PaginatedIndividualWatchlistScreeningReviewListResponseObject$`request_id`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`watchlist_screening_reviews`)) {
        sprintf(
        '"watchlist_screening_reviews":
        [%s]
',
        paste(sapply(self$`watchlist_screening_reviews`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`next_cursor`)) {
        sprintf(
        '"next_cursor":
          "%s"
                ',
        self$`next_cursor`
        )},
        if (!is.null(self$`request_id`)) {
        sprintf(
        '"request_id":
          "%s"
                ',
        self$`request_id`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(PaginatedIndividualWatchlistScreeningReviewListResponseJson) {
      PaginatedIndividualWatchlistScreeningReviewListResponseObject <- jsonlite::fromJSON(PaginatedIndividualWatchlistScreeningReviewListResponseJson)
      self$`watchlist_screening_reviews` <- ApiClient$new()$deserializeObj(PaginatedIndividualWatchlistScreeningReviewListResponseObject$`watchlist_screening_reviews`, "array[WatchlistScreeningReview]", loadNamespace("plaidr"))
      self$`next_cursor` <- PaginatedIndividualWatchlistScreeningReviewListResponseObject$`next_cursor`
      self$`request_id` <- PaginatedIndividualWatchlistScreeningReviewListResponseObject$`request_id`
      self
    }
  )
)
