# The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.146.0
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title PaymentInitiationConsentGetResponse
#'
#' @description PaymentInitiationConsentGetResponse Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field consent_id  character 
#'
#' @field status  \link{PaymentInitiationConsentStatus} 
#'
#' @field created_at  character 
#'
#' @field recipient_id  character 
#'
#' @field reference  character 
#'
#' @field constraints  \link{PaymentInitiationConsentConstraints} 
#'
#' @field scopes  list( \link{PaymentInitiationConsentScope} ) 
#'
#' @field request_id RequestID character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PaymentInitiationConsentGetResponse <- R6::R6Class(
  'PaymentInitiationConsentGetResponse',
  public = list(
    `consent_id` = NULL,
    `status` = NULL,
    `created_at` = NULL,
    `recipient_id` = NULL,
    `reference` = NULL,
    `constraints` = NULL,
    `scopes` = NULL,
    `request_id` = NULL,
    initialize = function(
        `consent_id`, `status`, `created_at`, `recipient_id`, `reference`, `constraints`, `scopes`, `request_id`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`consent_id`)) {
        stopifnot(is.character(`consent_id`), length(`consent_id`) == 1)
        self$`consent_id` <- `consent_id`
      }
      if (!missing(`status`)) {
        stopifnot(R6::is.R6(`status`))
        self$`status` <- `status`
      }
      if (!missing(`created_at`)) {
        stopifnot(is.character(`created_at`), length(`created_at`) == 1)
        self$`created_at` <- `created_at`
      }
      if (!missing(`recipient_id`)) {
        stopifnot(is.character(`recipient_id`), length(`recipient_id`) == 1)
        self$`recipient_id` <- `recipient_id`
      }
      if (!missing(`reference`)) {
        stopifnot(is.character(`reference`), length(`reference`) == 1)
        self$`reference` <- `reference`
      }
      if (!missing(`constraints`)) {
        stopifnot(R6::is.R6(`constraints`))
        self$`constraints` <- `constraints`
      }
      if (!missing(`scopes`)) {
        stopifnot(is.vector(`scopes`), length(`scopes`) != 0)
        sapply(`scopes`, function(x) stopifnot(R6::is.R6(x)))
        self$`scopes` <- `scopes`
      }
      if (!missing(`request_id`)) {
        stopifnot(is.character(`request_id`), length(`request_id`) == 1)
        self$`request_id` <- `request_id`
      }
    },
    toJSON = function() {
      PaymentInitiationConsentGetResponseObject <- list()
      if (!is.null(self$`consent_id`)) {
        PaymentInitiationConsentGetResponseObject[['consent_id']] <-
          self$`consent_id`
      }
      if (!is.null(self$`status`)) {
        PaymentInitiationConsentGetResponseObject[['status']] <-
          self$`status`$toJSON()
      }
      if (!is.null(self$`created_at`)) {
        PaymentInitiationConsentGetResponseObject[['created_at']] <-
          self$`created_at`
      }
      if (!is.null(self$`recipient_id`)) {
        PaymentInitiationConsentGetResponseObject[['recipient_id']] <-
          self$`recipient_id`
      }
      if (!is.null(self$`reference`)) {
        PaymentInitiationConsentGetResponseObject[['reference']] <-
          self$`reference`
      }
      if (!is.null(self$`constraints`)) {
        PaymentInitiationConsentGetResponseObject[['constraints']] <-
          self$`constraints`$toJSON()
      }
      if (!is.null(self$`scopes`)) {
        PaymentInitiationConsentGetResponseObject[['scopes']] <-
          lapply(self$`scopes`, function(x) x$toJSON())
      }
      if (!is.null(self$`request_id`)) {
        PaymentInitiationConsentGetResponseObject[['request_id']] <-
          self$`request_id`
      }

      PaymentInitiationConsentGetResponseObject
    },
    fromJSON = function(PaymentInitiationConsentGetResponseJson) {
      PaymentInitiationConsentGetResponseObject <- jsonlite::fromJSON(PaymentInitiationConsentGetResponseJson)
      if (!is.null(PaymentInitiationConsentGetResponseObject$`consent_id`)) {
        self$`consent_id` <- PaymentInitiationConsentGetResponseObject$`consent_id`
      }
      if (!is.null(PaymentInitiationConsentGetResponseObject$`status`)) {
        statusObject <- PaymentInitiationConsentStatus$new()
        statusObject$fromJSON(jsonlite::toJSON(PaymentInitiationConsentGetResponseObject$status, auto_unbox = TRUE, digits = NA))
        self$`status` <- statusObject
      }
      if (!is.null(PaymentInitiationConsentGetResponseObject$`created_at`)) {
        self$`created_at` <- PaymentInitiationConsentGetResponseObject$`created_at`
      }
      if (!is.null(PaymentInitiationConsentGetResponseObject$`recipient_id`)) {
        self$`recipient_id` <- PaymentInitiationConsentGetResponseObject$`recipient_id`
      }
      if (!is.null(PaymentInitiationConsentGetResponseObject$`reference`)) {
        self$`reference` <- PaymentInitiationConsentGetResponseObject$`reference`
      }
      if (!is.null(PaymentInitiationConsentGetResponseObject$`constraints`)) {
        constraintsObject <- PaymentInitiationConsentConstraints$new()
        constraintsObject$fromJSON(jsonlite::toJSON(PaymentInitiationConsentGetResponseObject$constraints, auto_unbox = TRUE, digits = NA))
        self$`constraints` <- constraintsObject
      }
      if (!is.null(PaymentInitiationConsentGetResponseObject$`scopes`)) {
        self$`scopes` <- ApiClient$new()$deserializeObj(PaymentInitiationConsentGetResponseObject$`scopes`, "array[PaymentInitiationConsentScope]", loadNamespace("plaidr"))
      }
      if (!is.null(PaymentInitiationConsentGetResponseObject$`request_id`)) {
        self$`request_id` <- PaymentInitiationConsentGetResponseObject$`request_id`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`consent_id`)) {
        sprintf(
        '"consent_id":
          "%s"
                ',
        self$`consent_id`
        )},
        if (!is.null(self$`status`)) {
        sprintf(
        '"status":
        %s
        ',
        jsonlite::toJSON(self$`status`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`created_at`)) {
        sprintf(
        '"created_at":
          "%s"
                ',
        self$`created_at`
        )},
        if (!is.null(self$`recipient_id`)) {
        sprintf(
        '"recipient_id":
          "%s"
                ',
        self$`recipient_id`
        )},
        if (!is.null(self$`reference`)) {
        sprintf(
        '"reference":
          "%s"
                ',
        self$`reference`
        )},
        if (!is.null(self$`constraints`)) {
        sprintf(
        '"constraints":
        %s
        ',
        jsonlite::toJSON(self$`constraints`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`scopes`)) {
        sprintf(
        '"scopes":
        [%s]
',
        paste(sapply(self$`scopes`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`request_id`)) {
        sprintf(
        '"request_id":
          "%s"
                ',
        self$`request_id`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(PaymentInitiationConsentGetResponseJson) {
      PaymentInitiationConsentGetResponseObject <- jsonlite::fromJSON(PaymentInitiationConsentGetResponseJson)
      self$`consent_id` <- PaymentInitiationConsentGetResponseObject$`consent_id`
      self$`status` <- PaymentInitiationConsentStatus$new()$fromJSON(jsonlite::toJSON(PaymentInitiationConsentGetResponseObject$status, auto_unbox = TRUE, digits = NA))
      self$`created_at` <- PaymentInitiationConsentGetResponseObject$`created_at`
      self$`recipient_id` <- PaymentInitiationConsentGetResponseObject$`recipient_id`
      self$`reference` <- PaymentInitiationConsentGetResponseObject$`reference`
      self$`constraints` <- PaymentInitiationConsentConstraints$new()$fromJSON(jsonlite::toJSON(PaymentInitiationConsentGetResponseObject$constraints, auto_unbox = TRUE, digits = NA))
      self$`scopes` <- ApiClient$new()$deserializeObj(PaymentInitiationConsentGetResponseObject$`scopes`, "array[PaymentInitiationConsentScope]", loadNamespace("plaidr"))
      self$`request_id` <- PaymentInitiationConsentGetResponseObject$`request_id`
      self
    }
  )
)
