# The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.146.0
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title PayrollIncomeAccountData
#'
#' @description PayrollIncomeAccountData Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field account_id  character 
#'
#' @field rate_of_pay  \link{PayrollIncomeRateOfPay} 
#'
#' @field pay_frequency  character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PayrollIncomeAccountData <- R6::R6Class(
  'PayrollIncomeAccountData',
  public = list(
    `account_id` = NULL,
    `rate_of_pay` = NULL,
    `pay_frequency` = NULL,
    initialize = function(
        `account_id`, `rate_of_pay`, `pay_frequency`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`account_id`)) {
        stopifnot(is.character(`account_id`), length(`account_id`) == 1)
        self$`account_id` <- `account_id`
      }
      if (!missing(`rate_of_pay`)) {
        stopifnot(R6::is.R6(`rate_of_pay`))
        self$`rate_of_pay` <- `rate_of_pay`
      }
      if (!missing(`pay_frequency`)) {
        stopifnot(is.character(`pay_frequency`), length(`pay_frequency`) == 1)
        self$`pay_frequency` <- `pay_frequency`
      }
    },
    toJSON = function() {
      PayrollIncomeAccountDataObject <- list()
      if (!is.null(self$`account_id`)) {
        PayrollIncomeAccountDataObject[['account_id']] <-
          self$`account_id`
      }
      if (!is.null(self$`rate_of_pay`)) {
        PayrollIncomeAccountDataObject[['rate_of_pay']] <-
          self$`rate_of_pay`$toJSON()
      }
      if (!is.null(self$`pay_frequency`)) {
        PayrollIncomeAccountDataObject[['pay_frequency']] <-
          self$`pay_frequency`
      }

      PayrollIncomeAccountDataObject
    },
    fromJSON = function(PayrollIncomeAccountDataJson) {
      PayrollIncomeAccountDataObject <- jsonlite::fromJSON(PayrollIncomeAccountDataJson)
      if (!is.null(PayrollIncomeAccountDataObject$`account_id`)) {
        self$`account_id` <- PayrollIncomeAccountDataObject$`account_id`
      }
      if (!is.null(PayrollIncomeAccountDataObject$`rate_of_pay`)) {
        rate_of_payObject <- PayrollIncomeRateOfPay$new()
        rate_of_payObject$fromJSON(jsonlite::toJSON(PayrollIncomeAccountDataObject$rate_of_pay, auto_unbox = TRUE, digits = NA))
        self$`rate_of_pay` <- rate_of_payObject
      }
      if (!is.null(PayrollIncomeAccountDataObject$`pay_frequency`)) {
        self$`pay_frequency` <- PayrollIncomeAccountDataObject$`pay_frequency`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`account_id`)) {
        sprintf(
        '"account_id":
          "%s"
                ',
        self$`account_id`
        )},
        if (!is.null(self$`rate_of_pay`)) {
        sprintf(
        '"rate_of_pay":
        %s
        ',
        jsonlite::toJSON(self$`rate_of_pay`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`pay_frequency`)) {
        sprintf(
        '"pay_frequency":
          "%s"
                ',
        self$`pay_frequency`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(PayrollIncomeAccountDataJson) {
      PayrollIncomeAccountDataObject <- jsonlite::fromJSON(PayrollIncomeAccountDataJson)
      self$`account_id` <- PayrollIncomeAccountDataObject$`account_id`
      self$`rate_of_pay` <- PayrollIncomeRateOfPay$new()$fromJSON(jsonlite::toJSON(PayrollIncomeAccountDataObject$rate_of_pay, auto_unbox = TRUE, digits = NA))
      self$`pay_frequency` <- PayrollIncomeAccountDataObject$`pay_frequency`
      self
    }
  )
)
