# The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.146.0
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title PhysicalDocumentExtractedData
#'
#' @description PhysicalDocumentExtractedData Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field id_number  character 
#'
#' @field category  \link{PhysicalDocumentCategory} 
#'
#' @field expiration_date  character 
#'
#' @field issuing_country GenericCountryCode character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PhysicalDocumentExtractedData <- R6::R6Class(
  'PhysicalDocumentExtractedData',
  public = list(
    `id_number` = NULL,
    `category` = NULL,
    `expiration_date` = NULL,
    `issuing_country` = NULL,
    initialize = function(
        `id_number`, `category`, `expiration_date`, `issuing_country`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`id_number`)) {
        stopifnot(is.character(`id_number`), length(`id_number`) == 1)
        self$`id_number` <- `id_number`
      }
      if (!missing(`category`)) {
        stopifnot(R6::is.R6(`category`))
        self$`category` <- `category`
      }
      if (!missing(`expiration_date`)) {
        self$`expiration_date` <- `expiration_date`
      }
      if (!missing(`issuing_country`)) {
        stopifnot(is.character(`issuing_country`), length(`issuing_country`) == 1)
        self$`issuing_country` <- `issuing_country`
      }
    },
    toJSON = function() {
      PhysicalDocumentExtractedDataObject <- list()
      if (!is.null(self$`id_number`)) {
        PhysicalDocumentExtractedDataObject[['id_number']] <-
          self$`id_number`
      }
      if (!is.null(self$`category`)) {
        PhysicalDocumentExtractedDataObject[['category']] <-
          self$`category`$toJSON()
      }
      if (!is.null(self$`expiration_date`)) {
        PhysicalDocumentExtractedDataObject[['expiration_date']] <-
          self$`expiration_date`
      }
      if (!is.null(self$`issuing_country`)) {
        PhysicalDocumentExtractedDataObject[['issuing_country']] <-
          self$`issuing_country`
      }

      PhysicalDocumentExtractedDataObject
    },
    fromJSON = function(PhysicalDocumentExtractedDataJson) {
      PhysicalDocumentExtractedDataObject <- jsonlite::fromJSON(PhysicalDocumentExtractedDataJson)
      if (!is.null(PhysicalDocumentExtractedDataObject$`id_number`)) {
        self$`id_number` <- PhysicalDocumentExtractedDataObject$`id_number`
      }
      if (!is.null(PhysicalDocumentExtractedDataObject$`category`)) {
        categoryObject <- PhysicalDocumentCategory$new()
        categoryObject$fromJSON(jsonlite::toJSON(PhysicalDocumentExtractedDataObject$category, auto_unbox = TRUE, digits = NA))
        self$`category` <- categoryObject
      }
      if (!is.null(PhysicalDocumentExtractedDataObject$`expiration_date`)) {
        self$`expiration_date` <- PhysicalDocumentExtractedDataObject$`expiration_date`
      }
      if (!is.null(PhysicalDocumentExtractedDataObject$`issuing_country`)) {
        self$`issuing_country` <- PhysicalDocumentExtractedDataObject$`issuing_country`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id_number`)) {
        sprintf(
        '"id_number":
          "%s"
                ',
        self$`id_number`
        )},
        if (!is.null(self$`category`)) {
        sprintf(
        '"category":
        %s
        ',
        jsonlite::toJSON(self$`category`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`expiration_date`)) {
        sprintf(
        '"expiration_date":
          "%s"
                ',
        self$`expiration_date`
        )},
        if (!is.null(self$`issuing_country`)) {
        sprintf(
        '"issuing_country":
          "%s"
                ',
        self$`issuing_country`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(PhysicalDocumentExtractedDataJson) {
      PhysicalDocumentExtractedDataObject <- jsonlite::fromJSON(PhysicalDocumentExtractedDataJson)
      self$`id_number` <- PhysicalDocumentExtractedDataObject$`id_number`
      self$`category` <- PhysicalDocumentCategory$new()$fromJSON(jsonlite::toJSON(PhysicalDocumentExtractedDataObject$category, auto_unbox = TRUE, digits = NA))
      self$`expiration_date` <- PhysicalDocumentExtractedDataObject$`expiration_date`
      self$`issuing_country` <- PhysicalDocumentExtractedDataObject$`issuing_country`
      self
    }
  )
)
