# The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.146.0
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title SandboxItemResetLoginRequest
#'
#' @description SandboxItemResetLoginRequest Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field client_id ClientID character [optional]
#'
#' @field secret APISecret character [optional]
#'
#' @field access_token AccessToken character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
SandboxItemResetLoginRequest <- R6::R6Class(
  'SandboxItemResetLoginRequest',
  public = list(
    `client_id` = NULL,
    `secret` = NULL,
    `access_token` = NULL,
    initialize = function(
        `access_token`, `client_id`=NULL, `secret`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`access_token`)) {
        stopifnot(is.character(`access_token`), length(`access_token`) == 1)
        self$`access_token` <- `access_token`
      }
      if (!is.null(`client_id`)) {
        stopifnot(is.character(`client_id`), length(`client_id`) == 1)
        self$`client_id` <- `client_id`
      }
      if (!is.null(`secret`)) {
        stopifnot(is.character(`secret`), length(`secret`) == 1)
        self$`secret` <- `secret`
      }
    },
    toJSON = function() {
      SandboxItemResetLoginRequestObject <- list()
      if (!is.null(self$`client_id`)) {
        SandboxItemResetLoginRequestObject[['client_id']] <-
          self$`client_id`
      }
      if (!is.null(self$`secret`)) {
        SandboxItemResetLoginRequestObject[['secret']] <-
          self$`secret`
      }
      if (!is.null(self$`access_token`)) {
        SandboxItemResetLoginRequestObject[['access_token']] <-
          self$`access_token`
      }

      SandboxItemResetLoginRequestObject
    },
    fromJSON = function(SandboxItemResetLoginRequestJson) {
      SandboxItemResetLoginRequestObject <- jsonlite::fromJSON(SandboxItemResetLoginRequestJson)
      if (!is.null(SandboxItemResetLoginRequestObject$`client_id`)) {
        self$`client_id` <- SandboxItemResetLoginRequestObject$`client_id`
      }
      if (!is.null(SandboxItemResetLoginRequestObject$`secret`)) {
        self$`secret` <- SandboxItemResetLoginRequestObject$`secret`
      }
      if (!is.null(SandboxItemResetLoginRequestObject$`access_token`)) {
        self$`access_token` <- SandboxItemResetLoginRequestObject$`access_token`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`client_id`)) {
        sprintf(
        '"client_id":
          "%s"
                ',
        self$`client_id`
        )},
        if (!is.null(self$`secret`)) {
        sprintf(
        '"secret":
          "%s"
                ',
        self$`secret`
        )},
        if (!is.null(self$`access_token`)) {
        sprintf(
        '"access_token":
          "%s"
                ',
        self$`access_token`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(SandboxItemResetLoginRequestJson) {
      SandboxItemResetLoginRequestObject <- jsonlite::fromJSON(SandboxItemResetLoginRequestJson)
      self$`client_id` <- SandboxItemResetLoginRequestObject$`client_id`
      self$`secret` <- SandboxItemResetLoginRequestObject$`secret`
      self$`access_token` <- SandboxItemResetLoginRequestObject$`access_token`
      self
    }
  )
)
