# The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.146.0
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ScreeningHitData
#'
#' @description ScreeningHitData Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field dates_of_birth  list( \link{ScreeningHitDateOfBirthItem} ) [optional]
#'
#' @field documents  list( \link{ScreeningHitDocumentsItems} ) [optional]
#'
#' @field locations  list( \link{GenericScreeningHitLocationItems} ) [optional]
#'
#' @field names  list( \link{ScreeningHitNamesItems} ) [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ScreeningHitData <- R6::R6Class(
  'ScreeningHitData',
  public = list(
    `dates_of_birth` = NULL,
    `documents` = NULL,
    `locations` = NULL,
    `names` = NULL,
    initialize = function(
        `dates_of_birth`=NULL, `documents`=NULL, `locations`=NULL, `names`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`dates_of_birth`)) {
        stopifnot(is.vector(`dates_of_birth`), length(`dates_of_birth`) != 0)
        sapply(`dates_of_birth`, function(x) stopifnot(R6::is.R6(x)))
        self$`dates_of_birth` <- `dates_of_birth`
      }
      if (!is.null(`documents`)) {
        stopifnot(is.vector(`documents`), length(`documents`) != 0)
        sapply(`documents`, function(x) stopifnot(R6::is.R6(x)))
        self$`documents` <- `documents`
      }
      if (!is.null(`locations`)) {
        stopifnot(is.vector(`locations`), length(`locations`) != 0)
        sapply(`locations`, function(x) stopifnot(R6::is.R6(x)))
        self$`locations` <- `locations`
      }
      if (!is.null(`names`)) {
        stopifnot(is.vector(`names`), length(`names`) != 0)
        sapply(`names`, function(x) stopifnot(R6::is.R6(x)))
        self$`names` <- `names`
      }
    },
    toJSON = function() {
      ScreeningHitDataObject <- list()
      if (!is.null(self$`dates_of_birth`)) {
        ScreeningHitDataObject[['dates_of_birth']] <-
          lapply(self$`dates_of_birth`, function(x) x$toJSON())
      }
      if (!is.null(self$`documents`)) {
        ScreeningHitDataObject[['documents']] <-
          lapply(self$`documents`, function(x) x$toJSON())
      }
      if (!is.null(self$`locations`)) {
        ScreeningHitDataObject[['locations']] <-
          lapply(self$`locations`, function(x) x$toJSON())
      }
      if (!is.null(self$`names`)) {
        ScreeningHitDataObject[['names']] <-
          lapply(self$`names`, function(x) x$toJSON())
      }

      ScreeningHitDataObject
    },
    fromJSON = function(ScreeningHitDataJson) {
      ScreeningHitDataObject <- jsonlite::fromJSON(ScreeningHitDataJson)
      if (!is.null(ScreeningHitDataObject$`dates_of_birth`)) {
        self$`dates_of_birth` <- ApiClient$new()$deserializeObj(ScreeningHitDataObject$`dates_of_birth`, "array[ScreeningHitDateOfBirthItem]", loadNamespace("plaidr"))
      }
      if (!is.null(ScreeningHitDataObject$`documents`)) {
        self$`documents` <- ApiClient$new()$deserializeObj(ScreeningHitDataObject$`documents`, "array[ScreeningHitDocumentsItems]", loadNamespace("plaidr"))
      }
      if (!is.null(ScreeningHitDataObject$`locations`)) {
        self$`locations` <- ApiClient$new()$deserializeObj(ScreeningHitDataObject$`locations`, "array[GenericScreeningHitLocationItems]", loadNamespace("plaidr"))
      }
      if (!is.null(ScreeningHitDataObject$`names`)) {
        self$`names` <- ApiClient$new()$deserializeObj(ScreeningHitDataObject$`names`, "array[ScreeningHitNamesItems]", loadNamespace("plaidr"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`dates_of_birth`)) {
        sprintf(
        '"dates_of_birth":
        [%s]
',
        paste(sapply(self$`dates_of_birth`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`documents`)) {
        sprintf(
        '"documents":
        [%s]
',
        paste(sapply(self$`documents`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`locations`)) {
        sprintf(
        '"locations":
        [%s]
',
        paste(sapply(self$`locations`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`names`)) {
        sprintf(
        '"names":
        [%s]
',
        paste(sapply(self$`names`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ScreeningHitDataJson) {
      ScreeningHitDataObject <- jsonlite::fromJSON(ScreeningHitDataJson)
      self$`dates_of_birth` <- ApiClient$new()$deserializeObj(ScreeningHitDataObject$`dates_of_birth`, "array[ScreeningHitDateOfBirthItem]", loadNamespace("plaidr"))
      self$`documents` <- ApiClient$new()$deserializeObj(ScreeningHitDataObject$`documents`, "array[ScreeningHitDocumentsItems]", loadNamespace("plaidr"))
      self$`locations` <- ApiClient$new()$deserializeObj(ScreeningHitDataObject$`locations`, "array[GenericScreeningHitLocationItems]", loadNamespace("plaidr"))
      self$`names` <- ApiClient$new()$deserializeObj(ScreeningHitDataObject$`names`, "array[ScreeningHitNamesItems]", loadNamespace("plaidr"))
      self
    }
  )
)
