# The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.146.0
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title SignalReturnReportRequest
#'
#' @description SignalReturnReportRequest Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field client_id ClientID character [optional]
#'
#' @field secret APISecret character [optional]
#'
#' @field client_transaction_id  character 
#'
#' @field return_code  character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
SignalReturnReportRequest <- R6::R6Class(
  'SignalReturnReportRequest',
  public = list(
    `client_id` = NULL,
    `secret` = NULL,
    `client_transaction_id` = NULL,
    `return_code` = NULL,
    initialize = function(
        `client_transaction_id`, `return_code`, `client_id`=NULL, `secret`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`client_transaction_id`)) {
        stopifnot(is.character(`client_transaction_id`), length(`client_transaction_id`) == 1)
        self$`client_transaction_id` <- `client_transaction_id`
      }
      if (!missing(`return_code`)) {
        stopifnot(is.character(`return_code`), length(`return_code`) == 1)
        self$`return_code` <- `return_code`
      }
      if (!is.null(`client_id`)) {
        stopifnot(is.character(`client_id`), length(`client_id`) == 1)
        self$`client_id` <- `client_id`
      }
      if (!is.null(`secret`)) {
        stopifnot(is.character(`secret`), length(`secret`) == 1)
        self$`secret` <- `secret`
      }
    },
    toJSON = function() {
      SignalReturnReportRequestObject <- list()
      if (!is.null(self$`client_id`)) {
        SignalReturnReportRequestObject[['client_id']] <-
          self$`client_id`
      }
      if (!is.null(self$`secret`)) {
        SignalReturnReportRequestObject[['secret']] <-
          self$`secret`
      }
      if (!is.null(self$`client_transaction_id`)) {
        SignalReturnReportRequestObject[['client_transaction_id']] <-
          self$`client_transaction_id`
      }
      if (!is.null(self$`return_code`)) {
        SignalReturnReportRequestObject[['return_code']] <-
          self$`return_code`
      }

      SignalReturnReportRequestObject
    },
    fromJSON = function(SignalReturnReportRequestJson) {
      SignalReturnReportRequestObject <- jsonlite::fromJSON(SignalReturnReportRequestJson)
      if (!is.null(SignalReturnReportRequestObject$`client_id`)) {
        self$`client_id` <- SignalReturnReportRequestObject$`client_id`
      }
      if (!is.null(SignalReturnReportRequestObject$`secret`)) {
        self$`secret` <- SignalReturnReportRequestObject$`secret`
      }
      if (!is.null(SignalReturnReportRequestObject$`client_transaction_id`)) {
        self$`client_transaction_id` <- SignalReturnReportRequestObject$`client_transaction_id`
      }
      if (!is.null(SignalReturnReportRequestObject$`return_code`)) {
        self$`return_code` <- SignalReturnReportRequestObject$`return_code`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`client_id`)) {
        sprintf(
        '"client_id":
          "%s"
                ',
        self$`client_id`
        )},
        if (!is.null(self$`secret`)) {
        sprintf(
        '"secret":
          "%s"
                ',
        self$`secret`
        )},
        if (!is.null(self$`client_transaction_id`)) {
        sprintf(
        '"client_transaction_id":
          "%s"
                ',
        self$`client_transaction_id`
        )},
        if (!is.null(self$`return_code`)) {
        sprintf(
        '"return_code":
          "%s"
                ',
        self$`return_code`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(SignalReturnReportRequestJson) {
      SignalReturnReportRequestObject <- jsonlite::fromJSON(SignalReturnReportRequestJson)
      self$`client_id` <- SignalReturnReportRequestObject$`client_id`
      self$`secret` <- SignalReturnReportRequestObject$`secret`
      self$`client_transaction_id` <- SignalReturnReportRequestObject$`client_transaction_id`
      self$`return_code` <- SignalReturnReportRequestObject$`return_code`
      self
    }
  )
)
