# The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.146.0
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title SignalEvaluateRequest
#'
#' @description SignalEvaluateRequest Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field client_id ClientID character [optional]
#'
#' @field secret APISecret character [optional]
#'
#' @field access_token AccessToken character 
#'
#' @field account_id  character 
#'
#' @field client_transaction_id  character 
#'
#' @field amount  numeric 
#'
#' @field user_present  character [optional]
#'
#' @field client_user_id  character [optional]
#'
#' @field user  \link{SignalUser} [optional]
#'
#' @field device  \link{SignalDevice} [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
SignalEvaluateRequest <- R6::R6Class(
  'SignalEvaluateRequest',
  public = list(
    `client_id` = NULL,
    `secret` = NULL,
    `access_token` = NULL,
    `account_id` = NULL,
    `client_transaction_id` = NULL,
    `amount` = NULL,
    `user_present` = NULL,
    `client_user_id` = NULL,
    `user` = NULL,
    `device` = NULL,
    initialize = function(
        `access_token`, `account_id`, `client_transaction_id`, `amount`, `client_id`=NULL, `secret`=NULL, `user_present`=NULL, `client_user_id`=NULL, `user`=NULL, `device`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`access_token`)) {
        stopifnot(is.character(`access_token`), length(`access_token`) == 1)
        self$`access_token` <- `access_token`
      }
      if (!missing(`account_id`)) {
        stopifnot(is.character(`account_id`), length(`account_id`) == 1)
        self$`account_id` <- `account_id`
      }
      if (!missing(`client_transaction_id`)) {
        stopifnot(is.character(`client_transaction_id`), length(`client_transaction_id`) == 1)
        self$`client_transaction_id` <- `client_transaction_id`
      }
      if (!missing(`amount`)) {
        stopifnot(is.numeric(`amount`), length(`amount`) == 1)
        self$`amount` <- `amount`
      }
      if (!is.null(`client_id`)) {
        stopifnot(is.character(`client_id`), length(`client_id`) == 1)
        self$`client_id` <- `client_id`
      }
      if (!is.null(`secret`)) {
        stopifnot(is.character(`secret`), length(`secret`) == 1)
        self$`secret` <- `secret`
      }
      if (!is.null(`user_present`)) {
        stopifnot(is.logical(`user_present`), length(`user_present`) == 1)
        self$`user_present` <- `user_present`
      }
      if (!is.null(`client_user_id`)) {
        stopifnot(is.character(`client_user_id`), length(`client_user_id`) == 1)
        self$`client_user_id` <- `client_user_id`
      }
      if (!is.null(`user`)) {
        stopifnot(R6::is.R6(`user`))
        self$`user` <- `user`
      }
      if (!is.null(`device`)) {
        stopifnot(R6::is.R6(`device`))
        self$`device` <- `device`
      }
    },
    toJSON = function() {
      SignalEvaluateRequestObject <- list()
      if (!is.null(self$`client_id`)) {
        SignalEvaluateRequestObject[['client_id']] <-
          self$`client_id`
      }
      if (!is.null(self$`secret`)) {
        SignalEvaluateRequestObject[['secret']] <-
          self$`secret`
      }
      if (!is.null(self$`access_token`)) {
        SignalEvaluateRequestObject[['access_token']] <-
          self$`access_token`
      }
      if (!is.null(self$`account_id`)) {
        SignalEvaluateRequestObject[['account_id']] <-
          self$`account_id`
      }
      if (!is.null(self$`client_transaction_id`)) {
        SignalEvaluateRequestObject[['client_transaction_id']] <-
          self$`client_transaction_id`
      }
      if (!is.null(self$`amount`)) {
        SignalEvaluateRequestObject[['amount']] <-
          self$`amount`
      }
      if (!is.null(self$`user_present`)) {
        SignalEvaluateRequestObject[['user_present']] <-
          self$`user_present`
      }
      if (!is.null(self$`client_user_id`)) {
        SignalEvaluateRequestObject[['client_user_id']] <-
          self$`client_user_id`
      }
      if (!is.null(self$`user`)) {
        SignalEvaluateRequestObject[['user']] <-
          self$`user`$toJSON()
      }
      if (!is.null(self$`device`)) {
        SignalEvaluateRequestObject[['device']] <-
          self$`device`$toJSON()
      }

      SignalEvaluateRequestObject
    },
    fromJSON = function(SignalEvaluateRequestJson) {
      SignalEvaluateRequestObject <- jsonlite::fromJSON(SignalEvaluateRequestJson)
      if (!is.null(SignalEvaluateRequestObject$`client_id`)) {
        self$`client_id` <- SignalEvaluateRequestObject$`client_id`
      }
      if (!is.null(SignalEvaluateRequestObject$`secret`)) {
        self$`secret` <- SignalEvaluateRequestObject$`secret`
      }
      if (!is.null(SignalEvaluateRequestObject$`access_token`)) {
        self$`access_token` <- SignalEvaluateRequestObject$`access_token`
      }
      if (!is.null(SignalEvaluateRequestObject$`account_id`)) {
        self$`account_id` <- SignalEvaluateRequestObject$`account_id`
      }
      if (!is.null(SignalEvaluateRequestObject$`client_transaction_id`)) {
        self$`client_transaction_id` <- SignalEvaluateRequestObject$`client_transaction_id`
      }
      if (!is.null(SignalEvaluateRequestObject$`amount`)) {
        self$`amount` <- SignalEvaluateRequestObject$`amount`
      }
      if (!is.null(SignalEvaluateRequestObject$`user_present`)) {
        self$`user_present` <- SignalEvaluateRequestObject$`user_present`
      }
      if (!is.null(SignalEvaluateRequestObject$`client_user_id`)) {
        self$`client_user_id` <- SignalEvaluateRequestObject$`client_user_id`
      }
      if (!is.null(SignalEvaluateRequestObject$`user`)) {
        userObject <- SignalUser$new()
        userObject$fromJSON(jsonlite::toJSON(SignalEvaluateRequestObject$user, auto_unbox = TRUE, digits = NA))
        self$`user` <- userObject
      }
      if (!is.null(SignalEvaluateRequestObject$`device`)) {
        deviceObject <- SignalDevice$new()
        deviceObject$fromJSON(jsonlite::toJSON(SignalEvaluateRequestObject$device, auto_unbox = TRUE, digits = NA))
        self$`device` <- deviceObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`client_id`)) {
        sprintf(
        '"client_id":
          "%s"
                ',
        self$`client_id`
        )},
        if (!is.null(self$`secret`)) {
        sprintf(
        '"secret":
          "%s"
                ',
        self$`secret`
        )},
        if (!is.null(self$`access_token`)) {
        sprintf(
        '"access_token":
          "%s"
                ',
        self$`access_token`
        )},
        if (!is.null(self$`account_id`)) {
        sprintf(
        '"account_id":
          "%s"
                ',
        self$`account_id`
        )},
        if (!is.null(self$`client_transaction_id`)) {
        sprintf(
        '"client_transaction_id":
          "%s"
                ',
        self$`client_transaction_id`
        )},
        if (!is.null(self$`amount`)) {
        sprintf(
        '"amount":
          %d
                ',
        self$`amount`
        )},
        if (!is.null(self$`user_present`)) {
        sprintf(
        '"user_present":
          %s
                ',
        tolower(self$`user_present`)
        )},
        if (!is.null(self$`client_user_id`)) {
        sprintf(
        '"client_user_id":
          "%s"
                ',
        self$`client_user_id`
        )},
        if (!is.null(self$`user`)) {
        sprintf(
        '"user":
        %s
        ',
        jsonlite::toJSON(self$`user`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`device`)) {
        sprintf(
        '"device":
        %s
        ',
        jsonlite::toJSON(self$`device`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(SignalEvaluateRequestJson) {
      SignalEvaluateRequestObject <- jsonlite::fromJSON(SignalEvaluateRequestJson)
      self$`client_id` <- SignalEvaluateRequestObject$`client_id`
      self$`secret` <- SignalEvaluateRequestObject$`secret`
      self$`access_token` <- SignalEvaluateRequestObject$`access_token`
      self$`account_id` <- SignalEvaluateRequestObject$`account_id`
      self$`client_transaction_id` <- SignalEvaluateRequestObject$`client_transaction_id`
      self$`amount` <- SignalEvaluateRequestObject$`amount`
      self$`user_present` <- SignalEvaluateRequestObject$`user_present`
      self$`client_user_id` <- SignalEvaluateRequestObject$`client_user_id`
      self$`user` <- SignalUser$new()$fromJSON(jsonlite::toJSON(SignalEvaluateRequestObject$user, auto_unbox = TRUE, digits = NA))
      self$`device` <- SignalDevice$new()$fromJSON(jsonlite::toJSON(SignalEvaluateRequestObject$device, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)
