# The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.146.0
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title StandaloneCurrencyCodeList
#'
#' @description StandaloneCurrencyCodeList Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field iso_currency_code  character 
#'
#' @field unofficial_currency_code UnofficialCurrencyCodeList character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
StandaloneCurrencyCodeList <- R6::R6Class(
  'StandaloneCurrencyCodeList',
  public = list(
    `iso_currency_code` = NULL,
    `unofficial_currency_code` = NULL,
    initialize = function(
        `iso_currency_code`, `unofficial_currency_code`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`iso_currency_code`)) {
        stopifnot(is.character(`iso_currency_code`), length(`iso_currency_code`) == 1)
        self$`iso_currency_code` <- `iso_currency_code`
      }
      if (!missing(`unofficial_currency_code`)) {
        stopifnot(is.character(`unofficial_currency_code`), length(`unofficial_currency_code`) == 1)
        self$`unofficial_currency_code` <- `unofficial_currency_code`
      }
    },
    toJSON = function() {
      StandaloneCurrencyCodeListObject <- list()
      if (!is.null(self$`iso_currency_code`)) {
        StandaloneCurrencyCodeListObject[['iso_currency_code']] <-
          self$`iso_currency_code`
      }
      if (!is.null(self$`unofficial_currency_code`)) {
        StandaloneCurrencyCodeListObject[['unofficial_currency_code']] <-
          self$`unofficial_currency_code`
      }

      StandaloneCurrencyCodeListObject
    },
    fromJSON = function(StandaloneCurrencyCodeListJson) {
      StandaloneCurrencyCodeListObject <- jsonlite::fromJSON(StandaloneCurrencyCodeListJson)
      if (!is.null(StandaloneCurrencyCodeListObject$`iso_currency_code`)) {
        self$`iso_currency_code` <- StandaloneCurrencyCodeListObject$`iso_currency_code`
      }
      if (!is.null(StandaloneCurrencyCodeListObject$`unofficial_currency_code`)) {
        self$`unofficial_currency_code` <- StandaloneCurrencyCodeListObject$`unofficial_currency_code`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`iso_currency_code`)) {
        sprintf(
        '"iso_currency_code":
          "%s"
                ',
        self$`iso_currency_code`
        )},
        if (!is.null(self$`unofficial_currency_code`)) {
        sprintf(
        '"unofficial_currency_code":
          "%s"
                ',
        self$`unofficial_currency_code`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(StandaloneCurrencyCodeListJson) {
      StandaloneCurrencyCodeListObject <- jsonlite::fromJSON(StandaloneCurrencyCodeListJson)
      self$`iso_currency_code` <- StandaloneCurrencyCodeListObject$`iso_currency_code`
      self$`unofficial_currency_code` <- StandaloneCurrencyCodeListObject$`unofficial_currency_code`
      self
    }
  )
)
