# The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.146.0
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title StudentLoanRepaymentModel
#'
#' @description StudentLoanRepaymentModel Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field type  character 
#'
#' @field non_repayment_months  numeric 
#'
#' @field repayment_months  numeric 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
StudentLoanRepaymentModel <- R6::R6Class(
  'StudentLoanRepaymentModel',
  public = list(
    `type` = NULL,
    `non_repayment_months` = NULL,
    `repayment_months` = NULL,
    initialize = function(
        `type`, `non_repayment_months`, `repayment_months`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`type`)) {
        stopifnot(is.character(`type`), length(`type`) == 1)
        self$`type` <- `type`
      }
      if (!missing(`non_repayment_months`)) {
        self$`non_repayment_months` <- `non_repayment_months`
      }
      if (!missing(`repayment_months`)) {
        self$`repayment_months` <- `repayment_months`
      }
    },
    toJSON = function() {
      StudentLoanRepaymentModelObject <- list()
      if (!is.null(self$`type`)) {
        StudentLoanRepaymentModelObject[['type']] <-
          self$`type`
      }
      if (!is.null(self$`non_repayment_months`)) {
        StudentLoanRepaymentModelObject[['non_repayment_months']] <-
          self$`non_repayment_months`
      }
      if (!is.null(self$`repayment_months`)) {
        StudentLoanRepaymentModelObject[['repayment_months']] <-
          self$`repayment_months`
      }

      StudentLoanRepaymentModelObject
    },
    fromJSON = function(StudentLoanRepaymentModelJson) {
      StudentLoanRepaymentModelObject <- jsonlite::fromJSON(StudentLoanRepaymentModelJson)
      if (!is.null(StudentLoanRepaymentModelObject$`type`)) {
        self$`type` <- StudentLoanRepaymentModelObject$`type`
      }
      if (!is.null(StudentLoanRepaymentModelObject$`non_repayment_months`)) {
        self$`non_repayment_months` <- StudentLoanRepaymentModelObject$`non_repayment_months`
      }
      if (!is.null(StudentLoanRepaymentModelObject$`repayment_months`)) {
        self$`repayment_months` <- StudentLoanRepaymentModelObject$`repayment_months`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`type`)) {
        sprintf(
        '"type":
          "%s"
                ',
        self$`type`
        )},
        if (!is.null(self$`non_repayment_months`)) {
        sprintf(
        '"non_repayment_months":
          %d
                ',
        self$`non_repayment_months`
        )},
        if (!is.null(self$`repayment_months`)) {
        sprintf(
        '"repayment_months":
          %d
                ',
        self$`repayment_months`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(StudentLoanRepaymentModelJson) {
      StudentLoanRepaymentModelObject <- jsonlite::fromJSON(StudentLoanRepaymentModelJson)
      self$`type` <- StudentLoanRepaymentModelObject$`type`
      self$`non_repayment_months` <- StudentLoanRepaymentModelObject$`non_repayment_months`
      self$`repayment_months` <- StudentLoanRepaymentModelObject$`repayment_months`
      self
    }
  )
)
