# The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.146.0
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title TaxpayerID
#'
#' @description TaxpayerID Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field id_type  character [optional]
#'
#' @field id_mask  character [optional]
#'
#' @field last_4_digits  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
TaxpayerID <- R6::R6Class(
  'TaxpayerID',
  public = list(
    `id_type` = NULL,
    `id_mask` = NULL,
    `last_4_digits` = NULL,
    initialize = function(
        `id_type`=NULL, `id_mask`=NULL, `last_4_digits`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`id_type`)) {
        stopifnot(is.character(`id_type`), length(`id_type`) == 1)
        self$`id_type` <- `id_type`
      }
      if (!is.null(`id_mask`)) {
        stopifnot(is.character(`id_mask`), length(`id_mask`) == 1)
        self$`id_mask` <- `id_mask`
      }
      if (!is.null(`last_4_digits`)) {
        stopifnot(is.character(`last_4_digits`), length(`last_4_digits`) == 1)
        self$`last_4_digits` <- `last_4_digits`
      }
    },
    toJSON = function() {
      TaxpayerIDObject <- list()
      if (!is.null(self$`id_type`)) {
        TaxpayerIDObject[['id_type']] <-
          self$`id_type`
      }
      if (!is.null(self$`id_mask`)) {
        TaxpayerIDObject[['id_mask']] <-
          self$`id_mask`
      }
      if (!is.null(self$`last_4_digits`)) {
        TaxpayerIDObject[['last_4_digits']] <-
          self$`last_4_digits`
      }

      TaxpayerIDObject
    },
    fromJSON = function(TaxpayerIDJson) {
      TaxpayerIDObject <- jsonlite::fromJSON(TaxpayerIDJson)
      if (!is.null(TaxpayerIDObject$`id_type`)) {
        self$`id_type` <- TaxpayerIDObject$`id_type`
      }
      if (!is.null(TaxpayerIDObject$`id_mask`)) {
        self$`id_mask` <- TaxpayerIDObject$`id_mask`
      }
      if (!is.null(TaxpayerIDObject$`last_4_digits`)) {
        self$`last_4_digits` <- TaxpayerIDObject$`last_4_digits`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id_type`)) {
        sprintf(
        '"id_type":
          "%s"
                ',
        self$`id_type`
        )},
        if (!is.null(self$`id_mask`)) {
        sprintf(
        '"id_mask":
          "%s"
                ',
        self$`id_mask`
        )},
        if (!is.null(self$`last_4_digits`)) {
        sprintf(
        '"last_4_digits":
          "%s"
                ',
        self$`last_4_digits`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(TaxpayerIDJson) {
      TaxpayerIDObject <- jsonlite::fromJSON(TaxpayerIDJson)
      self$`id_type` <- TaxpayerIDObject$`id_type`
      self$`id_mask` <- TaxpayerIDObject$`id_mask`
      self$`last_4_digits` <- TaxpayerIDObject$`last_4_digits`
      self
    }
  )
)
