# The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.146.0
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title TransferEvent
#'
#' @description TransferEvent Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field event_id  integer 
#'
#' @field timestamp  character 
#'
#' @field event_type  \link{TransferEventType} 
#'
#' @field account_id  character 
#'
#' @field transfer_id TransferID character 
#'
#' @field origination_account_id  character 
#'
#' @field transfer_type  \link{TransferType} 
#'
#' @field transfer_amount TransferAmount character 
#'
#' @field failure_reason  \link{TransferFailure} 
#'
#' @field sweep_id TransferSweepID character 
#'
#' @field sweep_amount TransferSweepAmount character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
TransferEvent <- R6::R6Class(
  'TransferEvent',
  public = list(
    `event_id` = NULL,
    `timestamp` = NULL,
    `event_type` = NULL,
    `account_id` = NULL,
    `transfer_id` = NULL,
    `origination_account_id` = NULL,
    `transfer_type` = NULL,
    `transfer_amount` = NULL,
    `failure_reason` = NULL,
    `sweep_id` = NULL,
    `sweep_amount` = NULL,
    initialize = function(
        `event_id`, `timestamp`, `event_type`, `account_id`, `transfer_id`, `origination_account_id`, `transfer_type`, `transfer_amount`, `failure_reason`, `sweep_id`, `sweep_amount`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`event_id`)) {
        stopifnot(is.numeric(`event_id`), length(`event_id`) == 1)
        self$`event_id` <- `event_id`
      }
      if (!missing(`timestamp`)) {
        stopifnot(is.character(`timestamp`), length(`timestamp`) == 1)
        self$`timestamp` <- `timestamp`
      }
      if (!missing(`event_type`)) {
        stopifnot(R6::is.R6(`event_type`))
        self$`event_type` <- `event_type`
      }
      if (!missing(`account_id`)) {
        stopifnot(is.character(`account_id`), length(`account_id`) == 1)
        self$`account_id` <- `account_id`
      }
      if (!missing(`transfer_id`)) {
        stopifnot(is.character(`transfer_id`), length(`transfer_id`) == 1)
        self$`transfer_id` <- `transfer_id`
      }
      if (!missing(`origination_account_id`)) {
        stopifnot(is.character(`origination_account_id`), length(`origination_account_id`) == 1)
        self$`origination_account_id` <- `origination_account_id`
      }
      if (!missing(`transfer_type`)) {
        stopifnot(R6::is.R6(`transfer_type`))
        self$`transfer_type` <- `transfer_type`
      }
      if (!missing(`transfer_amount`)) {
        stopifnot(is.character(`transfer_amount`), length(`transfer_amount`) == 1)
        self$`transfer_amount` <- `transfer_amount`
      }
      if (!missing(`failure_reason`)) {
        stopifnot(R6::is.R6(`failure_reason`))
        self$`failure_reason` <- `failure_reason`
      }
      if (!missing(`sweep_id`)) {
        stopifnot(is.character(`sweep_id`), length(`sweep_id`) == 1)
        self$`sweep_id` <- `sweep_id`
      }
      if (!missing(`sweep_amount`)) {
        stopifnot(is.character(`sweep_amount`), length(`sweep_amount`) == 1)
        self$`sweep_amount` <- `sweep_amount`
      }
    },
    toJSON = function() {
      TransferEventObject <- list()
      if (!is.null(self$`event_id`)) {
        TransferEventObject[['event_id']] <-
          self$`event_id`
      }
      if (!is.null(self$`timestamp`)) {
        TransferEventObject[['timestamp']] <-
          self$`timestamp`
      }
      if (!is.null(self$`event_type`)) {
        TransferEventObject[['event_type']] <-
          self$`event_type`$toJSON()
      }
      if (!is.null(self$`account_id`)) {
        TransferEventObject[['account_id']] <-
          self$`account_id`
      }
      if (!is.null(self$`transfer_id`)) {
        TransferEventObject[['transfer_id']] <-
          self$`transfer_id`
      }
      if (!is.null(self$`origination_account_id`)) {
        TransferEventObject[['origination_account_id']] <-
          self$`origination_account_id`
      }
      if (!is.null(self$`transfer_type`)) {
        TransferEventObject[['transfer_type']] <-
          self$`transfer_type`$toJSON()
      }
      if (!is.null(self$`transfer_amount`)) {
        TransferEventObject[['transfer_amount']] <-
          self$`transfer_amount`
      }
      if (!is.null(self$`failure_reason`)) {
        TransferEventObject[['failure_reason']] <-
          self$`failure_reason`$toJSON()
      }
      if (!is.null(self$`sweep_id`)) {
        TransferEventObject[['sweep_id']] <-
          self$`sweep_id`
      }
      if (!is.null(self$`sweep_amount`)) {
        TransferEventObject[['sweep_amount']] <-
          self$`sweep_amount`
      }

      TransferEventObject
    },
    fromJSON = function(TransferEventJson) {
      TransferEventObject <- jsonlite::fromJSON(TransferEventJson)
      if (!is.null(TransferEventObject$`event_id`)) {
        self$`event_id` <- TransferEventObject$`event_id`
      }
      if (!is.null(TransferEventObject$`timestamp`)) {
        self$`timestamp` <- TransferEventObject$`timestamp`
      }
      if (!is.null(TransferEventObject$`event_type`)) {
        event_typeObject <- TransferEventType$new()
        event_typeObject$fromJSON(jsonlite::toJSON(TransferEventObject$event_type, auto_unbox = TRUE, digits = NA))
        self$`event_type` <- event_typeObject
      }
      if (!is.null(TransferEventObject$`account_id`)) {
        self$`account_id` <- TransferEventObject$`account_id`
      }
      if (!is.null(TransferEventObject$`transfer_id`)) {
        self$`transfer_id` <- TransferEventObject$`transfer_id`
      }
      if (!is.null(TransferEventObject$`origination_account_id`)) {
        self$`origination_account_id` <- TransferEventObject$`origination_account_id`
      }
      if (!is.null(TransferEventObject$`transfer_type`)) {
        transfer_typeObject <- TransferType$new()
        transfer_typeObject$fromJSON(jsonlite::toJSON(TransferEventObject$transfer_type, auto_unbox = TRUE, digits = NA))
        self$`transfer_type` <- transfer_typeObject
      }
      if (!is.null(TransferEventObject$`transfer_amount`)) {
        self$`transfer_amount` <- TransferEventObject$`transfer_amount`
      }
      if (!is.null(TransferEventObject$`failure_reason`)) {
        failure_reasonObject <- TransferFailure$new()
        failure_reasonObject$fromJSON(jsonlite::toJSON(TransferEventObject$failure_reason, auto_unbox = TRUE, digits = NA))
        self$`failure_reason` <- failure_reasonObject
      }
      if (!is.null(TransferEventObject$`sweep_id`)) {
        self$`sweep_id` <- TransferEventObject$`sweep_id`
      }
      if (!is.null(TransferEventObject$`sweep_amount`)) {
        self$`sweep_amount` <- TransferEventObject$`sweep_amount`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`event_id`)) {
        sprintf(
        '"event_id":
          %d
                ',
        self$`event_id`
        )},
        if (!is.null(self$`timestamp`)) {
        sprintf(
        '"timestamp":
          "%s"
                ',
        self$`timestamp`
        )},
        if (!is.null(self$`event_type`)) {
        sprintf(
        '"event_type":
        %s
        ',
        jsonlite::toJSON(self$`event_type`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`account_id`)) {
        sprintf(
        '"account_id":
          "%s"
                ',
        self$`account_id`
        )},
        if (!is.null(self$`transfer_id`)) {
        sprintf(
        '"transfer_id":
          "%s"
                ',
        self$`transfer_id`
        )},
        if (!is.null(self$`origination_account_id`)) {
        sprintf(
        '"origination_account_id":
          "%s"
                ',
        self$`origination_account_id`
        )},
        if (!is.null(self$`transfer_type`)) {
        sprintf(
        '"transfer_type":
        %s
        ',
        jsonlite::toJSON(self$`transfer_type`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`transfer_amount`)) {
        sprintf(
        '"transfer_amount":
          "%s"
                ',
        self$`transfer_amount`
        )},
        if (!is.null(self$`failure_reason`)) {
        sprintf(
        '"failure_reason":
        %s
        ',
        jsonlite::toJSON(self$`failure_reason`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`sweep_id`)) {
        sprintf(
        '"sweep_id":
          "%s"
                ',
        self$`sweep_id`
        )},
        if (!is.null(self$`sweep_amount`)) {
        sprintf(
        '"sweep_amount":
          "%s"
                ',
        self$`sweep_amount`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(TransferEventJson) {
      TransferEventObject <- jsonlite::fromJSON(TransferEventJson)
      self$`event_id` <- TransferEventObject$`event_id`
      self$`timestamp` <- TransferEventObject$`timestamp`
      self$`event_type` <- TransferEventType$new()$fromJSON(jsonlite::toJSON(TransferEventObject$event_type, auto_unbox = TRUE, digits = NA))
      self$`account_id` <- TransferEventObject$`account_id`
      self$`transfer_id` <- TransferEventObject$`transfer_id`
      self$`origination_account_id` <- TransferEventObject$`origination_account_id`
      self$`transfer_type` <- TransferType$new()$fromJSON(jsonlite::toJSON(TransferEventObject$transfer_type, auto_unbox = TRUE, digits = NA))
      self$`transfer_amount` <- TransferEventObject$`transfer_amount`
      self$`failure_reason` <- TransferFailure$new()$fromJSON(jsonlite::toJSON(TransferEventObject$failure_reason, auto_unbox = TRUE, digits = NA))
      self$`sweep_id` <- TransferEventObject$`sweep_id`
      self$`sweep_amount` <- TransferEventObject$`sweep_amount`
      self
    }
  )
)
