# The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.146.0
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title TransferAuthorizationCreateRequest
#'
#' @description TransferAuthorizationCreateRequest Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field client_id ClientID character [optional]
#'
#' @field secret APISecret character [optional]
#'
#' @field access_token  character 
#'
#' @field account_id  character 
#'
#' @field type  \link{TransferType} 
#'
#' @field network  \link{TransferNetwork} 
#'
#' @field amount TransferAmount character 
#'
#' @field ach_class  \link{ACHClass} 
#'
#' @field user  \link{TransferUserInRequest} 
#'
#' @field device  \link{TransferAuthorizationDevice} [optional]
#'
#' @field origination_account_id  character [optional]
#'
#' @field iso_currency_code  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
TransferAuthorizationCreateRequest <- R6::R6Class(
  'TransferAuthorizationCreateRequest',
  public = list(
    `client_id` = NULL,
    `secret` = NULL,
    `access_token` = NULL,
    `account_id` = NULL,
    `type` = NULL,
    `network` = NULL,
    `amount` = NULL,
    `ach_class` = NULL,
    `user` = NULL,
    `device` = NULL,
    `origination_account_id` = NULL,
    `iso_currency_code` = NULL,
    initialize = function(
        `access_token`, `account_id`, `type`, `network`, `amount`, `ach_class`, `user`, `client_id`=NULL, `secret`=NULL, `device`=NULL, `origination_account_id`=NULL, `iso_currency_code`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`access_token`)) {
        stopifnot(is.character(`access_token`), length(`access_token`) == 1)
        self$`access_token` <- `access_token`
      }
      if (!missing(`account_id`)) {
        stopifnot(is.character(`account_id`), length(`account_id`) == 1)
        self$`account_id` <- `account_id`
      }
      if (!missing(`type`)) {
        stopifnot(R6::is.R6(`type`))
        self$`type` <- `type`
      }
      if (!missing(`network`)) {
        stopifnot(R6::is.R6(`network`))
        self$`network` <- `network`
      }
      if (!missing(`amount`)) {
        stopifnot(is.character(`amount`), length(`amount`) == 1)
        self$`amount` <- `amount`
      }
      if (!missing(`ach_class`)) {
        stopifnot(R6::is.R6(`ach_class`))
        self$`ach_class` <- `ach_class`
      }
      if (!missing(`user`)) {
        stopifnot(R6::is.R6(`user`))
        self$`user` <- `user`
      }
      if (!is.null(`client_id`)) {
        stopifnot(is.character(`client_id`), length(`client_id`) == 1)
        self$`client_id` <- `client_id`
      }
      if (!is.null(`secret`)) {
        stopifnot(is.character(`secret`), length(`secret`) == 1)
        self$`secret` <- `secret`
      }
      if (!is.null(`device`)) {
        stopifnot(R6::is.R6(`device`))
        self$`device` <- `device`
      }
      if (!is.null(`origination_account_id`)) {
        stopifnot(is.character(`origination_account_id`), length(`origination_account_id`) == 1)
        self$`origination_account_id` <- `origination_account_id`
      }
      if (!is.null(`iso_currency_code`)) {
        stopifnot(is.character(`iso_currency_code`), length(`iso_currency_code`) == 1)
        self$`iso_currency_code` <- `iso_currency_code`
      }
    },
    toJSON = function() {
      TransferAuthorizationCreateRequestObject <- list()
      if (!is.null(self$`client_id`)) {
        TransferAuthorizationCreateRequestObject[['client_id']] <-
          self$`client_id`
      }
      if (!is.null(self$`secret`)) {
        TransferAuthorizationCreateRequestObject[['secret']] <-
          self$`secret`
      }
      if (!is.null(self$`access_token`)) {
        TransferAuthorizationCreateRequestObject[['access_token']] <-
          self$`access_token`
      }
      if (!is.null(self$`account_id`)) {
        TransferAuthorizationCreateRequestObject[['account_id']] <-
          self$`account_id`
      }
      if (!is.null(self$`type`)) {
        TransferAuthorizationCreateRequestObject[['type']] <-
          self$`type`$toJSON()
      }
      if (!is.null(self$`network`)) {
        TransferAuthorizationCreateRequestObject[['network']] <-
          self$`network`$toJSON()
      }
      if (!is.null(self$`amount`)) {
        TransferAuthorizationCreateRequestObject[['amount']] <-
          self$`amount`
      }
      if (!is.null(self$`ach_class`)) {
        TransferAuthorizationCreateRequestObject[['ach_class']] <-
          self$`ach_class`$toJSON()
      }
      if (!is.null(self$`user`)) {
        TransferAuthorizationCreateRequestObject[['user']] <-
          self$`user`$toJSON()
      }
      if (!is.null(self$`device`)) {
        TransferAuthorizationCreateRequestObject[['device']] <-
          self$`device`$toJSON()
      }
      if (!is.null(self$`origination_account_id`)) {
        TransferAuthorizationCreateRequestObject[['origination_account_id']] <-
          self$`origination_account_id`
      }
      if (!is.null(self$`iso_currency_code`)) {
        TransferAuthorizationCreateRequestObject[['iso_currency_code']] <-
          self$`iso_currency_code`
      }

      TransferAuthorizationCreateRequestObject
    },
    fromJSON = function(TransferAuthorizationCreateRequestJson) {
      TransferAuthorizationCreateRequestObject <- jsonlite::fromJSON(TransferAuthorizationCreateRequestJson)
      if (!is.null(TransferAuthorizationCreateRequestObject$`client_id`)) {
        self$`client_id` <- TransferAuthorizationCreateRequestObject$`client_id`
      }
      if (!is.null(TransferAuthorizationCreateRequestObject$`secret`)) {
        self$`secret` <- TransferAuthorizationCreateRequestObject$`secret`
      }
      if (!is.null(TransferAuthorizationCreateRequestObject$`access_token`)) {
        self$`access_token` <- TransferAuthorizationCreateRequestObject$`access_token`
      }
      if (!is.null(TransferAuthorizationCreateRequestObject$`account_id`)) {
        self$`account_id` <- TransferAuthorizationCreateRequestObject$`account_id`
      }
      if (!is.null(TransferAuthorizationCreateRequestObject$`type`)) {
        typeObject <- TransferType$new()
        typeObject$fromJSON(jsonlite::toJSON(TransferAuthorizationCreateRequestObject$type, auto_unbox = TRUE, digits = NA))
        self$`type` <- typeObject
      }
      if (!is.null(TransferAuthorizationCreateRequestObject$`network`)) {
        networkObject <- TransferNetwork$new()
        networkObject$fromJSON(jsonlite::toJSON(TransferAuthorizationCreateRequestObject$network, auto_unbox = TRUE, digits = NA))
        self$`network` <- networkObject
      }
      if (!is.null(TransferAuthorizationCreateRequestObject$`amount`)) {
        self$`amount` <- TransferAuthorizationCreateRequestObject$`amount`
      }
      if (!is.null(TransferAuthorizationCreateRequestObject$`ach_class`)) {
        ach_classObject <- ACHClass$new()
        ach_classObject$fromJSON(jsonlite::toJSON(TransferAuthorizationCreateRequestObject$ach_class, auto_unbox = TRUE, digits = NA))
        self$`ach_class` <- ach_classObject
      }
      if (!is.null(TransferAuthorizationCreateRequestObject$`user`)) {
        userObject <- TransferUserInRequest$new()
        userObject$fromJSON(jsonlite::toJSON(TransferAuthorizationCreateRequestObject$user, auto_unbox = TRUE, digits = NA))
        self$`user` <- userObject
      }
      if (!is.null(TransferAuthorizationCreateRequestObject$`device`)) {
        deviceObject <- TransferAuthorizationDevice$new()
        deviceObject$fromJSON(jsonlite::toJSON(TransferAuthorizationCreateRequestObject$device, auto_unbox = TRUE, digits = NA))
        self$`device` <- deviceObject
      }
      if (!is.null(TransferAuthorizationCreateRequestObject$`origination_account_id`)) {
        self$`origination_account_id` <- TransferAuthorizationCreateRequestObject$`origination_account_id`
      }
      if (!is.null(TransferAuthorizationCreateRequestObject$`iso_currency_code`)) {
        self$`iso_currency_code` <- TransferAuthorizationCreateRequestObject$`iso_currency_code`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`client_id`)) {
        sprintf(
        '"client_id":
          "%s"
                ',
        self$`client_id`
        )},
        if (!is.null(self$`secret`)) {
        sprintf(
        '"secret":
          "%s"
                ',
        self$`secret`
        )},
        if (!is.null(self$`access_token`)) {
        sprintf(
        '"access_token":
          "%s"
                ',
        self$`access_token`
        )},
        if (!is.null(self$`account_id`)) {
        sprintf(
        '"account_id":
          "%s"
                ',
        self$`account_id`
        )},
        if (!is.null(self$`type`)) {
        sprintf(
        '"type":
        %s
        ',
        jsonlite::toJSON(self$`type`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`network`)) {
        sprintf(
        '"network":
        %s
        ',
        jsonlite::toJSON(self$`network`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`amount`)) {
        sprintf(
        '"amount":
          "%s"
                ',
        self$`amount`
        )},
        if (!is.null(self$`ach_class`)) {
        sprintf(
        '"ach_class":
        %s
        ',
        jsonlite::toJSON(self$`ach_class`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`user`)) {
        sprintf(
        '"user":
        %s
        ',
        jsonlite::toJSON(self$`user`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`device`)) {
        sprintf(
        '"device":
        %s
        ',
        jsonlite::toJSON(self$`device`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`origination_account_id`)) {
        sprintf(
        '"origination_account_id":
          "%s"
                ',
        self$`origination_account_id`
        )},
        if (!is.null(self$`iso_currency_code`)) {
        sprintf(
        '"iso_currency_code":
          "%s"
                ',
        self$`iso_currency_code`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(TransferAuthorizationCreateRequestJson) {
      TransferAuthorizationCreateRequestObject <- jsonlite::fromJSON(TransferAuthorizationCreateRequestJson)
      self$`client_id` <- TransferAuthorizationCreateRequestObject$`client_id`
      self$`secret` <- TransferAuthorizationCreateRequestObject$`secret`
      self$`access_token` <- TransferAuthorizationCreateRequestObject$`access_token`
      self$`account_id` <- TransferAuthorizationCreateRequestObject$`account_id`
      self$`type` <- TransferType$new()$fromJSON(jsonlite::toJSON(TransferAuthorizationCreateRequestObject$type, auto_unbox = TRUE, digits = NA))
      self$`network` <- TransferNetwork$new()$fromJSON(jsonlite::toJSON(TransferAuthorizationCreateRequestObject$network, auto_unbox = TRUE, digits = NA))
      self$`amount` <- TransferAuthorizationCreateRequestObject$`amount`
      self$`ach_class` <- ACHClass$new()$fromJSON(jsonlite::toJSON(TransferAuthorizationCreateRequestObject$ach_class, auto_unbox = TRUE, digits = NA))
      self$`user` <- TransferUserInRequest$new()$fromJSON(jsonlite::toJSON(TransferAuthorizationCreateRequestObject$user, auto_unbox = TRUE, digits = NA))
      self$`device` <- TransferAuthorizationDevice$new()$fromJSON(jsonlite::toJSON(TransferAuthorizationCreateRequestObject$device, auto_unbox = TRUE, digits = NA))
      self$`origination_account_id` <- TransferAuthorizationCreateRequestObject$`origination_account_id`
      self$`iso_currency_code` <- TransferAuthorizationCreateRequestObject$`iso_currency_code`
      self
    }
  )
)
