# The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.146.0
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title TransferAuthorizationProposedTransfer
#'
#' @description TransferAuthorizationProposedTransfer Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field ach_class  \link{ACHClass} 
#'
#' @field account_id  character 
#'
#' @field type  \link{TransferType} 
#'
#' @field user  \link{TransferUserInResponse} 
#'
#' @field amount TransferAmount character 
#'
#' @field network  character 
#'
#' @field origination_account_id  character 
#'
#' @field iso_currency_code  character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
TransferAuthorizationProposedTransfer <- R6::R6Class(
  'TransferAuthorizationProposedTransfer',
  public = list(
    `ach_class` = NULL,
    `account_id` = NULL,
    `type` = NULL,
    `user` = NULL,
    `amount` = NULL,
    `network` = NULL,
    `origination_account_id` = NULL,
    `iso_currency_code` = NULL,
    initialize = function(
        `ach_class`, `account_id`, `type`, `user`, `amount`, `network`, `origination_account_id`, `iso_currency_code`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`ach_class`)) {
        stopifnot(R6::is.R6(`ach_class`))
        self$`ach_class` <- `ach_class`
      }
      if (!missing(`account_id`)) {
        stopifnot(is.character(`account_id`), length(`account_id`) == 1)
        self$`account_id` <- `account_id`
      }
      if (!missing(`type`)) {
        stopifnot(R6::is.R6(`type`))
        self$`type` <- `type`
      }
      if (!missing(`user`)) {
        stopifnot(R6::is.R6(`user`))
        self$`user` <- `user`
      }
      if (!missing(`amount`)) {
        stopifnot(is.character(`amount`), length(`amount`) == 1)
        self$`amount` <- `amount`
      }
      if (!missing(`network`)) {
        stopifnot(is.character(`network`), length(`network`) == 1)
        self$`network` <- `network`
      }
      if (!missing(`origination_account_id`)) {
        stopifnot(is.character(`origination_account_id`), length(`origination_account_id`) == 1)
        self$`origination_account_id` <- `origination_account_id`
      }
      if (!missing(`iso_currency_code`)) {
        stopifnot(is.character(`iso_currency_code`), length(`iso_currency_code`) == 1)
        self$`iso_currency_code` <- `iso_currency_code`
      }
    },
    toJSON = function() {
      TransferAuthorizationProposedTransferObject <- list()
      if (!is.null(self$`ach_class`)) {
        TransferAuthorizationProposedTransferObject[['ach_class']] <-
          self$`ach_class`$toJSON()
      }
      if (!is.null(self$`account_id`)) {
        TransferAuthorizationProposedTransferObject[['account_id']] <-
          self$`account_id`
      }
      if (!is.null(self$`type`)) {
        TransferAuthorizationProposedTransferObject[['type']] <-
          self$`type`$toJSON()
      }
      if (!is.null(self$`user`)) {
        TransferAuthorizationProposedTransferObject[['user']] <-
          self$`user`$toJSON()
      }
      if (!is.null(self$`amount`)) {
        TransferAuthorizationProposedTransferObject[['amount']] <-
          self$`amount`
      }
      if (!is.null(self$`network`)) {
        TransferAuthorizationProposedTransferObject[['network']] <-
          self$`network`
      }
      if (!is.null(self$`origination_account_id`)) {
        TransferAuthorizationProposedTransferObject[['origination_account_id']] <-
          self$`origination_account_id`
      }
      if (!is.null(self$`iso_currency_code`)) {
        TransferAuthorizationProposedTransferObject[['iso_currency_code']] <-
          self$`iso_currency_code`
      }

      TransferAuthorizationProposedTransferObject
    },
    fromJSON = function(TransferAuthorizationProposedTransferJson) {
      TransferAuthorizationProposedTransferObject <- jsonlite::fromJSON(TransferAuthorizationProposedTransferJson)
      if (!is.null(TransferAuthorizationProposedTransferObject$`ach_class`)) {
        ach_classObject <- ACHClass$new()
        ach_classObject$fromJSON(jsonlite::toJSON(TransferAuthorizationProposedTransferObject$ach_class, auto_unbox = TRUE, digits = NA))
        self$`ach_class` <- ach_classObject
      }
      if (!is.null(TransferAuthorizationProposedTransferObject$`account_id`)) {
        self$`account_id` <- TransferAuthorizationProposedTransferObject$`account_id`
      }
      if (!is.null(TransferAuthorizationProposedTransferObject$`type`)) {
        typeObject <- TransferType$new()
        typeObject$fromJSON(jsonlite::toJSON(TransferAuthorizationProposedTransferObject$type, auto_unbox = TRUE, digits = NA))
        self$`type` <- typeObject
      }
      if (!is.null(TransferAuthorizationProposedTransferObject$`user`)) {
        userObject <- TransferUserInResponse$new()
        userObject$fromJSON(jsonlite::toJSON(TransferAuthorizationProposedTransferObject$user, auto_unbox = TRUE, digits = NA))
        self$`user` <- userObject
      }
      if (!is.null(TransferAuthorizationProposedTransferObject$`amount`)) {
        self$`amount` <- TransferAuthorizationProposedTransferObject$`amount`
      }
      if (!is.null(TransferAuthorizationProposedTransferObject$`network`)) {
        self$`network` <- TransferAuthorizationProposedTransferObject$`network`
      }
      if (!is.null(TransferAuthorizationProposedTransferObject$`origination_account_id`)) {
        self$`origination_account_id` <- TransferAuthorizationProposedTransferObject$`origination_account_id`
      }
      if (!is.null(TransferAuthorizationProposedTransferObject$`iso_currency_code`)) {
        self$`iso_currency_code` <- TransferAuthorizationProposedTransferObject$`iso_currency_code`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`ach_class`)) {
        sprintf(
        '"ach_class":
        %s
        ',
        jsonlite::toJSON(self$`ach_class`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`account_id`)) {
        sprintf(
        '"account_id":
          "%s"
                ',
        self$`account_id`
        )},
        if (!is.null(self$`type`)) {
        sprintf(
        '"type":
        %s
        ',
        jsonlite::toJSON(self$`type`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`user`)) {
        sprintf(
        '"user":
        %s
        ',
        jsonlite::toJSON(self$`user`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`amount`)) {
        sprintf(
        '"amount":
          "%s"
                ',
        self$`amount`
        )},
        if (!is.null(self$`network`)) {
        sprintf(
        '"network":
          "%s"
                ',
        self$`network`
        )},
        if (!is.null(self$`origination_account_id`)) {
        sprintf(
        '"origination_account_id":
          "%s"
                ',
        self$`origination_account_id`
        )},
        if (!is.null(self$`iso_currency_code`)) {
        sprintf(
        '"iso_currency_code":
          "%s"
                ',
        self$`iso_currency_code`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(TransferAuthorizationProposedTransferJson) {
      TransferAuthorizationProposedTransferObject <- jsonlite::fromJSON(TransferAuthorizationProposedTransferJson)
      self$`ach_class` <- ACHClass$new()$fromJSON(jsonlite::toJSON(TransferAuthorizationProposedTransferObject$ach_class, auto_unbox = TRUE, digits = NA))
      self$`account_id` <- TransferAuthorizationProposedTransferObject$`account_id`
      self$`type` <- TransferType$new()$fromJSON(jsonlite::toJSON(TransferAuthorizationProposedTransferObject$type, auto_unbox = TRUE, digits = NA))
      self$`user` <- TransferUserInResponse$new()$fromJSON(jsonlite::toJSON(TransferAuthorizationProposedTransferObject$user, auto_unbox = TRUE, digits = NA))
      self$`amount` <- TransferAuthorizationProposedTransferObject$`amount`
      self$`network` <- TransferAuthorizationProposedTransferObject$`network`
      self$`origination_account_id` <- TransferAuthorizationProposedTransferObject$`origination_account_id`
      self$`iso_currency_code` <- TransferAuthorizationProposedTransferObject$`iso_currency_code`
      self
    }
  )
)
