# The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.146.0
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Transfer
#'
#' @description Transfer Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field id TransferID character 
#'
#' @field ach_class  \link{ACHClass} 
#'
#' @field account_id  character 
#'
#' @field type  \link{TransferType} 
#'
#' @field user  \link{TransferUserInResponse} 
#'
#' @field amount TransferAmount character 
#'
#' @field description  character 
#'
#' @field created  character 
#'
#' @field status  \link{TransferStatus} 
#'
#' @field sweep_status  \link{TransferSweepStatus} [optional]
#'
#' @field network  \link{TransferNetwork} 
#'
#' @field cancellable  character 
#'
#' @field failure_reason  \link{TransferFailure} 
#'
#' @field metadata TransferMetadata named list( character ) 
#'
#' @field origination_account_id  character 
#'
#' @field guarantee_decision  \link{TransferAuthorizationGuaranteeDecision} 
#'
#' @field guarantee_decision_rationale  \link{TransferAuthorizationGuaranteeDecisionRationale} 
#'
#' @field iso_currency_code  character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Transfer <- R6::R6Class(
  'Transfer',
  public = list(
    `id` = NULL,
    `ach_class` = NULL,
    `account_id` = NULL,
    `type` = NULL,
    `user` = NULL,
    `amount` = NULL,
    `description` = NULL,
    `created` = NULL,
    `status` = NULL,
    `sweep_status` = NULL,
    `network` = NULL,
    `cancellable` = NULL,
    `failure_reason` = NULL,
    `metadata` = NULL,
    `origination_account_id` = NULL,
    `guarantee_decision` = NULL,
    `guarantee_decision_rationale` = NULL,
    `iso_currency_code` = NULL,
    initialize = function(
        `id`, `ach_class`, `account_id`, `type`, `user`, `amount`, `description`, `created`, `status`, `network`, `cancellable`, `failure_reason`, `metadata`, `origination_account_id`, `guarantee_decision`, `guarantee_decision_rationale`, `iso_currency_code`, `sweep_status`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`ach_class`)) {
        stopifnot(R6::is.R6(`ach_class`))
        self$`ach_class` <- `ach_class`
      }
      if (!missing(`account_id`)) {
        stopifnot(is.character(`account_id`), length(`account_id`) == 1)
        self$`account_id` <- `account_id`
      }
      if (!missing(`type`)) {
        stopifnot(R6::is.R6(`type`))
        self$`type` <- `type`
      }
      if (!missing(`user`)) {
        stopifnot(R6::is.R6(`user`))
        self$`user` <- `user`
      }
      if (!missing(`amount`)) {
        stopifnot(is.character(`amount`), length(`amount`) == 1)
        self$`amount` <- `amount`
      }
      if (!missing(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!missing(`created`)) {
        stopifnot(is.character(`created`), length(`created`) == 1)
        self$`created` <- `created`
      }
      if (!missing(`status`)) {
        stopifnot(R6::is.R6(`status`))
        self$`status` <- `status`
      }
      if (!missing(`network`)) {
        stopifnot(R6::is.R6(`network`))
        self$`network` <- `network`
      }
      if (!missing(`cancellable`)) {
        stopifnot(is.logical(`cancellable`), length(`cancellable`) == 1)
        self$`cancellable` <- `cancellable`
      }
      if (!missing(`failure_reason`)) {
        stopifnot(R6::is.R6(`failure_reason`))
        self$`failure_reason` <- `failure_reason`
      }
      if (!missing(`metadata`)) {
        stopifnot(is.vector(`metadata`), length(`metadata`) != 0)
        sapply(`metadata`, function(x) stopifnot(is.character(x)))
        self$`metadata` <- `metadata`
      }
      if (!missing(`origination_account_id`)) {
        stopifnot(is.character(`origination_account_id`), length(`origination_account_id`) == 1)
        self$`origination_account_id` <- `origination_account_id`
      }
      if (!missing(`guarantee_decision`)) {
        stopifnot(R6::is.R6(`guarantee_decision`))
        self$`guarantee_decision` <- `guarantee_decision`
      }
      if (!missing(`guarantee_decision_rationale`)) {
        stopifnot(R6::is.R6(`guarantee_decision_rationale`))
        self$`guarantee_decision_rationale` <- `guarantee_decision_rationale`
      }
      if (!missing(`iso_currency_code`)) {
        stopifnot(is.character(`iso_currency_code`), length(`iso_currency_code`) == 1)
        self$`iso_currency_code` <- `iso_currency_code`
      }
      if (!is.null(`sweep_status`)) {
        stopifnot(R6::is.R6(`sweep_status`))
        self$`sweep_status` <- `sweep_status`
      }
    },
    toJSON = function() {
      TransferObject <- list()
      if (!is.null(self$`id`)) {
        TransferObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`ach_class`)) {
        TransferObject[['ach_class']] <-
          self$`ach_class`$toJSON()
      }
      if (!is.null(self$`account_id`)) {
        TransferObject[['account_id']] <-
          self$`account_id`
      }
      if (!is.null(self$`type`)) {
        TransferObject[['type']] <-
          self$`type`$toJSON()
      }
      if (!is.null(self$`user`)) {
        TransferObject[['user']] <-
          self$`user`$toJSON()
      }
      if (!is.null(self$`amount`)) {
        TransferObject[['amount']] <-
          self$`amount`
      }
      if (!is.null(self$`description`)) {
        TransferObject[['description']] <-
          self$`description`
      }
      if (!is.null(self$`created`)) {
        TransferObject[['created']] <-
          self$`created`
      }
      if (!is.null(self$`status`)) {
        TransferObject[['status']] <-
          self$`status`$toJSON()
      }
      if (!is.null(self$`sweep_status`)) {
        TransferObject[['sweep_status']] <-
          self$`sweep_status`$toJSON()
      }
      if (!is.null(self$`network`)) {
        TransferObject[['network']] <-
          self$`network`$toJSON()
      }
      if (!is.null(self$`cancellable`)) {
        TransferObject[['cancellable']] <-
          self$`cancellable`
      }
      if (!is.null(self$`failure_reason`)) {
        TransferObject[['failure_reason']] <-
          self$`failure_reason`$toJSON()
      }
      if (!is.null(self$`metadata`)) {
        TransferObject[['metadata']] <-
          self$`metadata`
      }
      if (!is.null(self$`origination_account_id`)) {
        TransferObject[['origination_account_id']] <-
          self$`origination_account_id`
      }
      if (!is.null(self$`guarantee_decision`)) {
        TransferObject[['guarantee_decision']] <-
          self$`guarantee_decision`$toJSON()
      }
      if (!is.null(self$`guarantee_decision_rationale`)) {
        TransferObject[['guarantee_decision_rationale']] <-
          self$`guarantee_decision_rationale`$toJSON()
      }
      if (!is.null(self$`iso_currency_code`)) {
        TransferObject[['iso_currency_code']] <-
          self$`iso_currency_code`
      }

      TransferObject
    },
    fromJSON = function(TransferJson) {
      TransferObject <- jsonlite::fromJSON(TransferJson)
      if (!is.null(TransferObject$`id`)) {
        self$`id` <- TransferObject$`id`
      }
      if (!is.null(TransferObject$`ach_class`)) {
        ach_classObject <- ACHClass$new()
        ach_classObject$fromJSON(jsonlite::toJSON(TransferObject$ach_class, auto_unbox = TRUE, digits = NA))
        self$`ach_class` <- ach_classObject
      }
      if (!is.null(TransferObject$`account_id`)) {
        self$`account_id` <- TransferObject$`account_id`
      }
      if (!is.null(TransferObject$`type`)) {
        typeObject <- TransferType$new()
        typeObject$fromJSON(jsonlite::toJSON(TransferObject$type, auto_unbox = TRUE, digits = NA))
        self$`type` <- typeObject
      }
      if (!is.null(TransferObject$`user`)) {
        userObject <- TransferUserInResponse$new()
        userObject$fromJSON(jsonlite::toJSON(TransferObject$user, auto_unbox = TRUE, digits = NA))
        self$`user` <- userObject
      }
      if (!is.null(TransferObject$`amount`)) {
        self$`amount` <- TransferObject$`amount`
      }
      if (!is.null(TransferObject$`description`)) {
        self$`description` <- TransferObject$`description`
      }
      if (!is.null(TransferObject$`created`)) {
        self$`created` <- TransferObject$`created`
      }
      if (!is.null(TransferObject$`status`)) {
        statusObject <- TransferStatus$new()
        statusObject$fromJSON(jsonlite::toJSON(TransferObject$status, auto_unbox = TRUE, digits = NA))
        self$`status` <- statusObject
      }
      if (!is.null(TransferObject$`sweep_status`)) {
        sweep_statusObject <- TransferSweepStatus$new()
        sweep_statusObject$fromJSON(jsonlite::toJSON(TransferObject$sweep_status, auto_unbox = TRUE, digits = NA))
        self$`sweep_status` <- sweep_statusObject
      }
      if (!is.null(TransferObject$`network`)) {
        networkObject <- TransferNetwork$new()
        networkObject$fromJSON(jsonlite::toJSON(TransferObject$network, auto_unbox = TRUE, digits = NA))
        self$`network` <- networkObject
      }
      if (!is.null(TransferObject$`cancellable`)) {
        self$`cancellable` <- TransferObject$`cancellable`
      }
      if (!is.null(TransferObject$`failure_reason`)) {
        failure_reasonObject <- TransferFailure$new()
        failure_reasonObject$fromJSON(jsonlite::toJSON(TransferObject$failure_reason, auto_unbox = TRUE, digits = NA))
        self$`failure_reason` <- failure_reasonObject
      }
      if (!is.null(TransferObject$`metadata`)) {
        self$`metadata` <- ApiClient$new()$deserializeObj(TransferObject$`metadata`, "map(character)", loadNamespace("plaidr"))
      }
      if (!is.null(TransferObject$`origination_account_id`)) {
        self$`origination_account_id` <- TransferObject$`origination_account_id`
      }
      if (!is.null(TransferObject$`guarantee_decision`)) {
        guarantee_decisionObject <- TransferAuthorizationGuaranteeDecision$new()
        guarantee_decisionObject$fromJSON(jsonlite::toJSON(TransferObject$guarantee_decision, auto_unbox = TRUE, digits = NA))
        self$`guarantee_decision` <- guarantee_decisionObject
      }
      if (!is.null(TransferObject$`guarantee_decision_rationale`)) {
        guarantee_decision_rationaleObject <- TransferAuthorizationGuaranteeDecisionRationale$new()
        guarantee_decision_rationaleObject$fromJSON(jsonlite::toJSON(TransferObject$guarantee_decision_rationale, auto_unbox = TRUE, digits = NA))
        self$`guarantee_decision_rationale` <- guarantee_decision_rationaleObject
      }
      if (!is.null(TransferObject$`iso_currency_code`)) {
        self$`iso_currency_code` <- TransferObject$`iso_currency_code`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          "%s"
                ',
        self$`id`
        )},
        if (!is.null(self$`ach_class`)) {
        sprintf(
        '"ach_class":
        %s
        ',
        jsonlite::toJSON(self$`ach_class`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`account_id`)) {
        sprintf(
        '"account_id":
          "%s"
                ',
        self$`account_id`
        )},
        if (!is.null(self$`type`)) {
        sprintf(
        '"type":
        %s
        ',
        jsonlite::toJSON(self$`type`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`user`)) {
        sprintf(
        '"user":
        %s
        ',
        jsonlite::toJSON(self$`user`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`amount`)) {
        sprintf(
        '"amount":
          "%s"
                ',
        self$`amount`
        )},
        if (!is.null(self$`description`)) {
        sprintf(
        '"description":
          "%s"
                ',
        self$`description`
        )},
        if (!is.null(self$`created`)) {
        sprintf(
        '"created":
          "%s"
                ',
        self$`created`
        )},
        if (!is.null(self$`status`)) {
        sprintf(
        '"status":
        %s
        ',
        jsonlite::toJSON(self$`status`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`sweep_status`)) {
        sprintf(
        '"sweep_status":
        %s
        ',
        jsonlite::toJSON(self$`sweep_status`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`network`)) {
        sprintf(
        '"network":
        %s
        ',
        jsonlite::toJSON(self$`network`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`cancellable`)) {
        sprintf(
        '"cancellable":
          %s
                ',
        tolower(self$`cancellable`)
        )},
        if (!is.null(self$`failure_reason`)) {
        sprintf(
        '"failure_reason":
        %s
        ',
        jsonlite::toJSON(self$`failure_reason`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`metadata`)) {
        sprintf(
        '"metadata":
          "%s"
        ',
        jsonlite::toJSON(lapply(self$`metadata`, function(x){ x }), auto_unbox = TRUE, digits=NA)
        )},
        if (!is.null(self$`origination_account_id`)) {
        sprintf(
        '"origination_account_id":
          "%s"
                ',
        self$`origination_account_id`
        )},
        if (!is.null(self$`guarantee_decision`)) {
        sprintf(
        '"guarantee_decision":
        %s
        ',
        jsonlite::toJSON(self$`guarantee_decision`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`guarantee_decision_rationale`)) {
        sprintf(
        '"guarantee_decision_rationale":
        %s
        ',
        jsonlite::toJSON(self$`guarantee_decision_rationale`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`iso_currency_code`)) {
        sprintf(
        '"iso_currency_code":
          "%s"
                ',
        self$`iso_currency_code`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(TransferJson) {
      TransferObject <- jsonlite::fromJSON(TransferJson)
      self$`id` <- TransferObject$`id`
      self$`ach_class` <- ACHClass$new()$fromJSON(jsonlite::toJSON(TransferObject$ach_class, auto_unbox = TRUE, digits = NA))
      self$`account_id` <- TransferObject$`account_id`
      self$`type` <- TransferType$new()$fromJSON(jsonlite::toJSON(TransferObject$type, auto_unbox = TRUE, digits = NA))
      self$`user` <- TransferUserInResponse$new()$fromJSON(jsonlite::toJSON(TransferObject$user, auto_unbox = TRUE, digits = NA))
      self$`amount` <- TransferObject$`amount`
      self$`description` <- TransferObject$`description`
      self$`created` <- TransferObject$`created`
      self$`status` <- TransferStatus$new()$fromJSON(jsonlite::toJSON(TransferObject$status, auto_unbox = TRUE, digits = NA))
      self$`sweep_status` <- TransferSweepStatus$new()$fromJSON(jsonlite::toJSON(TransferObject$sweep_status, auto_unbox = TRUE, digits = NA))
      self$`network` <- TransferNetwork$new()$fromJSON(jsonlite::toJSON(TransferObject$network, auto_unbox = TRUE, digits = NA))
      self$`cancellable` <- TransferObject$`cancellable`
      self$`failure_reason` <- TransferFailure$new()$fromJSON(jsonlite::toJSON(TransferObject$failure_reason, auto_unbox = TRUE, digits = NA))
      self$`metadata` <- ApiClient$new()$deserializeObj(TransferObject$`metadata`, "map(character)", loadNamespace("plaidr"))
      self$`origination_account_id` <- TransferObject$`origination_account_id`
      self$`guarantee_decision` <- TransferAuthorizationGuaranteeDecision$new()$fromJSON(jsonlite::toJSON(TransferObject$guarantee_decision, auto_unbox = TRUE, digits = NA))
      self$`guarantee_decision_rationale` <- TransferAuthorizationGuaranteeDecisionRationale$new()$fromJSON(jsonlite::toJSON(TransferObject$guarantee_decision_rationale, auto_unbox = TRUE, digits = NA))
      self$`iso_currency_code` <- TransferObject$`iso_currency_code`
      self
    }
  )
)
