# The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.146.0
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title TransferIntentGet
#'
#' @description TransferIntentGet Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field id  character 
#'
#' @field created  character 
#'
#' @field status  \link{TransferIntentStatus} 
#'
#' @field transfer_id  character 
#'
#' @field failure_reason  \link{TransferIntentGetFailureReason} 
#'
#' @field authorization_decision  \link{TransferIntentAuthorizationDecision} 
#'
#' @field authorization_decision_rationale  \link{TransferAuthorizationDecisionRationale} 
#'
#' @field account_id  character [optional]
#'
#' @field origination_account_id  character 
#'
#' @field amount TransferAmount character 
#'
#' @field mode  \link{TransferIntentCreateMode} 
#'
#' @field ach_class  \link{ACHClass} 
#'
#' @field user  \link{TransferUserInResponse} 
#'
#' @field description  character 
#'
#' @field metadata TransferMetadata named list( character ) [optional]
#'
#' @field iso_currency_code  character 
#'
#' @field require_guarantee  character [optional]
#'
#' @field guarantee_decision  \link{TransferAuthorizationGuaranteeDecision} 
#'
#' @field guarantee_decision_rationale  \link{TransferAuthorizationGuaranteeDecisionRationale} 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
TransferIntentGet <- R6::R6Class(
  'TransferIntentGet',
  public = list(
    `id` = NULL,
    `created` = NULL,
    `status` = NULL,
    `transfer_id` = NULL,
    `failure_reason` = NULL,
    `authorization_decision` = NULL,
    `authorization_decision_rationale` = NULL,
    `account_id` = NULL,
    `origination_account_id` = NULL,
    `amount` = NULL,
    `mode` = NULL,
    `ach_class` = NULL,
    `user` = NULL,
    `description` = NULL,
    `metadata` = NULL,
    `iso_currency_code` = NULL,
    `require_guarantee` = NULL,
    `guarantee_decision` = NULL,
    `guarantee_decision_rationale` = NULL,
    initialize = function(
        `id`, `created`, `status`, `transfer_id`, `failure_reason`, `authorization_decision`, `authorization_decision_rationale`, `origination_account_id`, `amount`, `mode`, `ach_class`, `user`, `description`, `iso_currency_code`, `guarantee_decision`, `guarantee_decision_rationale`, `account_id`=NULL, `metadata`=NULL, `require_guarantee`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`created`)) {
        stopifnot(is.character(`created`), length(`created`) == 1)
        self$`created` <- `created`
      }
      if (!missing(`status`)) {
        stopifnot(R6::is.R6(`status`))
        self$`status` <- `status`
      }
      if (!missing(`transfer_id`)) {
        stopifnot(is.character(`transfer_id`), length(`transfer_id`) == 1)
        self$`transfer_id` <- `transfer_id`
      }
      if (!missing(`failure_reason`)) {
        stopifnot(R6::is.R6(`failure_reason`))
        self$`failure_reason` <- `failure_reason`
      }
      if (!missing(`authorization_decision`)) {
        stopifnot(R6::is.R6(`authorization_decision`))
        self$`authorization_decision` <- `authorization_decision`
      }
      if (!missing(`authorization_decision_rationale`)) {
        stopifnot(R6::is.R6(`authorization_decision_rationale`))
        self$`authorization_decision_rationale` <- `authorization_decision_rationale`
      }
      if (!missing(`origination_account_id`)) {
        stopifnot(is.character(`origination_account_id`), length(`origination_account_id`) == 1)
        self$`origination_account_id` <- `origination_account_id`
      }
      if (!missing(`amount`)) {
        stopifnot(is.character(`amount`), length(`amount`) == 1)
        self$`amount` <- `amount`
      }
      if (!missing(`mode`)) {
        stopifnot(R6::is.R6(`mode`))
        self$`mode` <- `mode`
      }
      if (!missing(`ach_class`)) {
        stopifnot(R6::is.R6(`ach_class`))
        self$`ach_class` <- `ach_class`
      }
      if (!missing(`user`)) {
        stopifnot(R6::is.R6(`user`))
        self$`user` <- `user`
      }
      if (!missing(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!missing(`iso_currency_code`)) {
        stopifnot(is.character(`iso_currency_code`), length(`iso_currency_code`) == 1)
        self$`iso_currency_code` <- `iso_currency_code`
      }
      if (!missing(`guarantee_decision`)) {
        stopifnot(R6::is.R6(`guarantee_decision`))
        self$`guarantee_decision` <- `guarantee_decision`
      }
      if (!missing(`guarantee_decision_rationale`)) {
        stopifnot(R6::is.R6(`guarantee_decision_rationale`))
        self$`guarantee_decision_rationale` <- `guarantee_decision_rationale`
      }
      if (!is.null(`account_id`)) {
        stopifnot(is.character(`account_id`), length(`account_id`) == 1)
        self$`account_id` <- `account_id`
      }
      if (!is.null(`metadata`)) {
        stopifnot(is.vector(`metadata`), length(`metadata`) != 0)
        sapply(`metadata`, function(x) stopifnot(is.character(x)))
        self$`metadata` <- `metadata`
      }
      if (!is.null(`require_guarantee`)) {
        stopifnot(is.logical(`require_guarantee`), length(`require_guarantee`) == 1)
        self$`require_guarantee` <- `require_guarantee`
      }
    },
    toJSON = function() {
      TransferIntentGetObject <- list()
      if (!is.null(self$`id`)) {
        TransferIntentGetObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`created`)) {
        TransferIntentGetObject[['created']] <-
          self$`created`
      }
      if (!is.null(self$`status`)) {
        TransferIntentGetObject[['status']] <-
          self$`status`$toJSON()
      }
      if (!is.null(self$`transfer_id`)) {
        TransferIntentGetObject[['transfer_id']] <-
          self$`transfer_id`
      }
      if (!is.null(self$`failure_reason`)) {
        TransferIntentGetObject[['failure_reason']] <-
          self$`failure_reason`$toJSON()
      }
      if (!is.null(self$`authorization_decision`)) {
        TransferIntentGetObject[['authorization_decision']] <-
          self$`authorization_decision`$toJSON()
      }
      if (!is.null(self$`authorization_decision_rationale`)) {
        TransferIntentGetObject[['authorization_decision_rationale']] <-
          self$`authorization_decision_rationale`$toJSON()
      }
      if (!is.null(self$`account_id`)) {
        TransferIntentGetObject[['account_id']] <-
          self$`account_id`
      }
      if (!is.null(self$`origination_account_id`)) {
        TransferIntentGetObject[['origination_account_id']] <-
          self$`origination_account_id`
      }
      if (!is.null(self$`amount`)) {
        TransferIntentGetObject[['amount']] <-
          self$`amount`
      }
      if (!is.null(self$`mode`)) {
        TransferIntentGetObject[['mode']] <-
          self$`mode`$toJSON()
      }
      if (!is.null(self$`ach_class`)) {
        TransferIntentGetObject[['ach_class']] <-
          self$`ach_class`$toJSON()
      }
      if (!is.null(self$`user`)) {
        TransferIntentGetObject[['user']] <-
          self$`user`$toJSON()
      }
      if (!is.null(self$`description`)) {
        TransferIntentGetObject[['description']] <-
          self$`description`
      }
      if (!is.null(self$`metadata`)) {
        TransferIntentGetObject[['metadata']] <-
          self$`metadata`
      }
      if (!is.null(self$`iso_currency_code`)) {
        TransferIntentGetObject[['iso_currency_code']] <-
          self$`iso_currency_code`
      }
      if (!is.null(self$`require_guarantee`)) {
        TransferIntentGetObject[['require_guarantee']] <-
          self$`require_guarantee`
      }
      if (!is.null(self$`guarantee_decision`)) {
        TransferIntentGetObject[['guarantee_decision']] <-
          self$`guarantee_decision`$toJSON()
      }
      if (!is.null(self$`guarantee_decision_rationale`)) {
        TransferIntentGetObject[['guarantee_decision_rationale']] <-
          self$`guarantee_decision_rationale`$toJSON()
      }

      TransferIntentGetObject
    },
    fromJSON = function(TransferIntentGetJson) {
      TransferIntentGetObject <- jsonlite::fromJSON(TransferIntentGetJson)
      if (!is.null(TransferIntentGetObject$`id`)) {
        self$`id` <- TransferIntentGetObject$`id`
      }
      if (!is.null(TransferIntentGetObject$`created`)) {
        self$`created` <- TransferIntentGetObject$`created`
      }
      if (!is.null(TransferIntentGetObject$`status`)) {
        statusObject <- TransferIntentStatus$new()
        statusObject$fromJSON(jsonlite::toJSON(TransferIntentGetObject$status, auto_unbox = TRUE, digits = NA))
        self$`status` <- statusObject
      }
      if (!is.null(TransferIntentGetObject$`transfer_id`)) {
        self$`transfer_id` <- TransferIntentGetObject$`transfer_id`
      }
      if (!is.null(TransferIntentGetObject$`failure_reason`)) {
        failure_reasonObject <- TransferIntentGetFailureReason$new()
        failure_reasonObject$fromJSON(jsonlite::toJSON(TransferIntentGetObject$failure_reason, auto_unbox = TRUE, digits = NA))
        self$`failure_reason` <- failure_reasonObject
      }
      if (!is.null(TransferIntentGetObject$`authorization_decision`)) {
        authorization_decisionObject <- TransferIntentAuthorizationDecision$new()
        authorization_decisionObject$fromJSON(jsonlite::toJSON(TransferIntentGetObject$authorization_decision, auto_unbox = TRUE, digits = NA))
        self$`authorization_decision` <- authorization_decisionObject
      }
      if (!is.null(TransferIntentGetObject$`authorization_decision_rationale`)) {
        authorization_decision_rationaleObject <- TransferAuthorizationDecisionRationale$new()
        authorization_decision_rationaleObject$fromJSON(jsonlite::toJSON(TransferIntentGetObject$authorization_decision_rationale, auto_unbox = TRUE, digits = NA))
        self$`authorization_decision_rationale` <- authorization_decision_rationaleObject
      }
      if (!is.null(TransferIntentGetObject$`account_id`)) {
        self$`account_id` <- TransferIntentGetObject$`account_id`
      }
      if (!is.null(TransferIntentGetObject$`origination_account_id`)) {
        self$`origination_account_id` <- TransferIntentGetObject$`origination_account_id`
      }
      if (!is.null(TransferIntentGetObject$`amount`)) {
        self$`amount` <- TransferIntentGetObject$`amount`
      }
      if (!is.null(TransferIntentGetObject$`mode`)) {
        modeObject <- TransferIntentCreateMode$new()
        modeObject$fromJSON(jsonlite::toJSON(TransferIntentGetObject$mode, auto_unbox = TRUE, digits = NA))
        self$`mode` <- modeObject
      }
      if (!is.null(TransferIntentGetObject$`ach_class`)) {
        ach_classObject <- ACHClass$new()
        ach_classObject$fromJSON(jsonlite::toJSON(TransferIntentGetObject$ach_class, auto_unbox = TRUE, digits = NA))
        self$`ach_class` <- ach_classObject
      }
      if (!is.null(TransferIntentGetObject$`user`)) {
        userObject <- TransferUserInResponse$new()
        userObject$fromJSON(jsonlite::toJSON(TransferIntentGetObject$user, auto_unbox = TRUE, digits = NA))
        self$`user` <- userObject
      }
      if (!is.null(TransferIntentGetObject$`description`)) {
        self$`description` <- TransferIntentGetObject$`description`
      }
      if (!is.null(TransferIntentGetObject$`metadata`)) {
        self$`metadata` <- ApiClient$new()$deserializeObj(TransferIntentGetObject$`metadata`, "map(character)", loadNamespace("plaidr"))
      }
      if (!is.null(TransferIntentGetObject$`iso_currency_code`)) {
        self$`iso_currency_code` <- TransferIntentGetObject$`iso_currency_code`
      }
      if (!is.null(TransferIntentGetObject$`require_guarantee`)) {
        self$`require_guarantee` <- TransferIntentGetObject$`require_guarantee`
      }
      if (!is.null(TransferIntentGetObject$`guarantee_decision`)) {
        guarantee_decisionObject <- TransferAuthorizationGuaranteeDecision$new()
        guarantee_decisionObject$fromJSON(jsonlite::toJSON(TransferIntentGetObject$guarantee_decision, auto_unbox = TRUE, digits = NA))
        self$`guarantee_decision` <- guarantee_decisionObject
      }
      if (!is.null(TransferIntentGetObject$`guarantee_decision_rationale`)) {
        guarantee_decision_rationaleObject <- TransferAuthorizationGuaranteeDecisionRationale$new()
        guarantee_decision_rationaleObject$fromJSON(jsonlite::toJSON(TransferIntentGetObject$guarantee_decision_rationale, auto_unbox = TRUE, digits = NA))
        self$`guarantee_decision_rationale` <- guarantee_decision_rationaleObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          "%s"
                ',
        self$`id`
        )},
        if (!is.null(self$`created`)) {
        sprintf(
        '"created":
          "%s"
                ',
        self$`created`
        )},
        if (!is.null(self$`status`)) {
        sprintf(
        '"status":
        %s
        ',
        jsonlite::toJSON(self$`status`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`transfer_id`)) {
        sprintf(
        '"transfer_id":
          "%s"
                ',
        self$`transfer_id`
        )},
        if (!is.null(self$`failure_reason`)) {
        sprintf(
        '"failure_reason":
        %s
        ',
        jsonlite::toJSON(self$`failure_reason`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`authorization_decision`)) {
        sprintf(
        '"authorization_decision":
        %s
        ',
        jsonlite::toJSON(self$`authorization_decision`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`authorization_decision_rationale`)) {
        sprintf(
        '"authorization_decision_rationale":
        %s
        ',
        jsonlite::toJSON(self$`authorization_decision_rationale`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`account_id`)) {
        sprintf(
        '"account_id":
          "%s"
                ',
        self$`account_id`
        )},
        if (!is.null(self$`origination_account_id`)) {
        sprintf(
        '"origination_account_id":
          "%s"
                ',
        self$`origination_account_id`
        )},
        if (!is.null(self$`amount`)) {
        sprintf(
        '"amount":
          "%s"
                ',
        self$`amount`
        )},
        if (!is.null(self$`mode`)) {
        sprintf(
        '"mode":
        %s
        ',
        jsonlite::toJSON(self$`mode`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`ach_class`)) {
        sprintf(
        '"ach_class":
        %s
        ',
        jsonlite::toJSON(self$`ach_class`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`user`)) {
        sprintf(
        '"user":
        %s
        ',
        jsonlite::toJSON(self$`user`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`description`)) {
        sprintf(
        '"description":
          "%s"
                ',
        self$`description`
        )},
        if (!is.null(self$`metadata`)) {
        sprintf(
        '"metadata":
          "%s"
        ',
        jsonlite::toJSON(lapply(self$`metadata`, function(x){ x }), auto_unbox = TRUE, digits=NA)
        )},
        if (!is.null(self$`iso_currency_code`)) {
        sprintf(
        '"iso_currency_code":
          "%s"
                ',
        self$`iso_currency_code`
        )},
        if (!is.null(self$`require_guarantee`)) {
        sprintf(
        '"require_guarantee":
          %s
                ',
        tolower(self$`require_guarantee`)
        )},
        if (!is.null(self$`guarantee_decision`)) {
        sprintf(
        '"guarantee_decision":
        %s
        ',
        jsonlite::toJSON(self$`guarantee_decision`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`guarantee_decision_rationale`)) {
        sprintf(
        '"guarantee_decision_rationale":
        %s
        ',
        jsonlite::toJSON(self$`guarantee_decision_rationale`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(TransferIntentGetJson) {
      TransferIntentGetObject <- jsonlite::fromJSON(TransferIntentGetJson)
      self$`id` <- TransferIntentGetObject$`id`
      self$`created` <- TransferIntentGetObject$`created`
      self$`status` <- TransferIntentStatus$new()$fromJSON(jsonlite::toJSON(TransferIntentGetObject$status, auto_unbox = TRUE, digits = NA))
      self$`transfer_id` <- TransferIntentGetObject$`transfer_id`
      self$`failure_reason` <- TransferIntentGetFailureReason$new()$fromJSON(jsonlite::toJSON(TransferIntentGetObject$failure_reason, auto_unbox = TRUE, digits = NA))
      self$`authorization_decision` <- TransferIntentAuthorizationDecision$new()$fromJSON(jsonlite::toJSON(TransferIntentGetObject$authorization_decision, auto_unbox = TRUE, digits = NA))
      self$`authorization_decision_rationale` <- TransferAuthorizationDecisionRationale$new()$fromJSON(jsonlite::toJSON(TransferIntentGetObject$authorization_decision_rationale, auto_unbox = TRUE, digits = NA))
      self$`account_id` <- TransferIntentGetObject$`account_id`
      self$`origination_account_id` <- TransferIntentGetObject$`origination_account_id`
      self$`amount` <- TransferIntentGetObject$`amount`
      self$`mode` <- TransferIntentCreateMode$new()$fromJSON(jsonlite::toJSON(TransferIntentGetObject$mode, auto_unbox = TRUE, digits = NA))
      self$`ach_class` <- ACHClass$new()$fromJSON(jsonlite::toJSON(TransferIntentGetObject$ach_class, auto_unbox = TRUE, digits = NA))
      self$`user` <- TransferUserInResponse$new()$fromJSON(jsonlite::toJSON(TransferIntentGetObject$user, auto_unbox = TRUE, digits = NA))
      self$`description` <- TransferIntentGetObject$`description`
      self$`metadata` <- ApiClient$new()$deserializeObj(TransferIntentGetObject$`metadata`, "map(character)", loadNamespace("plaidr"))
      self$`iso_currency_code` <- TransferIntentGetObject$`iso_currency_code`
      self$`require_guarantee` <- TransferIntentGetObject$`require_guarantee`
      self$`guarantee_decision` <- TransferAuthorizationGuaranteeDecision$new()$fromJSON(jsonlite::toJSON(TransferIntentGetObject$guarantee_decision, auto_unbox = TRUE, digits = NA))
      self$`guarantee_decision_rationale` <- TransferAuthorizationGuaranteeDecisionRationale$new()$fromJSON(jsonlite::toJSON(TransferIntentGetObject$guarantee_decision_rationale, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)
