# The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.146.0
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title WalletTransactionCounterparty
#'
#' @description WalletTransactionCounterparty Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field name  character 
#'
#' @field numbers  \link{WalletTransactionCounterpartyNumbers} 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
WalletTransactionCounterparty <- R6::R6Class(
  'WalletTransactionCounterparty',
  public = list(
    `name` = NULL,
    `numbers` = NULL,
    initialize = function(
        `name`, `numbers`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`numbers`)) {
        stopifnot(R6::is.R6(`numbers`))
        self$`numbers` <- `numbers`
      }
    },
    toJSON = function() {
      WalletTransactionCounterpartyObject <- list()
      if (!is.null(self$`name`)) {
        WalletTransactionCounterpartyObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`numbers`)) {
        WalletTransactionCounterpartyObject[['numbers']] <-
          self$`numbers`$toJSON()
      }

      WalletTransactionCounterpartyObject
    },
    fromJSON = function(WalletTransactionCounterpartyJson) {
      WalletTransactionCounterpartyObject <- jsonlite::fromJSON(WalletTransactionCounterpartyJson)
      if (!is.null(WalletTransactionCounterpartyObject$`name`)) {
        self$`name` <- WalletTransactionCounterpartyObject$`name`
      }
      if (!is.null(WalletTransactionCounterpartyObject$`numbers`)) {
        numbersObject <- WalletTransactionCounterpartyNumbers$new()
        numbersObject$fromJSON(jsonlite::toJSON(WalletTransactionCounterpartyObject$numbers, auto_unbox = TRUE, digits = NA))
        self$`numbers` <- numbersObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`numbers`)) {
        sprintf(
        '"numbers":
        %s
        ',
        jsonlite::toJSON(self$`numbers`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(WalletTransactionCounterpartyJson) {
      WalletTransactionCounterpartyObject <- jsonlite::fromJSON(WalletTransactionCounterpartyJson)
      self$`name` <- WalletTransactionCounterpartyObject$`name`
      self$`numbers` <- WalletTransactionCounterpartyNumbers$new()$fromJSON(jsonlite::toJSON(WalletTransactionCounterpartyObject$numbers, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)
