# The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.146.0
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title WalletBalance
#'
#' @description WalletBalance Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field iso_currency_code  character 
#'
#' @field current  numeric 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
WalletBalance <- R6::R6Class(
  'WalletBalance',
  public = list(
    `iso_currency_code` = NULL,
    `current` = NULL,
    initialize = function(
        `iso_currency_code`, `current`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`iso_currency_code`)) {
        stopifnot(is.character(`iso_currency_code`), length(`iso_currency_code`) == 1)
        self$`iso_currency_code` <- `iso_currency_code`
      }
      if (!missing(`current`)) {
        stopifnot(is.numeric(`current`), length(`current`) == 1)
        self$`current` <- `current`
      }
    },
    toJSON = function() {
      WalletBalanceObject <- list()
      if (!is.null(self$`iso_currency_code`)) {
        WalletBalanceObject[['iso_currency_code']] <-
          self$`iso_currency_code`
      }
      if (!is.null(self$`current`)) {
        WalletBalanceObject[['current']] <-
          self$`current`
      }

      WalletBalanceObject
    },
    fromJSON = function(WalletBalanceJson) {
      WalletBalanceObject <- jsonlite::fromJSON(WalletBalanceJson)
      if (!is.null(WalletBalanceObject$`iso_currency_code`)) {
        self$`iso_currency_code` <- WalletBalanceObject$`iso_currency_code`
      }
      if (!is.null(WalletBalanceObject$`current`)) {
        self$`current` <- WalletBalanceObject$`current`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`iso_currency_code`)) {
        sprintf(
        '"iso_currency_code":
          "%s"
                ',
        self$`iso_currency_code`
        )},
        if (!is.null(self$`current`)) {
        sprintf(
        '"current":
          %d
                ',
        self$`current`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(WalletBalanceJson) {
      WalletBalanceObject <- jsonlite::fromJSON(WalletBalanceJson)
      self$`iso_currency_code` <- WalletBalanceObject$`iso_currency_code`
      self$`current` <- WalletBalanceObject$`current`
      self
    }
  )
)
