# The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.146.0
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title WalletTransactionGetResponse
#'
#' @description WalletTransactionGetResponse Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field transaction_id  character 
#'
#' @field reference  character 
#'
#' @field type  character 
#'
#' @field amount  \link{WalletTransactionAmount} 
#'
#' @field counterparty  \link{WalletTransactionCounterparty} 
#'
#' @field status  \link{WalletTransactionStatus} 
#'
#' @field created_at  character 
#'
#' @field request_id RequestID character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
WalletTransactionGetResponse <- R6::R6Class(
  'WalletTransactionGetResponse',
  public = list(
    `transaction_id` = NULL,
    `reference` = NULL,
    `type` = NULL,
    `amount` = NULL,
    `counterparty` = NULL,
    `status` = NULL,
    `created_at` = NULL,
    `request_id` = NULL,
    initialize = function(
        `transaction_id`, `reference`, `type`, `amount`, `counterparty`, `status`, `created_at`, `request_id`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`transaction_id`)) {
        stopifnot(is.character(`transaction_id`), length(`transaction_id`) == 1)
        self$`transaction_id` <- `transaction_id`
      }
      if (!missing(`reference`)) {
        stopifnot(is.character(`reference`), length(`reference`) == 1)
        self$`reference` <- `reference`
      }
      if (!missing(`type`)) {
        stopifnot(is.character(`type`), length(`type`) == 1)
        self$`type` <- `type`
      }
      if (!missing(`amount`)) {
        stopifnot(R6::is.R6(`amount`))
        self$`amount` <- `amount`
      }
      if (!missing(`counterparty`)) {
        stopifnot(R6::is.R6(`counterparty`))
        self$`counterparty` <- `counterparty`
      }
      if (!missing(`status`)) {
        stopifnot(R6::is.R6(`status`))
        self$`status` <- `status`
      }
      if (!missing(`created_at`)) {
        stopifnot(is.character(`created_at`), length(`created_at`) == 1)
        self$`created_at` <- `created_at`
      }
      if (!missing(`request_id`)) {
        stopifnot(is.character(`request_id`), length(`request_id`) == 1)
        self$`request_id` <- `request_id`
      }
    },
    toJSON = function() {
      WalletTransactionGetResponseObject <- list()
      if (!is.null(self$`transaction_id`)) {
        WalletTransactionGetResponseObject[['transaction_id']] <-
          self$`transaction_id`
      }
      if (!is.null(self$`reference`)) {
        WalletTransactionGetResponseObject[['reference']] <-
          self$`reference`
      }
      if (!is.null(self$`type`)) {
        WalletTransactionGetResponseObject[['type']] <-
          self$`type`
      }
      if (!is.null(self$`amount`)) {
        WalletTransactionGetResponseObject[['amount']] <-
          self$`amount`$toJSON()
      }
      if (!is.null(self$`counterparty`)) {
        WalletTransactionGetResponseObject[['counterparty']] <-
          self$`counterparty`$toJSON()
      }
      if (!is.null(self$`status`)) {
        WalletTransactionGetResponseObject[['status']] <-
          self$`status`$toJSON()
      }
      if (!is.null(self$`created_at`)) {
        WalletTransactionGetResponseObject[['created_at']] <-
          self$`created_at`
      }
      if (!is.null(self$`request_id`)) {
        WalletTransactionGetResponseObject[['request_id']] <-
          self$`request_id`
      }

      WalletTransactionGetResponseObject
    },
    fromJSON = function(WalletTransactionGetResponseJson) {
      WalletTransactionGetResponseObject <- jsonlite::fromJSON(WalletTransactionGetResponseJson)
      if (!is.null(WalletTransactionGetResponseObject$`transaction_id`)) {
        self$`transaction_id` <- WalletTransactionGetResponseObject$`transaction_id`
      }
      if (!is.null(WalletTransactionGetResponseObject$`reference`)) {
        self$`reference` <- WalletTransactionGetResponseObject$`reference`
      }
      if (!is.null(WalletTransactionGetResponseObject$`type`)) {
        self$`type` <- WalletTransactionGetResponseObject$`type`
      }
      if (!is.null(WalletTransactionGetResponseObject$`amount`)) {
        amountObject <- WalletTransactionAmount$new()
        amountObject$fromJSON(jsonlite::toJSON(WalletTransactionGetResponseObject$amount, auto_unbox = TRUE, digits = NA))
        self$`amount` <- amountObject
      }
      if (!is.null(WalletTransactionGetResponseObject$`counterparty`)) {
        counterpartyObject <- WalletTransactionCounterparty$new()
        counterpartyObject$fromJSON(jsonlite::toJSON(WalletTransactionGetResponseObject$counterparty, auto_unbox = TRUE, digits = NA))
        self$`counterparty` <- counterpartyObject
      }
      if (!is.null(WalletTransactionGetResponseObject$`status`)) {
        statusObject <- WalletTransactionStatus$new()
        statusObject$fromJSON(jsonlite::toJSON(WalletTransactionGetResponseObject$status, auto_unbox = TRUE, digits = NA))
        self$`status` <- statusObject
      }
      if (!is.null(WalletTransactionGetResponseObject$`created_at`)) {
        self$`created_at` <- WalletTransactionGetResponseObject$`created_at`
      }
      if (!is.null(WalletTransactionGetResponseObject$`request_id`)) {
        self$`request_id` <- WalletTransactionGetResponseObject$`request_id`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`transaction_id`)) {
        sprintf(
        '"transaction_id":
          "%s"
                ',
        self$`transaction_id`
        )},
        if (!is.null(self$`reference`)) {
        sprintf(
        '"reference":
          "%s"
                ',
        self$`reference`
        )},
        if (!is.null(self$`type`)) {
        sprintf(
        '"type":
          "%s"
                ',
        self$`type`
        )},
        if (!is.null(self$`amount`)) {
        sprintf(
        '"amount":
        %s
        ',
        jsonlite::toJSON(self$`amount`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`counterparty`)) {
        sprintf(
        '"counterparty":
        %s
        ',
        jsonlite::toJSON(self$`counterparty`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`status`)) {
        sprintf(
        '"status":
        %s
        ',
        jsonlite::toJSON(self$`status`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`created_at`)) {
        sprintf(
        '"created_at":
          "%s"
                ',
        self$`created_at`
        )},
        if (!is.null(self$`request_id`)) {
        sprintf(
        '"request_id":
          "%s"
                ',
        self$`request_id`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(WalletTransactionGetResponseJson) {
      WalletTransactionGetResponseObject <- jsonlite::fromJSON(WalletTransactionGetResponseJson)
      self$`transaction_id` <- WalletTransactionGetResponseObject$`transaction_id`
      self$`reference` <- WalletTransactionGetResponseObject$`reference`
      self$`type` <- WalletTransactionGetResponseObject$`type`
      self$`amount` <- WalletTransactionAmount$new()$fromJSON(jsonlite::toJSON(WalletTransactionGetResponseObject$amount, auto_unbox = TRUE, digits = NA))
      self$`counterparty` <- WalletTransactionCounterparty$new()$fromJSON(jsonlite::toJSON(WalletTransactionGetResponseObject$counterparty, auto_unbox = TRUE, digits = NA))
      self$`status` <- WalletTransactionStatus$new()$fromJSON(jsonlite::toJSON(WalletTransactionGetResponseObject$status, auto_unbox = TRUE, digits = NA))
      self$`created_at` <- WalletTransactionGetResponseObject$`created_at`
      self$`request_id` <- WalletTransactionGetResponseObject$`request_id`
      self
    }
  )
)
