# The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.146.0
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Wallet
#'
#' @description Wallet Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field wallet_id  character 
#'
#' @field balance  \link{WalletBalance} 
#'
#' @field numbers  \link{WalletNumbers} 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Wallet <- R6::R6Class(
  'Wallet',
  public = list(
    `wallet_id` = NULL,
    `balance` = NULL,
    `numbers` = NULL,
    initialize = function(
        `wallet_id`, `balance`, `numbers`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`wallet_id`)) {
        stopifnot(is.character(`wallet_id`), length(`wallet_id`) == 1)
        self$`wallet_id` <- `wallet_id`
      }
      if (!missing(`balance`)) {
        stopifnot(R6::is.R6(`balance`))
        self$`balance` <- `balance`
      }
      if (!missing(`numbers`)) {
        stopifnot(R6::is.R6(`numbers`))
        self$`numbers` <- `numbers`
      }
    },
    toJSON = function() {
      WalletObject <- list()
      if (!is.null(self$`wallet_id`)) {
        WalletObject[['wallet_id']] <-
          self$`wallet_id`
      }
      if (!is.null(self$`balance`)) {
        WalletObject[['balance']] <-
          self$`balance`$toJSON()
      }
      if (!is.null(self$`numbers`)) {
        WalletObject[['numbers']] <-
          self$`numbers`$toJSON()
      }

      WalletObject
    },
    fromJSON = function(WalletJson) {
      WalletObject <- jsonlite::fromJSON(WalletJson)
      if (!is.null(WalletObject$`wallet_id`)) {
        self$`wallet_id` <- WalletObject$`wallet_id`
      }
      if (!is.null(WalletObject$`balance`)) {
        balanceObject <- WalletBalance$new()
        balanceObject$fromJSON(jsonlite::toJSON(WalletObject$balance, auto_unbox = TRUE, digits = NA))
        self$`balance` <- balanceObject
      }
      if (!is.null(WalletObject$`numbers`)) {
        numbersObject <- WalletNumbers$new()
        numbersObject$fromJSON(jsonlite::toJSON(WalletObject$numbers, auto_unbox = TRUE, digits = NA))
        self$`numbers` <- numbersObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`wallet_id`)) {
        sprintf(
        '"wallet_id":
          "%s"
                ',
        self$`wallet_id`
        )},
        if (!is.null(self$`balance`)) {
        sprintf(
        '"balance":
        %s
        ',
        jsonlite::toJSON(self$`balance`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`numbers`)) {
        sprintf(
        '"numbers":
        %s
        ',
        jsonlite::toJSON(self$`numbers`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(WalletJson) {
      WalletObject <- jsonlite::fromJSON(WalletJson)
      self$`wallet_id` <- WalletObject$`wallet_id`
      self$`balance` <- WalletBalance$new()$fromJSON(jsonlite::toJSON(WalletObject$balance, auto_unbox = TRUE, digits = NA))
      self$`numbers` <- WalletNumbers$new()$fromJSON(jsonlite::toJSON(WalletObject$numbers, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)
